Repository spidernet-io/spiderpool, pull requests merged in 2022-08, with the labels that each got.

#485 E2E: fix eventually for R00006
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required, pr/ready-review

#512 docs: fix some install steps
  docs/usage/install.md
Labels: pr/release/none-required

#517 doc: typo
  docs/usage/install.md
Labels: pr/release/doc

#523 add owner of doc
  CODEOWNERS
Labels: pr/release/none-required

#528 add startup probe for spiderpool agent&controller
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/runtime_status.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-controller/cmd/http_server.go
  cmd/spiderpool-controller/cmd/runtime_status.go
  go.mod
Labels: pr/release/none-required, pr/ready-review

#507 Chopped indexe in node，namespace，pod manager
  pkg/namespacemanager/namespace_manager.go
  pkg/nodemanager/node_manager.go
  pkg/podmanager/pod_manager.go
Labels: pr/release/none-required, pr/ready-review

#530 [docs] updated test docs
  .github/.spelling
  test/doc/annotation.md
  test/doc/assignip.md
  test/doc/cli.md
  test/doc/configmap.md
  test/doc/ippoolcr.md
  test/doc/labelselector.md
  test/doc/metric.md
  test/doc/performance.md
  test/doc/reclaim.md
  test/doc/reliability.md
  test/doc/reservedip.md
Labels: issue/doc, pr/release/none-required

#443 E2E:add case batch create and delete ippool（D00006 and D00004）
  test/e2e/common/spiderpool.go
  test/e2e/ippool/job_pod_test.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required, pr/ready-review

#515 E2E: case G00005, G00007 a dirty IP record in the IPPool shoud be auto clean by Spiderpool
  README.md
  go.mod
  go.sum
  test/e2e/assignip/assignip_test.go
  test/e2e/common/pod.go
  test/e2e/common/tools.go
  test/e2e/ippool/job_pod_test.go
  test/e2e/reclaim/reclaim_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/framework.go
  vendor/github.com/spidernet-io/e2eframework/framework/serviceaccounts.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#520 Change Docs Order
  docs/README.md
  docs/concepts/arch.md
  docs/mkdocs.yml
Labels: pr/approved, pr/release/doc, pr/ready-review

#510 E2E: add e2e case S00003 for spiderpool
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required, pr/ready-review

#558 docs
  .github/.spelling
  .github/codespell-config
  README.md
  docs/concepts/annotation.md
  docs/concepts/config.md
  docs/concepts/metrics.md
  docs/example/ippool-gc.md
  docs/example/statefulset-demo.yaml
  docs/mkdocs.yml
  docs/usage/advance.md
  docs/usage/basic.md
  docs/usage/cidrManager.md
  docs/usage/debug.md
  docs/usage/demo.md
  docs/usage/install.md
  docs/usage/ippool-affinity-namespace.md
  docs/usage/ippool-affinity-node.md
  docs/usage/ippool-affinity-pod.md
  docs/usage/ippool-multi.md
  docs/usage/ippool-namesapce.md
  docs/usage/ipv6.md
  docs/usage/multi-interfaces-annotation.md
  docs/usage/multi-interfaces-cni.md
  docs/usage/statefulset.md
Labels: pr/release/none-required

#542 [docs] updated several files about grammar
  .github/.spelling
  docs/cmdref/spiderpool-agent.md
  docs/cmdref/spiderpool-controller.md
  docs/cmdref/spiderpoolctl.md
  docs/concepts/allocation.md
  docs/concepts/annotation.md
  docs/concepts/arch.md
  docs/concepts/gc.md
  docs/develop/pullrequest.md
Labels: issue/doc, pr/release/none-required

#552 E2E: add test case A00008 for spiderpool
  test/e2e/annotation/annotation_test.go
Labels: pr/release/none-required, pr/ready-review

#555 chore:Rename the Kind of Spiderpool CRDs
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderreservedips.yaml
  charts/spiderpool/templates/cluster-default-ippool.yaml
  charts/spiderpool/templates/webhook.yaml
  cmd/spiderpool-agent/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  pkg/constant/k8s.go
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_reconcile.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/k8s/apis/v1/ippool_types.go
  pkg/k8s/apis/v1/reservedip_types.go
  pkg/k8s/apis/v1/workloadendpoint_types.go
  pkg/k8s/apis/v1/zz_generated.deepcopy.go
  pkg/logutils/log.go
  pkg/logutils/logutils_suite_test.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/common/reservedip.go
  test/e2e/common/spiderpool.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/labelselector/labelselector_test.go
  test/e2e/performance/performance_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required, pr/ready-review

#562 feat:Add webhook for ReservedIP
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderreservedips.yaml
  charts/spiderpool/templates/webhook.yaml
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ip/ips.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/k8s/apis/v1/ippool_types.go
  pkg/k8s/apis/v1/reservedip_types.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/reservedipmanager/reservedip_webhook.go
Labels: pr/release/none-required, pr/ready-review

#567 change tls name of chart values
  .github/workflows/call-lint-chart.yaml
  charts/spiderpool/templates/tls.yaml
  charts/spiderpool/templates/webhook.yaml
  charts/spiderpool/values.yaml
  docs/usage/install.md
  test/Makefile
Labels: pr/release/none-required

#547 correct grammatical errors
  docs/develop/changelog.md
  docs/usage/ippool-affinity-pod.md
Labels: pr/approved, pr/release/none-required

#493 add statefulset support
  .github/.spelling
  .github/workflows/lint-license.yaml
  .github/yamllint-conf.yml
  .licenserc.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/ipam.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  docs/usage/statefulset.md
  go.mod
  pkg/constant/k8s.go
  pkg/gcmanager/README.md
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/pod_informer.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/ipam/convert.go
  pkg/ipam/ipam.go
  pkg/ipam/ipam_config.go
  pkg/ipam/ipam_statefulset.go
  pkg/ipam/tools.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/k8s/apis/v1/ippool_types.go
  pkg/k8s/apis/v1/rbac.go
  pkg/k8s/apis/v1/workloadendpoint_types.go
  pkg/podmanager/pod_manager.go
  pkg/podmanager/utils.go
  pkg/statefulsetmanager/sts_manager.go
  pkg/statefulsetmanager/utils.go
  pkg/types/k8s.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/none-required, pr/ready-review

#568 v0.0.6
  VERSION
Labels: pr/release/none-required

#570 robot update chart and website from to branch github_pages
  docs/404.html
  docs/assets/javascripts/bundle.9c69f0bc.min.js
  docs/assets/javascripts/bundle.9c69f0bc.min.js.map
  docs/assets/javascripts/workers/search.ecf98df9.min.js
  docs/assets/javascripts/workers/search.ecf98df9.min.js.map
  docs/assets/stylesheets/main.476df7d4.min.css
  docs/assets/stylesheets/main.69437709.min.css
  docs/assets/stylesheets/main.69437709.min.css.map
  docs/charts/spiderpool-v0.0.6.tgz
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/ippool/index.html
  docs/concepts/metrics/index.html
  docs/concepts/reservedip/index.html
  docs/concepts/roadmap/index.html
  docs/concepts/workloadendpoint/index.html
  docs/develop/changelog/index.html
  docs/develop/pullrequest/index.html
  docs/develop/release/index.html
  docs/develop/swagger_openapi/index.html
  docs/develop/test/index.html
  docs/example/ippool-gc/index.html
  docs/example/statefulset-demo.yaml
  docs/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/basic/index.html
  docs/usage/cidrManager/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namesapce/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/multi-interfaces-cni/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/statefulset/index.html
Labels: pr/release/robot_update_githubpage

#569 robot update changelog with tag v0.0.6 to branch github_pages
  changelogs/v0.0.5-to-v0.0.6.md
Labels: pr/release/robot_update_githubpage

#575 workflow: check chart version
  .github/workflows/call-lint-chart.yaml
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required

#532 E2E: case L00007 Succeed to run daemonSet/pod who is cross-zone daemonSet with matched nodeSelector
  test/doc/labelselector.md
  test/e2e/labelselector/labelselector_test.go
Labels: pr/release/none-required, pr/ready-review

#541 E2E: update case G00003 add deployment,statefulSet, daemonSet...
  test/e2e/reclaim/reclaim_test.go
Labels: pr/release/none-required, pr/ready-review

#580 fix:Limiter holds lock for too long
  pkg/limiter/queue.go
Labels: pr/release/bug, pr/ready-review

#579 robot update changelog with tag v0.0.6 to branch github_pages
  changelogs/v0.0.5-to-v0.0.6.md
Labels: pr/release/robot_update_githubpage

#578 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-v0.0.6.tgz
  docs/index.yaml
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#585 chart: new tolerations for agent
  charts/spiderpool/LICENSE
  charts/spiderpool/values.yaml
Labels: pr/release/none-required

#587 fix: spiderpool-controller encounter "too many open files" error
  .github/.spelling
  LICENSE
  cmd/spiderpoolctl/cmd/command_ip.go
  docs/usage/install.md
  test/Makefile
  test/Makefile.defs
  test/e2e/reliability/reliability_test.go
  test/scripts/debugEnv.sh
  test/yamls/kind-config.tmpl
Labels: pr/release/bug

#589 e2e: use latest k8s version
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/call-lint-chart.yaml
  test/Makefile
  test/Makefile.defs
  test/yamls/kind-config.tmpl
Labels: pr/release/none-required

#557 E2E: add test case A00007 for spiderpool
  test/e2e/annotation/annotation_test.go
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: pr/release/none-required, pr/ready-review

#591 version: 0.0.7
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required

#593 robot update changelog with tag v0.0.7 to branch github_pages
  changelogs/v0.0.6-to-v0.0.7.md
Labels: pr/release/robot_update_githubpage

#592 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-v0.0.7.tgz
  docs/index.yaml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/install/index.html
Labels: pr/release/robot_update_githubpage

#594 v0.0.8
  VERSION
  charts/spiderpool/Chart.yaml
  charts/spiderpool/values.yaml
Labels: pr/release/none-required

#595 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-v0.0.8.tgz
  docs/index.yaml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#548 fix ipam default log file
  cmd/spiderpool/cmd/cni_types.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
  cmd/spiderpool/cmd/utils.go
  docs/concepts/config.md
  pkg/logutils/log.go
  pkg/logutils/log_test.go
Labels: pr/release/none-required, pr/ready-review

#597 workflow typo
  .github/workflows/lint-codeowners.yaml
  .github/workflows/lint-markdown.yaml
Labels: pr/release/none-required

#598 add global.imageRegistry to chart values
  .github/workflows/update-chart-readme.yml
  CODEOWNERS
  charts/spiderpool/templates/_helpers.tpl
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  test/Makefile
Labels: pr/release/chart

#602 chart: readme
  .github/markdownlint.yaml
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: pr/release/none-required

#603 v0.0.9
  VERSION
  charts/spiderpool/Chart.yaml
  test/Makefile
  test/scripts/debugEnv.sh
Labels: pr/release/none-required

#605 robot update changelog with tag v0.0.9 to branch github_pages
  changelogs/v0.0.8-to-v0.0.9.md
Labels: pr/release/robot_update_githubpage

#604 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-v0.0.9.tgz
  docs/concepts/config/index.html
  docs/index.yaml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/install/index.html
Labels: pr/release/robot_update_githubpage

#573 feat:Group the routes in IP allocation result by NIC
  api/v1/agent/models/ipam_add_args.go
  api/v1/agent/models/route.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  cmd/spiderpool/cmd/cni_types.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_test.go
  pkg/constant/errors.go
  pkg/constant/ip.go
  pkg/constant/k8s.go
  pkg/ipam/convert.go
  pkg/ipam/ipam.go
  pkg/ipam/ipam_config.go
  pkg/ipam/tools.go
  pkg/ipam/types.go
  pkg/k8s/apis/v1/workloadendpoint_types.go
  pkg/k8s/apis/v1/zz_generated.deepcopy.go
  pkg/types/k8s.go
  test/e2e/annotation/annotation_test.go
Labels: pr/release/none-required, pr/ready-review

#610 E2E: Fixed failed to get masternode when run case L00006
  test/Makefile
  test/e2e/labelselector/labelselector_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required

#609 doc: install
  .github/.spelling
  .github/workflows/update-chart-readme.yml
  charts/spiderpool/README.md
  docs/usage/install.md
  test/Makefile
  test/scripts/debugEnv.sh
Labels: pr/release/none-required

#615 chart: add serviceMonitor
  .github/.spelling
  charts/spiderpool/README.md
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/templates/grafanaDashboard.yaml
  charts/spiderpool/templates/prometheusrule.yaml
  charts/spiderpool/templates/service.yaml
  charts/spiderpool/templates/servicemonitor.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  test/Makefile
  test/yamls/grafanadashboards.yaml
  test/yamls/monitoring.coreos.com_podmonitors.yaml
  test/yamls/monitoring.coreos.com_probes.yaml
  test/yamls/monitoring.coreos.com_prometheusrules.yaml
  test/yamls/monitoring.coreos.com_servicemonitors.yaml
Labels: pr/release/chart

#590 switch webhook health check from L4 to L7
  charts/spiderpool/templates/cluster-default-ippool.yaml
  charts/spiderpool/templates/webhook.yaml
  cmd/spiderpool-agent/cmd/http_server.go
  cmd/spiderpool-agent/cmd/runtime_status.go
  cmd/spiderpool-agent/cmd/unix_server.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/runtime_status.go
  pkg/ippoolmanager/ippool_webhook.go
Labels: pr/release/none-required, pr/ready-review

#621 chart: remove values GcEvictedPodPod
  .github/workflows/lint-spell.yaml
  .github/workflows/update-chart-readme.yml
  charts/spiderpool/templates/deployment.yaml
Labels: pr/release/none-required

#617 remove spiderpool controller env evicted options
  .github/.spelling
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
  docs/cmdref/spiderpool-controller.md
Labels: pr/release/none-required, pr/ready-review

#623 v0.0.10
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required

#624 robot update chart and website from to branch github_pages
  docs/404.html
  docs/charts/spiderpool-v0.0.10.tgz
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/ippool/index.html
  docs/concepts/metrics/index.html
  docs/concepts/reservedip/index.html
  docs/concepts/roadmap/index.html
  docs/concepts/workloadendpoint/index.html
  docs/develop/changelog/index.html
  docs/develop/pullrequest/index.html
  docs/develop/release/index.html
  docs/develop/swagger_openapi/index.html
  docs/develop/test/index.html
  docs/example/ippool-gc/index.html
  docs/index.html
  docs/index.yaml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/basic/index.html
  docs/usage/cidrManager/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namesapce/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/multi-interfaces-cni/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/statefulset/index.html
Labels: pr/release/robot_update_githubpage

#626 fix statefulset markdown format
  docs/usage/statefulset.md
Labels: pr/release/none-required, pr/ready-review

#560 E2E: fix issue 482；improve the api to wait for all pods in the cluste…
  go.mod
  go.sum
  test/e2e/common/node.go
  test/e2e/common/tools.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/daemonset.go
  vendor/github.com/spidernet-io/e2eframework/framework/events.go
  vendor/github.com/spidernet-io/e2eframework/framework/framework.go
  vendor/github.com/spidernet-io/e2eframework/framework/namespace.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/github.com/spidernet-io/e2eframework/framework/serviceaccounts.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review, pr/not-ready

#607 add IP GC design markdown
  .github/.spelling
  pkg/gcmanager/README.md
Labels: pr/release/none-required, pr/ready-review

#629 fix:Parse custom routes defined by Pod annotation panic
  pkg/ipam/convert.go
Labels: pr/release/none-required, pr/ready-review

#584 E2E: FIX update CreateNamespace to CrateNamespaceUntilDefaultServiceAccountReady
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/ippool/job_pod_test.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/labelselector/labelselector_test.go
  test/e2e/performance/performance_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required

#627 E2E add case G00006 "check ip release after job finished" and integrate…
  test/e2e/assignip/assignip_test.go
  test/e2e/common/constant.go
  test/e2e/common/spiderpool.go
  test/e2e/ippool/ippool_suite_test.go
  test/e2e/ippool/job_pod_test.go
  test/e2e/reclaim/reclaim_test.go
Labels: pr/release/none-required, pr/ready-review

#634 E2E: Reduce test time and allow only performance tests to be run in dual stacks.
  .github/workflows/auto-pr-ci.yaml
Labels: pr/release/none-required, pr/ready-review

#638 ci: set --slow-spec-threshold
  test/Makefile
Labels: pr/release/none-required

#639 v0.0.11
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required

#641 robot update changelog with tag v0.0.11 to branch github_pages
  changelogs/v0.0.10-to-v0.0.11.md
Labels: pr/release/robot_update_githubpage

#640 robot update chart and website from to branch github_pages
  docs/404.html
  docs/charts/spiderpool-v0.0.11.tgz
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/ippool/index.html
  docs/concepts/metrics/index.html
  docs/concepts/reservedip/index.html
  docs/concepts/roadmap/index.html
  docs/concepts/workloadendpoint/index.html
  docs/develop/changelog/index.html
  docs/develop/pullrequest/index.html
  docs/develop/release/index.html
  docs/develop/swagger_openapi/index.html
  docs/develop/test/index.html
  docs/example/ippool-gc/index.html
  docs/index.html
  docs/index.yaml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/basic/index.html
  docs/usage/cidrManager/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namespace/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/multi-interfaces-cni/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/statefulset/index.html
Labels: pr/release/robot_update_githubpage

#650 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-v0.1.0.tgz
  docs/index.yaml
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#649 robot update changelog with tag v0.1.0 to branch github_pages
  changelogs/v0.0.11-to-v0.1.0.md
Labels: pr/release/robot_update_githubpage

#588 E2E: case D00002 edit ippool route and gateway
  go.mod
  go.sum
  test/e2e/common/pod.go
  test/e2e/ippoolcr/ippoolcr_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/kind.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#652 E2E: add case A00002 edit pod annotations about route field
  test/e2e/annotation/annotation_test.go
Labels: pr/release/none-required

#654 remove validating webhook post-install
  charts/spiderpool/templates/webhook.yaml
Labels: pr/release/bug, pr/ready-review

#658 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-v0.1.1.tgz
  docs/index.yaml
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#657 robot update changelog with tag v0.1.1 to branch github_pages
  changelogs/v0.1.0-to-v0.1.1.md
Labels: pr/release/robot_update_githubpage

#651 docs:Update docs reserved-ip.md and add some examples
  .github/.spelling
  docs/example/reserved-ip/already-in-use-ippool.yaml
  docs/example/reserved-ip/created-by-someone-else-ippool.yaml
  docs/example/reserved-ip/not-use-excludeips-ippool.yaml
  docs/example/reserved-ip/reservedip-example-deploy.yaml
  docs/example/reserved-ip/test-ipv4-ippool.yaml
  docs/example/reserved-ip/test-ipv4-reservedip.yaml
  docs/example/reserved-ip/use-excludeips-ippool.yaml
  docs/usage/reserved-ip.md
Labels: pr/release/none-required, pr/ready-review

#660 fix leader election log
  pkg/election/lease_election.go
Labels: pr/release/none-required, pr/ready-review

#659 add crd concepts markdown
  .github/.spelling
  docs/concepts/ippool.md
  docs/concepts/reservedip.md
  docs/concepts/spiderendpoint.md
  docs/concepts/spiderippool.md
  docs/concepts/spiderreservedip.md
  docs/concepts/workloadendpoint.md
  docs/mkdocs.yml
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderendpoint_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderreservedip_types.go
Labels: pr/release/none-required, pr/ready-review

#661 docs:Add docs ippool-multi.md
  docs/example/ippool-multi/dummy-pod.yaml
  docs/example/ippool-multi/multi-ippool-example-deploy.yaml
  docs/example/ippool-multi/test-ipv4-ippools.yaml
  docs/usage/ippool-multi.md
Labels: pr/release/none-required, pr/ready-review

#667 docs:Add ippool-affinity-namespace.md
  docs/usage/ippool-affinity-namespace.md
Labels: pr/release/none-required, pr/ready-review

#666 docs:Add docs ippool-affinity-node.md
  docs/usage/ippool-affinity-node.md
Labels: pr/release/none-required, pr/ready-review

#665 docs:Add docs ippool-namespace.md
  docs/example/ippool-namespace/ns1-default-ippool-deploy.yaml
  docs/example/ippool-namespace/ns1-default-ipv4-ippool.yaml
  docs/example/ippool-namespace/ns1-ippool-selection-patch.yaml
  docs/usage/ippool-namespace.md
Labels: pr/release/none-required, pr/ready-review

#664 add multi interfaces docs markdown
  docs/example/ippool-gc.md
  docs/usage/cli.md
  docs/usage/multi-interfaces-annotation.md
  docs/usage/multi-interfaces-cni.md
  docs/usage/statefulset.md
Labels: pr/release/none-required, pr/ready-review

#662 improve ipam plugin installation
  charts/spiderpool/templates/daemonset.yaml
Labels: pr/release/none-required, pr/ready-review
