Repository spidernet-io/spiderpool, pull requests merged in 2022-10, with the labels that each got.

#777 Optimize certificate checking logic
  pkg/cert/gen.go
Labels: pr/release/feature-new

#827 [doc] Updated /usage files
  docs/usage/install.md
  docs/usage/ippool-affinity-namespace.md
  docs/usage/ippool-affinity-node.md
  docs/usage/ippool-affinity-pod.md
  docs/usage/ippool-multi.md
  docs/usage/ippool-namespace.md
  docs/usage/ipv6.md
  docs/usage/multi-interfaces-annotation.md
  docs/usage/multi-interfaces-cni.md
  docs/usage/reserved-ip.md
  docs/usage/statefulset.md
Labels: pr/release/none-required

#779 Set defaults for limiter config
  cmd/spiderpool-agent/cmd/daemon.go
  pkg/ipam/config.go
  pkg/limiter/config.go
  pkg/limiter/queue.go
  pkg/limiter/queue_test.go
Labels: pr/release/none-required, pr/ready-review

#783 Prohibit to create IPv4/6 IPPools when IPv4/6 is disabled
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/config.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/reservedipmanager/config.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_validate.go
Labels: pr/release/none-required, pr/ready-review

#803 Ignore pool selection rules for IPv4/6 IPAM when IPv4/6 is disabled, instead of returning an error
  pkg/ipam/config.go
  pkg/ipam/ipam.go
Labels: pr/release/none-required, pr/ready-review

#830 fix:Wrong import
  cmd/spiderpool-controller/cmd/daemon.go
Labels: pr/release/none-required, pr/ready-review

#832 fix subnet no pointer bug
  pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
  pkg/subnetmanager/deployment_controller.go
  pkg/subnetmanager/subnet_controller.go
  pkg/subnetmanager/utils.go
Labels: pr/release/bug, pr/ready-review

#835 Retain existing labels
  .github/workflows/label-syncer.yaml
Labels: pr/release/none-required, pr/ready-review

#825 E2E: add some apis about spidersubnet
  test/e2e/common/spiderpool.go
  test/e2e/common/spidersubnet.go
Labels: pr/release/none-required

#833 feat:Add K8s event recorder
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/constant/k8s.go
  pkg/event/event.go
Labels: pr/release/feature-new, pr/ready-review

#824 Cascade delete SpiderSubnet and SpiderIPPools controlled by it
  charts/spiderpool/templates/tls.yaml
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook.go
Labels: pr/release/feature-new, pr/ready-review

#843 chart typo
  charts/spiderpool/templates/_helpers.tpl
Labels: pr/release/bug

#841 test:Add test case for setting defaults when new a Limiter
  pkg/limiter/queue_test.go
Labels: pr/release/none-required, pr/ready-review

#836 Return more detailed error message when the Spiderpool CNI bin fails to call
  .github/.spelling
  api/v1/agent/client/daemonset/delete_ipam_ip_responses.go
  api/v1/agent/client/daemonset/delete_ipam_ips_responses.go
  api/v1/agent/client/daemonset/post_ipam_ip_responses.go
  api/v1/agent/client/daemonset/post_ipam_ips_responses.go
  api/v1/agent/models/error.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  api/v1/agent/server/restapi/daemonset/delete_ipam_ip_responses.go
  api/v1/agent/server/restapi/daemonset/delete_ipam_ips_responses.go
  api/v1/agent/server/restapi/daemonset/post_ipam_ip_responses.go
  api/v1/agent/server/restapi/daemonset/post_ipam_ips_responses.go
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/ipam.go
  cmd/spiderpool-agent/cmd/metrics_server.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-controller/cmd/metrics_server.go
  cmd/spiderpool/cmd/cni_types.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
  cmd/spiderpool/cmd/command_test.go
  docs/concepts/config.md
  pkg/config/config.go
  pkg/constant/errors.go
  pkg/constant/k8s.go
  pkg/ipam/config.go
  pkg/ipam/ipam.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/metric/README.md
  pkg/metric/metrics.go
  pkg/metric/metrics_instance.go
  pkg/metric/metrics_ipam.go
  pkg/podmanager/pod_manager.go
  pkg/podmanager/utils.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/e2e/common/constant.go
  test/e2e/common/spiderpool.go
Labels: pr/release/feature-new, pr/ready-review

#861 fix:Missing resource type when cleaning SpiderEndpoint CRs in cleanCRD.sh
  tools/scripts/cleanCRD.sh
Labels: pr/release/bug, pr/ready-review, kind/bug

#859 fix:ApplyPodEntry holds the lock for too long
  pkg/lock/lock_debug.go
Labels: pr/release/none-required, pr/ready-review

#849 doc typo
  docs/usage/spider-subnet.md
Labels: issue/doc, pr/release/none-required, pr/ready-review

#878 chart removes role of secret
  charts/spiderpool/templates/role.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v1/rbac.go
Labels: pr/release/chart

#880 workflow integrate trivy
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/call-lint-chart.yaml
  .github/workflows/call-release-image.yaml
  Makefile
  Makefile.defs
Labels: pr/release/none-required

#879 update vendor to fix CVE-2022-1996
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: pr/release/bug

#887 Update README.md
  README.md
Labels: pr/release/doc

#889 update base image
  .github/codespell-ignorewords
  Makefile
  images/spiderpool-agent/Dockerfile
  images/spiderpool-controller/Dockerfile
Labels: pr/release/none-required

#891 chart: remove useless http header
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/deployment.yaml
Labels: pr/release/none-required

#858 test:Add test for pkg lock
  pkg/limiter/queue_test.go
  pkg/lock/lock_debug.go
  pkg/lock/lock_debug_test.go
  pkg/lock/lock_fast_test.go
  pkg/lock/lock_suite_test.go
Labels: pr/release/none-required, pr/ready-review

#892 feat:Add retry mechanism for updating 'status.freeIPs' of SpiderSubnet
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/ippoolmanager/types/interface.go
  pkg/reservedipmanager/reservedip_webhook.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_webhook.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/feature-new, pr/ready-review

#907 Add the label of its owner SpiderSubnet name to the SpiderIPPool
  pkg/ippoolmanager/ippool_webhook.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/none-required, pr/ready-review

#872 fix:Illegal creation of two SpiderSubnets with the same 'spec.subnet'
  pkg/ip/cidr.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/subnetmanager/subnet_validate.go
Labels: pr/release/bug, pr/ready-review, kind/bug

#910 add debug information and set go max procs
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  test/Makefile
Labels: pr/release/feature-new

#893 fix: ipv6 address validity issue
  test/e2e/annotation/annotation_test.go
  test/e2e/common/spiderpool.go
  test/e2e/common/tools.go
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: pr/release/none-required, pr/ready-review, kind/bug

#908 Docs: fix helm upgrade feature.enableSpiderSubnet
  docs/usage/install.md
  docs/usage/ipv6.md
  docs/usage/spider-subnet.md
  docs/usage/statefulset.md
Labels: issue/doc, pr/release/none-required, pr/ready-review, kind/documentation

#905 Docs: update test case
  test/doc/cidr.md
Labels: issue/doc, pr/release/none-required, pr/ready-review

#911 Add Controlled IPPool IP addresses
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderreservedips.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderendpoint_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderreservedip_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/zz_generated.deepcopy.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/utils.go
Labels: pr/release/none-required, pr/not-ready

#929 fix:Panic when failed to mark an IP allocation
  pkg/ipam/ipam.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/bug, pr/ready-review, kind/bug

#933 feat:Add mutating webhook for SpiderEndpoint
  charts/spiderpool/templates/tls.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_webhook.go
Labels: pr/release/feature-new, pr/ready-review

#931 feat:Enable the RESYNC mechanism of SpiderSubnet Informer
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/feature-new, pr/ready-review

#930 E2E: strength the e2e case P00002
  test/e2e/common/spiderpool.go
  test/e2e/performance/performance_test.go
Labels: pr/release/none-required, pr/ready-review

#913 [docs] updated concept pages
  docs/concepts/annotation.md
  docs/concepts/arch.md
  docs/concepts/config.md
  docs/concepts/gc.md
  docs/concepts/metrics.md
  docs/concepts/roadmap.md
  docs/concepts/spiderendpoint.md
  docs/concepts/spiderippool.md
  docs/concepts/spiderreservedip.md
  docs/concepts/spidersubnet.md
Labels: pr/release/none-required

#936 fix:Failed to remove free IP addresees in SpiderSubnet
  pkg/ippoolmanager/ippool_validate.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_validate.go
Labels: pr/release/bug, pr/ready-review, kind/bug

#939 fix:Duplicated codes in ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/subnetmanager/subnet_validate.go
Labels: pr/release/none-required, pr/ready-review

#940 fix:Avoid ci failure, add workload delete judgement logic
  test/e2e/common/spiderpool.go
Labels: pr/release/none-required, pr/ready-review

#941 test:Add "forgot to start" test to Limiter
  pkg/limiter/queue.go
  pkg/limiter/queue_test.go
Labels: pr/release/none-required, pr/ready-review

#942 Adjust some annotations specifying pool selection rules
  pkg/constant/k8s.go
  pkg/ipam/utils.go
  pkg/types/k8s.go
  test/e2e/common/namespace.go
Labels: pr/release/none-required, pr/ready-review

#944 Return the cause of IPPool being filtered when selecting IPPools
  pkg/ipam/ipam.go
Labels: pr/release/none-required, pr/ready-review

#834 support to scale up and down the IP in auto-created spiderippool
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/constant/k8s.go
  pkg/ipam/ipam.go
  pkg/ippoolmanager/config.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/ippoolmanager/types/interface.go
  pkg/ippoolmanager/utils.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/zz_generated.deepcopy.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/controllers/controller.go
  pkg/subnetmanager/controllers/cronjob_informer.go
  pkg/subnetmanager/controllers/daemonset_informer.go
  pkg/subnetmanager/controllers/deployment_informer.go
  pkg/subnetmanager/controllers/job_informer.go
  pkg/subnetmanager/controllers/replicaset_informer.go
  pkg/subnetmanager/controllers/statefulset_informer.go
  pkg/subnetmanager/controllers/utils.go
  pkg/subnetmanager/deployment_controller.go
  pkg/subnetmanager/subnet_controller.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
  pkg/subnetmanager/utils.go
Labels: pr/release/feature-new, pr/ready-review

#951 fix subnet panic bug
  pkg/ippoolmanager/ippool_informer.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/none-required, pr/ready-review

#952 v0.3.0
  .github/workflows/auto-version-release.yaml
  VERSION
Labels: pr/release/none-required

#864 E2E: add subnet case for spiderpool
  test/e2e/common/constant.go
  test/e2e/common/spidersubnet.go
  test/e2e/subnet/subnet_suite_test.go
  test/e2e/subnet/subnet_test.go
  tools/scripts/e2eperformance.sh
Labels: pr/release/none-required, pr/ready-review

#955 robot update changelog with tag v0.3.0 to branch github_pages
  changelogs/0.3.0-to-v0.3.0.md
Labels: pr/release/robot_update_githubpage

#957 robot update changelog with tag v0.3.0 to branch github_pages
  changelogs/v0.2.3-to-v0.3.0.md
Labels: pr/release/robot_update_githubpage

#958 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.3.0.tgz
  docs/index.yaml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#960 add SpiderSubnet string method
  pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
Labels: pr/release/none-required, pr/ready-review

#959 discard to retry scale IPPool and all error requeue
  cmd/spiderpool-agent/cmd/crd_manager.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
Labels: pr/release/none-required, pr/ready-review

#904 E2E: there are enough resources on the node that the deployment pod will eventually run
  test/e2e/common/deployment.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#961 update doc
  .github/.spelling
  .github/markdownlint.yaml
  docs/develop/release.md
Labels: pr/release/doc

#964 e2e: print detail
  test/scripts/debugEnv.sh
Labels: pr/release/none-required

#966 fix spiderpool-agent oom
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/runtime_status.go
  cmd/spiderpool-agent/cmd/unix_server.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-controller/cmd/runtime_status.go
Labels: pr/release/bug, pr/ready-review

#962 fix ipam get subnet duplicated ippools
  pkg/ipam/ipam.go
Labels: pr/release/bug, pr/ready-review

#967 add event records for SpiderSubnet
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/constant/k8s.go
  pkg/event/event.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/feature-new, pr/ready-review
