Repository spidernet-io/spiderpool, pull requests merged in 2022-12, with the labels that each got.

#1097 test: Add unit tests for pkg ip
  pkg/ip/cidr_test.go
  pkg/ip/ip.go
  pkg/ip/ip_suite_test.go
  pkg/ip/ip_test.go
  pkg/ip/iprange.go
  pkg/ip/iprange_test.go
  pkg/ip/route_test.go
  pkg/ip/utils.go
  pkg/ip/utils_test.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/subnetmanager/subnet_manager.go
  pkg/types/ip.go
  pkg/types/types.go
Labels: pr/release/none-required, pr/ready-review, size/XXL, cherrypick-release-v0.3

#1125 docs: Fix typo 'cleanCRD.sh' -> './cleanCRD.sh'
  docs/usage/install.md
Labels: pr/release/none-required, pr/ready-review, size/XS, cherrypick-release-v0.3

#932 E2E: the same spec is used to create the subnet and only one should succeed
  test/e2e/common/spiderpool.go
  test/e2e/common/spidersubnet.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1138 test: Add unit tests for pkg nodemanager
  go.mod
  go.sum
  pkg/constant/errors.go
  pkg/nodemanager/node_manager.go
  pkg/nodemanager/node_manager_suite_test.go
  pkg/nodemanager/node_manager_test.go
  pkg/nodemanager/nodemanager_suite_test.go
  test/Makefile
  vendor/github.com/agiledragon/gomonkey/v2/LICENSE
  vendor/github.com/agiledragon/gomonkey/v2/README.md
  vendor/github.com/agiledragon/gomonkey/v2/creflect/ae1.17.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/be1.16.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_amd64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_arm64.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_windows.go
  vendor/github.com/agiledragon/gomonkey/v2/patch.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: pr/release/none-required, pr/ready-review, size/L, cherrypick-release-v0.3

#1147 test: Update the descriptions and labels of some specs
  pkg/limiter/limiter_suite_test.go
  pkg/limiter/queue_test.go
  pkg/nodemanager/node_manager_suite_test.go
Labels: pr/release/none-required, pr/ready-review, size/S

#1148 test: Add unit tests for pkg namespacemanager
  pkg/ipam/ipam.go
  pkg/namespacemanager/namespace_manager.go
  pkg/namespacemanager/namespace_manager_suite_test.go
  pkg/namespacemanager/namespace_manager_test.go
  pkg/namespacemanager/namespacemanager_suite_test.go
  pkg/namespacemanager/utils.go
  pkg/namespacemanager/utils_test.go
Labels: pr/release/none-required, pr/ready-review, size/L

#1150 test: Add unit tests for pkg reservedipmanager
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/reservedipmanager/config.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/reservedipmanager/reservedip_manager_suite_test.go
  pkg/reservedipmanager/reservedip_manager_test.go
  pkg/reservedipmanager/reservedip_mutate.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/reservedipmanager/reservedip_webhook.go
  pkg/reservedipmanager/utils.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/none-required, pr/not-ready, size/XL

#1095 E2E: add some cases about updating routes and gateways and excludeIPs.
  test/doc/reservedip.md
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review, pr/not-ready

#1135 add auto-created ippool gc
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/types/interface.go
  pkg/ippoolmanager/utils.go
  pkg/subnetmanager/controllers/utils.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.3

#1141 auto cherry pick PR 1138 to branch release-v0.3
  go.mod
  go.sum
  pkg/constant/errors.go
  pkg/nodemanager/node_manager.go
  pkg/nodemanager/node_manager_suite_test.go
  pkg/nodemanager/node_manager_test.go
  pkg/nodemanager/nodemanager_suite_test.go
  test/Makefile
  vendor/github.com/agiledragon/gomonkey/v2/LICENSE
  vendor/github.com/agiledragon/gomonkey/v2/README.md
  vendor/github.com/agiledragon/gomonkey/v2/creflect/ae1.17.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/be1.16.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_amd64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_arm64.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_windows.go
  vendor/github.com/agiledragon/gomonkey/v2/patch.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: pr/release/none-required, robot-cherrypick

#1158 ci: check label
  .github/workflows/auto-cherrypick.yaml
  .github/workflows/pr-label-check.yaml
Labels: pr/release/none-required

#1156 Revert "Merge pull request #1150 from iiiceoo/ut-rip"
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/reservedipmanager/config.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/reservedipmanager/reservedip_manager_suite_test.go
  pkg/reservedipmanager/reservedip_manager_test.go
  pkg/reservedipmanager/reservedip_mutate.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/reservedipmanager/reservedip_webhook.go
  pkg/reservedipmanager/utils.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/none-required, pr/ready-review

#1152 auto cherry pick PR 1135 to branch release-v0.3
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/types/interface.go
  pkg/ippoolmanager/utils.go
  pkg/subnetmanager/controllers/utils.go
Labels: pr/release/bug, robot-cherrypick

#1159 auto cherry pick PR 1155 to branch release-v0.3
  pkg/ippoolmanager/ippool_informer.go
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/controllers/cronjob_informer.go
  pkg/subnetmanager/controllers/daemonset_informer.go
  pkg/subnetmanager/controllers/deployment_informer.go
  pkg/subnetmanager/controllers/job_informer.go
  pkg/subnetmanager/controllers/replicaset_informer.go
  pkg/subnetmanager/controllers/statefulset_informer.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/bug, robot-cherrypick

#1164 workflow: fix gh cli
  .github/workflows/auto-cherrypick.yaml
  .github/workflows/pr-label-check.yaml
Labels: pr/release/none-required, cherrypick-release-v0.3

#1157 test: Add unit tests for pkg reservedipmanager
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  go.mod
  go.sum
  pkg/constant/ip.go
  pkg/constant/k8s.go
  pkg/ip/cidr_test.go
  pkg/ip/ip_suite_test.go
  pkg/ip/ip_test.go
  pkg/ip/iprange_test.go
  pkg/ip/route_test.go
  pkg/ip/utils_test.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderreservedip_types.go
  pkg/namespacemanager/utils.go
  pkg/namespacemanager/utils_test.go
  pkg/reservedipmanager/config.go
  pkg/reservedipmanager/mock/reservedip_manager_mock.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/reservedipmanager/reservedip_manager_suite_test.go
  pkg/reservedipmanager/reservedip_manager_test.go
  pkg/reservedipmanager/reservedip_mutate.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/reservedipmanager/reservedip_webhook.go
  pkg/reservedipmanager/reservedip_webhook_test.go
  pkg/reservedipmanager/utils.go
  pkg/reservedipmanager/utils_test.go
  pkg/subnetmanager/subnet_manager.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#1140 Modify e2e CI job to be parallel
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/trivy-scan-image.yaml
Labels: pr/release/none-required, pr/ready-review

#1162 change the label of auto-created ippool for GC needs
  .github/.spelling
  docs/develop/upgrade.md
  docs/mkdocs.yml
  docs/usage/spider-subnet.md
  pkg/ippoolmanager/ippool_informer.go
  pkg/subnetmanager/controllers/utils.go
Labels: pr/release/feature-new, pr/ready-review, cherrypick-release-v0.3

#1169 fix: The field `status.allocatedIPCount` of SpiderIPPool was incorrectly updated to -1
  pkg/ippoolmanager/ippool_informer.go
Labels: pr/release/bug, kind/bug, cherrypick-release-v0.3

#1179 cherry pick pr 1662 to release v0.3
  .github/.spelling
  docs/develop/upgrade.md
  docs/mkdocs.yml
  docs/usage/spider-subnet.md
  pkg/ippoolmanager/ippool_informer.go
  pkg/subnetmanager/controllers/utils.go
Labels: pr/release/bug, pr/ready-review, robot-cherrypick

#1177 auto cherry pick PR 1169 to branch release-v0.3
  pkg/ippoolmanager/ippool_informer.go
Labels: pr/release/bug, pr/ready-review, robot-cherrypick

#1173 E2E: The subnet automatically creates an ippool and allocates IP, and should consider reservedIP
  test/doc/annotation.md
  test/doc/cidr.md
  test/e2e/annotation/annotation_suite_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required, pr/ready-review

#1182 bug fix: leak the spiderendpoint of StatefulSet
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/e2e/common/spiderpool.go
  test/scripts/debugEnv.sh
Labels: pr/release/bug, pr/ready-review, kind/bug, cherrypick-release-v0.3

#1188 ci: title for cherry pick pr
  .github/workflows/auto-cherrypick.yaml
Labels: pr/release/none-required

#1186 bug fix: leak the spiderendpoint of StatefulSet
  pkg/gcmanager/tracePod_worker.go
  test/e2e/common/spiderpool.go
  test/scripts/debugEnv.sh
Labels: pr/release/bug, pr/ready-review, kind/bug

#1190 fix: The normal IP addresses are recycled by mistake when multiple Pods with the same namespace and name are created in a short time
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/bug, pr/ready-review, size/S, cherrypick-release-v0.3

#1189 test: Add unit tests for pkg statefulsetmanager
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/namespacemanager/namespace_manager_test.go
  pkg/namespacemanager/utils_test.go
  pkg/nodemanager/node_manager_test.go
  pkg/podmanager/pod_manager_test.go
  pkg/podmanager/utils_test.go
  pkg/statefulsetmanager/sts_manager.go
  pkg/statefulsetmanager/sts_manager_suite_test.go
  pkg/statefulsetmanager/sts_manager_test.go
Labels: pr/release/none-required, pr/ready-review, size/L

#1191 fix: The normal IP addresses are recycled by mistake when multiple Pods with the same namespace and name are created in a short time
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/bug, robot-cherrypick

#1181 test: Add unit tests for pkg workloadendpoint
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  go.mod
  go.sum
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/ipam/ipam.go
  pkg/podmanager/mock/pod_manager_mock.go
  pkg/podmanager/pod_manager_test.go
  pkg/podmanager/utils_test.go
  pkg/reservedipmanager/reservedip_mutate.go
  pkg/workloadendpointmanager/config.go
  pkg/workloadendpointmanager/utils.go
  pkg/workloadendpointmanager/utils_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_suite_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
  pkg/workloadendpointmanager/workloadendpoint_mutate.go
  pkg/workloadendpointmanager/workloadendpoint_webhook.go
  pkg/workloadendpointmanager/workloadendpoint_webhook_test.go
  vendor/github.com/moby/moby/AUTHORS
  vendor/github.com/moby/moby/LICENSE
  vendor/github.com/moby/moby/NOTICE
  vendor/github.com/moby/moby/pkg/stringid/README.md
  vendor/github.com/moby/moby/pkg/stringid/stringid.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review, size/XXL

#1200 No longer validate when deleting SpiderIPPool, SpiderSubnet and SpiderReservedIP
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/podmanager/utils_test.go
  pkg/reservedipmanager/reservedip_webhook.go
  pkg/reservedipmanager/reservedip_webhook_test.go
  pkg/reservedipmanager/utils.go
  pkg/reservedipmanager/utils_test.go
  pkg/subnetmanager/subnet_webhook.go
Labels: pr/release/none-required, pr/ready-review, size/L

#1206 modify charts value comments
  charts/spiderpool/values.yaml
Labels: pr/release/none-required, pr/ready-review

#1151 subnet: accelerate application controllers processing
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  docs/images/spider-subnet-architecture.png
  pkg/ippoolmanager/ippool_informer.go
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/feature-new, pr/release/none-required, pr/ready-review

#1199 E2E: sync default subnet
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_suite_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/common/tools.go
  test/e2e/reclaim/reclaim_suite_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required, pr/ready-review

#1213 Added mkdocs display
  docs/mkdocs.yml
Labels: pr/release/none-required, pr/ready-review

#1222 fix: quickstart docs deployment fails question
  docs/usage/basic.md
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.3

#1223 ci: issue assingees
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/ci-failure.md
  .github/ISSUE_TEMPLATE/doc.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/usage.md
Labels: pr/release/none-required

#1205 Add ClusterDefaultSubnet and SpiderSubnet multiple interfaces support
  .github/.spelling
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-init/cmd/root.go
  docs/concepts/allocation.md
  docs/concepts/annotation.md
  docs/concepts/config.md
  docs/develop/upgrade.md
  docs/example/spider-subnet/cluster-default-subnet-deployment.yaml
  docs/example/spider-subnet/multiple-interfaces.yaml
  docs/usage/spider-subnet.md
  pkg/constant/k8s.go
  pkg/ipam/ipam.go
  pkg/singletons/singleton.go
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/controllers/utils.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
  pkg/types/k8s.go
  pkg/types/types_string.go
  test/Makefile
  test/e2e/reservedip/reservedip_test.go
  test/e2e/subnet/subnet_test.go
  test/scripts/installTestPod.sh
Labels: pr/release/feature-new, pr/ready-review

#1226 Bump Spiderpool version to v0.3.6
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#1228 fix: The "tags" plugin is not installed
  Makefile
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.3

#1229 title: fix: The "tags" plugin is not installed
  Makefile
Labels: robot-cherrypick

#1230 robot update changelog with tag v0.3.6 to branch github_pages
  changelogs/v0.3.5-to-v0.3.6.md
Labels: pr/release/robot_update_githubpage

#1237 robot update changelog with tag v0.4.0-rc1 to branch github_pages
  changelogs/v0.3.5-to-v0.4.0-rc1.md
Labels: pr/release/robot_update_githubpage

#1236 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.4.0-rc1.tgz
  docs/index.yaml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#1233 fix charts value comment
  charts/spiderpool/values.yaml
Labels: pr/release/doc, pr/ready-review

#1239 robot update chart and website from to branch github_pages
  docs/404.html
  docs/charts/spiderpool-0.3.6.tgz
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/metrics/index.html
  docs/concepts/roadmap/index.html
  docs/concepts/spiderendpoint/index.html
  docs/concepts/spiderippool/index.html
  docs/concepts/spiderreservedip/index.html
  docs/concepts/spidersubnet/index.html
  docs/develop/changelog/index.html
  docs/develop/pullrequest/index.html
  docs/develop/release/index.html
  docs/develop/swagger_openapi/index.html
  docs/develop/test/index.html
  docs/develop/upgrade/index.html
  docs/example/spider-subnet/cluster-default-subnet-deployment.yaml
  docs/example/spider-subnet/multiple-interfaces.yaml
  docs/images/spider-subnet-architecture.png
  docs/images/spider.png
  docs/images/spider.svg
  docs/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/basic/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namespace/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/multi-interfaces-cni/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/spider-subnet/index.html
  docs/usage/statefulset/index.html
  docs/usage/third-party-controller/index.html
Labels: pr/release/robot_update_githubpage

#1240 robot update changelog with tag v0.3.6 to branch github_pages
  changelogs/v0.3.5-to-v0.3.6.md
Labels: pr/release/robot_update_githubpage

#1245 ci: changelog
  .github/workflows/call-release-changelog.yaml
Labels: pr/release/none-required

#1249 ci: fix changelog
  .github/changelog_builder_conf.json
  .github/workflows/call-release-changelog.yaml
  tools/scripts/changelog.sh
Labels: pr/release/none-required
