Repository spidernet-io/spiderpool, pull requests merged in 2022-04, with the labels that each got.

#92 Pr/welan/workflow
  .github/workflows/auto-release.yaml
  .github/workflows/build-beta-image.yaml
  .github/workflows/build-image-base.yaml
  .github/workflows/build-image-beta.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/build-image-release.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-image.yaml
  .github/workflows/lint-license.yaml
  .github/workflows/release-chart.yaml
  .github/workflows/robot-update-changelog.yaml
  .licenserc.yaml
  CODEOWNERS
  README.md
  changelogs/README.md
  docs/charts/README.md
  docs/charts/index.html
Labels: pr/release/none-required

#95 typo
  .github/workflows/call-release-chart.yaml
Labels: pr/release/none-required

#96 fix
  .github/workflows/call-release-chart.yaml
Labels: pr/release/none-required

#108 Pr/welan/gcimage
  .github/labels.yml
  .github/workflows/auto-release.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/lint-markdown.yaml
  .github/workflows/lint-yaml.yaml
  .github/workflows/pr-label-assign.yaml
  .github/workflows/pr-label-check.yaml
  docs/contributing/development/changelog.md
  docs/contributing/development/chart.md
  docs/contributing/development/daily_build.md
  docs/contributing/development/github_pages.md
  docs/contributing/development/pullrequest.md
  docs/contributing/development/release.md
Labels: pr/release/none-required

#117 test
  cmd/spiderpool/main.go
  tools/k8s-code-gen/generate-groups.sh
  tools/k8s-code-gen/tools.go
  tools/k8s-code-gen/verify-codegen.sh
  tools/scripts/check-miss-license.sh
Labels: pr/release/none-required

#118 test
  .github/workflows/build-image-ci.yaml
  cmd/spiderpool/main.go
Labels: pr/release/none-required

#119 Pr/welan/delimage
  .github/workflows/auto-clean-image.yaml
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-release.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/call-lint-chart.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/ci-images-cache-cleaner.yaml
  .github/workflows/close-stale-issues-pr.yaml
  .github/workflows/label-syncer.yaml
  .github/workflows/lint-golang.yaml
  CODEOWNERS
Labels: pr/release/none-required

#124 workflow spell
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/codespell-config
  .github/codespell-ignorewords
  .github/labels.yml
  .github/workflows/auto-release.yaml
  .github/workflows/call-lint-chart.yaml
  .github/workflows/pr-label-check.yaml
  Makefile
  charts/spiderpool/values.yaml
  docs/README.md
  docs/cmdref/spiderpool-controller.md
  docs/cmdref/spiderpoolctl.md
  docs/contributing/development/changelog.md
  docs/contributing/development/daily_build.md
  docs/contributing/development/github_pages.md
  docs/contributing/development/pullrequest.md
  pkg/ippoolmanager/README.md
  pkg/workloadendpointmanager/README.md
Labels: pr/release/none-required

#147 add label check for test file
  .github/.spelling
  Makefile
  docs/contributing/development/pullrequest.md
Labels: pr/release/none-required

#135 spiderpool cmd cli
  cmd/spiderpool-agent/cmd/command_daemon.go
  cmd/spiderpool-agent/cmd/command_root.go
  cmd/spiderpool-agent/cmd/command_shutdown.go
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/http_server.go
  cmd/spiderpool-agent/cmd/runtime_status.go
  cmd/spiderpool-agent/main.go
  cmd/spiderpool-controller/cmd/command_daemon.go
  cmd/spiderpool-controller/cmd/command_root.go
  cmd/spiderpool-controller/cmd/command_shutdown.go
  cmd/spiderpool-controller/cmd/command_status.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-controller/cmd/http_server.go
  cmd/spiderpool-controller/cmd/runtime_status.go
  cmd/spiderpool-controller/main.go
  cmd/spiderpoolctl/cmd/command_gc.go
  cmd/spiderpoolctl/cmd/command_ip.go
  cmd/spiderpoolctl/cmd/command_root.go
  cmd/spiderpoolctl/main.go
  docs/cmdref/spiderpoolctl.md
  go.mod
  go.sum
  pkg/cmdgenmd/cmd_generate_markdown.go
  vendor/github.com/cpuguy83/go-md2man/v2/LICENSE.md
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
  vendor/github.com/russross/blackfriday/v2/.gitignore
  vendor/github.com/russross/blackfriday/v2/.travis.yml
  vendor/github.com/russross/blackfriday/v2/LICENSE.txt
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/entities.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/markdown.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/russross/blackfriday/v2/smartypants.go
  vendor/github.com/spf13/cobra/doc/README.md
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/man_docs.md
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.md
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs.md
  vendor/github.com/spf13/cobra/doc/util.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.md
  vendor/modules.txt
Labels: pr/release/none-required

#149 fix charts
  charts/spiderpool/Chart.yaml
  charts/spiderpool/crds/crd.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  images/spiderpool-agent/Dockerfile
  images/spiderpool-controller/Dockerfile
Labels: pr/release/chart, issue/bug

#156 ci: check go sdk
  .github/workflows/lint-golang.yaml
Labels: pr/release/none-required

#164 fix cli bugs
  cmd/spiderpool-agent/cmd/http_server.go
  cmd/spiderpool-agent/cmd/runtime_status.go
  cmd/spiderpool-controller/cmd/http_server.go
  cmd/spiderpool-controller/cmd/runtime_status.go
Labels: pr/release/none-required

#167 typo
  .github/labels.yml
  README.md
Labels: pr/release/none-required

#168 fix sha for push case
  .github/workflows/build-image-ci.yaml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-license.yaml
  .github/workflows/lint-spell.yaml
Labels: pr/release/none-required

#170 roadmap
  .github/.spelling
  docs/concepts/arch.md
  docs/contributing/development/roadmap.md
Labels: pr/release/doc

#171 workflow, ignore ct --check-version-increment
  .github/workflows/call-lint-chart.yaml
Labels: pr/release/none-required

#172 CI: check tag and VERSION is same
  .github/workflows/auto-release.yaml
  .github/workflows/call-lint-chart.yaml
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required

#178 low coverage target
  codecov.yml
  docs/contributing/development/roadmap.md
Labels: pr/release/none-required

#183 optimize e2e
  .github/workflows/auto-nightly-ci.yaml
Labels: pr/release/none-required

#185 opt workflow
  .github/workflows/lint-golang.yaml
Labels: pr/release/none-required

#177 ipam plugin
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/health.go
  cmd/spiderpool-agent/cmd/http_server.go
  cmd/spiderpool-agent/cmd/ipam.go
  cmd/spiderpool-agent/cmd/runtime_status.go
  cmd/spiderpool-agent/cmd/unix_server.go
  cmd/spiderpool-agent/pkg/README.md
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/pkg/README.md
  cmd/spiderpool/cmd/cmd_suite_test.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
  cmd/spiderpool/cmd/command_test.go
  cmd/spiderpool/main.go
  cmd/spiderpool/pkg/README.md
  cmd/spiderpool/pkg/spiderpool
  cmd/spiderpoolctl/pkg/README.md
  go.mod
  go.sum
  pkg/cnicommon/cni_types.go
  vendor/github.com/containernetworking/cni/LICENSE
  vendor/github.com/containernetworking/cni/pkg/skel/skel.go
  vendor/github.com/containernetworking/cni/pkg/types/020/types.go
  vendor/github.com/containernetworking/cni/pkg/types/040/types.go
  vendor/github.com/containernetworking/cni/pkg/types/100/types.go
  vendor/github.com/containernetworking/cni/pkg/types/args.go
  vendor/github.com/containernetworking/cni/pkg/types/create/create.go
  vendor/github.com/containernetworking/cni/pkg/types/internal/convert.go
  vendor/github.com/containernetworking/cni/pkg/types/internal/create.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/github.com/containernetworking/cni/pkg/utils/utils.go
  vendor/github.com/containernetworking/cni/pkg/version/conf.go
  vendor/github.com/containernetworking/cni/pkg/version/plugin.go
  vendor/github.com/containernetworking/cni/pkg/version/reconcile.go
  vendor/github.com/containernetworking/cni/pkg/version/version.go
  vendor/github.com/containernetworking/plugins/LICENSE
  vendor/github.com/containernetworking/plugins/pkg/ns/README.md
  vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/bad_reader.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/cmd.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/dns.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/netns_linux.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/ping.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/testing.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version4.go
  vendor/modules.txt
Labels: pr/release/none-required

#186 add multus ci smoke
  test/Makefile
  test/Makefile.defs
  test/scripts/install-multus.sh
  test/scripts/prepare.sh
  test/yamls/multus-daemonset-thick-plugin.yml
Labels: pr/release/none-required

#188 check tools
  .github/.spelling
  .gitignore
  Makefile
  docs/contributing/development/test.md
  test/Makefile
  test/Makefile.defs
  test/scripts/cni-install.sh
  test/scripts/install-tools.sh
  test/scripts/prepare.sh
Labels: pr/release/none-required

#189 support run e2e for multiple cluster at same time
  Makefile
  test/Makefile
  test/scripts/install-tools.sh
Labels: pr/release/none-required

#191 optimise e2e
  .gitignore
  Makefile
  test/Makefile
  test/Makefile.defs
  test/scripts/install-macvlan.sh
  test/scripts/install-multus.sh
  test/scripts/install-tools.sh
  test/scripts/install-whereabouts.sh
  test/scripts/prepare.sh
  test/yamls/multus-daemonset-thick-plugin.tmpl
Labels: pr/release/bug
