Repository spidernet-io/spiderpool, pull requests merged in 2022-06, with the labels that each got.

#282 robot update doc from main to branch github_pages
  docs/concepts/allocation/index.html
  docs/concepts/arch/index.html
  docs/concepts/gc/index.html
  docs/concepts/ippool/index.html
  docs/concepts/reservedip/index.html
  docs/concepts/workloadendpoint/index.html
  docs/develop/changelog/index.html
  docs/develop/pullrequest/index.html
  docs/develop/release/index.html
  docs/develop/swagger_openapi/index.html
  docs/develop/test/index.html
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/advance/index.html
  docs/usage/annotation/index.html
  docs/usage/cli/index.html
  docs/usage/config/index.html
  docs/usage/demo/index.html
  docs/usage/metrics/index.html
  docs/usage/qa/index.html
  docs/usage/reservedip/index.html
Labels: pr/release/robot_update_githubpage

#287 ci bug
  .github/workflows/auto-nightly-ci.yaml
  tools/scripts/e2eperformance.sh
Labels: pr/release/none-required

#291 add tls cert to webhook
  .github/.spelling
  .github/codespell-ignorewords
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/call-lint-chart.yaml
  .github/workflows/lint-golang.yaml
  Makefile
  Makefile.defs
  charts/spiderpool/Chart.yaml
  charts/spiderpool/templates/_helpers.tpl
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/templates/service.yaml
  charts/spiderpool/templates/tls.yaml
  charts/spiderpool/templates/webhook-validating.yaml
  charts/spiderpool/templates/webhook.yaml
  charts/spiderpool/values.yaml
  charts/spiderpool/webhook/manifests.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-controller/cmd/command_daemon.go
  cmd/spiderpool-controller/cmd/config.go
  docs/cmdref/spiderpool-agent.md
  docs/cmdref/spiderpool-controller.md
  docs/develop/test.md
  docs/usage/config.md
  docs/usage/demo.md
  test/Makefile
  test/Makefile.defs
  test/scripts/install-cert-manager.sh
  test/scripts/prepare.sh
  test/yamls/10-macvlan.tmpl
  test/yamls/cert-manager.yaml
  tools/cert/generateCert.sh
  tools/k8s-controller-gen/update-controller-gen.sh
Labels: pr/release/none-required

#296 fix CI bug of creating PR
  .github/workflows/auto-clean-image.yaml
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-release.yaml
  .github/workflows/build-image-beta.yaml
  .github/workflows/build-image-release.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
Labels: pr/release/none-required

#302 robot update changelog with tag v0.0.2 to branch github_pages
  changelogs/v0.0.1-to-v0.0.2.md
Labels: pr/release/robot_update_githubpage

#301 robot Update chart from v0.0.2 to branch github_pages
  charts/spiderpool-v0.0.2.tgz
  index.yaml
Labels: pr/release/robot_update_githubpage

#303 ci bug for triggering e2e
  .github/workflows/auto-nightly-ci.yaml
  charts/spiderpool/values.yaml
Labels: pr/release/none-required

#304 e2e: multis add more cni conf
  charts/spiderpool/values.yaml
  test/Makefile
  test/Makefile.defs
  test/e2e/common/daemonset.go
  test/e2e/common/deployment.go
  test/e2e/common/pod.go
  test/e2e/common/replicaset.go
  test/e2e/common/statefulset.go
  test/e2e/performance/ippool_perf_test.go
  test/scripts/install-macvlan.sh
  test/scripts/install-multus.sh
  test/scripts/installTestPod.sh
  test/yamls/10-macvlan.tmpl
  test/yamls/multus-daemonset-thick-plugin.tmpl
Labels: pr/release/none-required

#305 e2e support ipv4, ipv6 and dual-stack
  .github/.spelling
  .github/workflows/auto-nightly-ci.yaml
  README.md
  docs/develop/test.md
  test/Makefile
  test/Makefile.defs
  test/e2e/ippool/statefulset_test.go
  test/scripts/install-multus.sh
  test/scripts/installTestPod.sh
  test/yamls/kind-config.tmpl
  test/yamls/multus-daemonset-thick-plugin.tmpl
Labels: pr/release/none-required

#308 add job e2e test (E00005)
  test/e2e/common/job.go
  test/e2e/ippool/ippool_suite_test.go
  test/e2e/ippool/job_pod_test.go
Labels: pr/release/none-required, pr/ready-review

#316 e2e: add bridge cni for service traffic
  .github/workflows/auto-nightly-ci.yaml
  README.md
  test/Makefile
  test/Makefile.defs
  test/scripts/install-multus.sh
  test/yamls/kind-config.tmpl
  test/yamls/multus-daemonset-thick-plugin.tmpl
Labels: pr/release/none-required

#318 ci: typo
  .github/workflows/call-release-image.yaml
Labels: pr/release/none-required

#314 add case for batch ippool
  test/doc/performance.md
Labels: pr/release/none-required, pr/ready-review

#320 modify job e2e case E00005
  test/e2e/ippool/job_pod_test.go
Labels: pr/release/none-required, pr/ready-review

#323 case G00002 delete same-name pod in different namespace
  go.mod
  go.sum
  test/e2e/performance/performance_test.go
  test/e2e/reclaim/reclaim_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/namespace.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#231 k8s:Add Spiderpool CRD data pkg and IPAM pkg
  .github/.spelling
  api/v1/agent/client/daemonset/post_ipam_ip_responses.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  api/v1/agent/server/restapi/daemonset/post_ipam_ip_responses.go
  charts/spiderpool/crds/spiderpool.spidernet.io_ippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_reservedips.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_workloadendpoints.yaml
  charts/spiderpool/templates/cluster-default-ippool.yaml
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/templates/rbac.yaml
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/templates/role_binding.yaml
  charts/spiderpool/templates/tls.yaml
  charts/spiderpool/templates/webhook.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/crd_manager.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/ipam.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_test.go
  docs/concepts/allocation.md
  docs/usage/annotation.md
  docs/usage/config.md
  pkg/constant/errors.go
  pkg/constant/k8s.go
  pkg/gcmanager/README.md
  pkg/ip/ips.go
  pkg/ipam/ipam.go
  pkg/ipammanager/README.md
  pkg/ippoolmanager/README.md
  pkg/ippoolmanager/ippool_manager.go
  pkg/k8s/apis/v1/ippool_types.go
  pkg/k8s/apis/v1/rbac.go
  pkg/k8s/apis/v1/reservedip_types.go
  pkg/k8s/apis/v1/workloadendpoint_types.go
  pkg/k8s/apis/v1/zz_generated.deepcopy.go
  pkg/metric/README.md
  pkg/namespacemanager/namespace_manager.go
  pkg/nodemanager/node_manager.go
  pkg/nsmanager/README.md
  pkg/podmanager/pod_manager.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/types/k8s.go
  pkg/webhook/ippool_webhook.go
  pkg/workloadendpointmanager/README.md
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/Makefile
  test/Makefile.defs
  test/doc/configmap.md
  test/e2e/performance/performance_test.go
  test/scripts/installTestPod.sh
  tools/k8s-controller-gen/update-controller-gen.sh
Labels: pr/release/none-required, pr/ready-review

#334 e2e: add spiderpool api
  go.mod
  go.sum
  test/e2e/annotation/annotation_suite_test.go
  test/e2e/assignip/assiginip_suite_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/cli/cli_suite_test.go
  test/e2e/common/constant.go
  test/e2e/common/spiderpool.go
  test/e2e/configmap/configmap_suite_test.go
  test/e2e/editcrd/editcrd_suite_test.go
  test/e2e/ippool/ippool_suite_test.go
  test/e2e/ippool/job_pod_test.go
  test/e2e/metric/metric_suite_test.go
  test/e2e/performance/performance_suite_test.go
  test/e2e/reclaim/reclaim_suite_test.go
  test/e2e/reliability/reliability_suite_test.go
  test/e2e/reservedip/reservedip_suite_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/configmap.go
  vendor/github.com/spidernet-io/e2eframework/framework/framework.go
  vendor/modules.txt
Labels: pr/release/none-required

#325 add test case A00003
  go.mod
  go.sum
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/common/constant.go
  test/e2e/common/pod.go
  vendor/github.com/spidernet-io/e2eframework/framework/configmap.go
  vendor/github.com/spidernet-io/e2eframework/framework/events.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#336 add GetNamespaceDefaultIppool api
  test/e2e/common/spiderpool.go
Labels: pr/release/none-required, pr/ready-review

#339 add api create/delete ippool for spiderpool
  test/e2e/common/spiderpool.go
Labels: pr/release/none-required, pr/ready-review

#337 hide cobra CLI completion command
  cmd/spiderpool-agent/cmd/command_root.go
  cmd/spiderpool-controller/cmd/command_root.go
  cmd/spiderpoolctl/cmd/command_root.go
Labels: pr/release/none-required, pr/ready-review

#338 ipam:Add code to release IP
  api/v1/agent/models/ip_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/crds/spiderpool.spidernet.io_ippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_workloadendpoints.yaml
  cmd/spiderpool-agent/cmd/crd_manager.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/ipam.go
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/k8s/apis/v1/ippool_types.go
  pkg/k8s/apis/v1/workloadendpoint_types.go
  pkg/k8s/apis/v1/zz_generated.deepcopy.go
  pkg/logutils/log.go
  pkg/logutils/log_test.go
  pkg/namespacemanager/namespace_manager.go
  pkg/nodemanager/node_manager.go
  pkg/podmanager/pod_manager.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/e2e/performance/performance_test.go
Labels: pr/release/none-required, pr/ready-review

#346 fix:Failed to rollback IP when serializing Pod IP allocation annotations
  pkg/ipam/ipam.go
  pkg/types/k8s.go
Labels: pr/release/none-required, pr/ready-review

#344 add test case A00001 for spiderpool
  go.mod
  go.sum
  test/e2e/annotation/annotation_test.go
  test/e2e/common/constant.go
  test/e2e/common/spiderpool.go
  test/e2e/common/tools.go
  test/e2e/performance/performance_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/deployment.go
  vendor/github.com/spidernet-io/e2eframework/framework/node.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#349 Update Spiderpool-controller env args
  charts/spiderpool/Chart.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/deployment.yaml
  cmd/spiderpool-agent/cmd/command_daemon.go
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-controller/cmd/command_daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/http_server.go
Labels: pr/release/none-required, pr/ready-review

#347 doc:Add doc annotation.md
  .github/.spelling
  docs/usage/annotation.md
Labels: pr/release/none-required, pr/ready-review

#350 doc:Add doc config.md
  .github/.spelling
  docs/usage/config.md
Labels: pr/release/none-required, pr/ready-review

#354 update webui theme
  docs/mkdocs.yml
Labels: pr/release/none-required

#335 E2E: add case A00005 for spiderpool
  test/e2e/annotation/annotation_test.go
Labels: pr/release/none-required, pr/ready-review

#355 e2e: add flamegraph
  .github/.spelling
  .github/workflows/auto-nightly-ci.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/utils.go
  docs/cmdref/spiderpool-agent.md
  docs/cmdref/spiderpool-controller.md
  docs/develop/test.md
  docs/usage/config.md
  go.mod
  go.sum
  pkg/logutils/log.go
  test/Makefile
  test/Makefile.defs
  test/yamls/cert-manager.yaml
  vendor/github.com/google/gops/LICENSE
  vendor/github.com/google/gops/agent/agent.go
  vendor/github.com/google/gops/agent/sockopt_reuseport.go
  vendor/github.com/google/gops/agent/sockopt_unsupported.go
  vendor/github.com/google/gops/internal/internal.go
  vendor/github.com/google/gops/internal/internal_go1_13.go
  vendor/github.com/google/gops/internal/internal_lt_go1_13.go
  vendor/github.com/google/gops/signal/signal.go
  vendor/github.com/pyroscope-io/client/LICENSE
  vendor/github.com/pyroscope-io/client/internal/flameql/error.go
  vendor/github.com/pyroscope-io/client/internal/flameql/flameql.go
  vendor/github.com/pyroscope-io/client/internal/flameql/key.go
  vendor/github.com/pyroscope-io/client/internal/flameql/parse.go
  vendor/github.com/pyroscope-io/client/internal/sortedmap/sortedmap.go
  vendor/github.com/pyroscope-io/client/pyroscope/api.go
  vendor/github.com/pyroscope-io/client/pyroscope/logger.go
  vendor/github.com/pyroscope-io/client/pyroscope/remote.go
  vendor/github.com/pyroscope-io/client/pyroscope/session.go
  vendor/github.com/pyroscope-io/client/pyroscope/types.go
  vendor/modules.txt
Labels: pr/release/none-required

#361 docs:Add docs select-ippool.md
  docs/usage/annotation.md
  docs/usage/config.md
  docs/usage/select-ippool.md
Labels: pr/release/none-required, pr/ready-review

#341 E2E: E00015 fail to run a pod when IP resource of an ippool is exhausted
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/common/constant.go
  test/e2e/common/spiderpool.go
  test/e2e/common/tools.go
Labels: pr/release/none-required, pr/ready-review

#372 ci: seperate e2e ci
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/call-ci.yaml
Labels: pr/release/none-required

#365 fix:Typo namespaceSelector
  charts/spiderpool/crds/spiderpool.spidernet.io_ippools.yaml
  pkg/k8s/apis/v1/ippool_types.go
Labels: pr/release/none-required, pr/ready-review

#373 ci: seperate e2e ci
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/call-ci.yaml
Labels: pr/release/none-required

#374 ci: seperate e2e ci
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/call-ci.yaml
Labels: pr/release/none-required

#371 add execCommand
  test/e2e/common/tools.go
  vendor/github.com/onsi/gomega/gbytes/buffer.go
  vendor/github.com/onsi/gomega/gbytes/io_wrappers.go
  vendor/github.com/onsi/gomega/gbytes/say_matcher.go
  vendor/github.com/onsi/gomega/gexec/build.go
  vendor/github.com/onsi/gomega/gexec/exit_matcher.go
  vendor/github.com/onsi/gomega/gexec/prefixed_writer.go
  vendor/github.com/onsi/gomega/gexec/session.go
  vendor/modules.txt
Labels: pr/release/none-required

#366 E2E: case D00001 it fails to append an ip that already exists in another …
  test/e2e/editcrd/editcrd_test.go
Labels: pr/release/none-required

#343 E2E: add test cases according to the documentation
  test/doc/annotation.md
  test/doc/configmap.md
  test/doc/editcrd.md
Labels: pr/release/none-required, pr/ready-review

#377 E2E add R00001/R00004 reliability about spiderpool component
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required, pr/ready-review

#289 add multiple cni version support
  cmd/spiderpool/cmd/cni_types.go
  cmd/spiderpool/cmd/command_test.go
  cmd/spiderpool/main.go
Labels: pr/release/none-required, pr/ready-review

#375 E2E: add smoke test case A00006 for namespace annotations
  test/e2e/annotation/annotation_test.go
Labels: pr/release/none-required, pr/ready-review

#382 ipam:Add default IP pools at CNI network configuration level
  api/README.md
  api/v1/agent/models/ipam_add_args.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool/cmd/cni_types.go
  cmd/spiderpool/cmd/command_add.go
  pkg/ipam/ipam.go
  test/scripts/install-multus.sh
Labels: pr/release/none-required, pr/ready-review

#381 add multiple CNI version support unit test
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_test.go
Labels: pr/release/none-required, pr/ready-review

#383 version v0.0.4
  .github/workflows/auto-pr-ci.yaml
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required

#388 ci: print log
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  .gitignore
  Makefile
  charts/spiderpool/values.yaml
  docs/develop/test.md
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  test/Makefile
  test/Makefile.defs
  test/scripts/debugEnv.sh
Labels: pr/release/none-required

#390 E2E: fix api CheckPodListIpReady
  go.mod
  go.sum
  test/e2e/common/pod.go
  test/e2e/ippool/job_pod_test.go
  test/e2e/reclaim/reclaim_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/deployment.go
  vendor/github.com/spidernet-io/e2eframework/framework/node.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/github.com/spidernet-io/e2eframework/tools/tools.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#379 E2E:ippool ip limit for test case P00002
  test/e2e/common/spiderpool.go
  test/e2e/performance/performance_test.go
Labels: pr/release/none-required, pr/ready-review

#389 fix:Failed to correctly filter IP pool
  pkg/ipam/ipam.go
Labels: pr/release/none-required, pr/ready-review

#391 improve ip gc
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
Labels: pr/release/none-required, pr/ready-review

#392 E2E: fix bug of DeletePodListUntilReady
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  Makefile
  go.mod
  go.sum
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  test/e2e/performance/performance_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/modules.txt
Labels: pr/release/none-required

#396 robot Update chart from v0.0.4 to branch github_pages
  charts/spiderpool-v0.0.4.tgz
  index.yaml
Labels: pr/release/robot_update_githubpage

#395 robot update changelog with tag v0.0.4 to branch github_pages
  changelogs/v0.0.3-to-v0.0.4.md
Labels: pr/release/robot_update_githubpage
