Repository spidernet-io/spiderpool, pull requests merged in 2022-11, with the labels that each got.

#972 fix:add e2e coverage
  .github/workflows/status.yaml
  tools/scripts/e2ecover.sh
Labels: pr/release/none-required, pr/ready-review

#981 ci: debug error
  .github/workflows/auto-nightly-ci.yaml
  test/Makefile
  test/scripts/debugEnv.sh
Labels: pr/release/none-required

#982 fix IPPool scale up but subnet no more IPs issue
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/bug, pr/ready-review

#991 improve election log
  pkg/election/lease_election.go
Labels: pr/release/none-required, pr/ready-review

#983 improve IP GC log
  pkg/gcmanager/scanAll_IPPool.go
Labels: pr/release/none-required, pr/ready-review

#988 fix:the subnet function is switched off and e2e cannot be run.
  docs/develop/test.md
  test/Makefile
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assignip_test.go
Labels: pr/release/none-required, pr/ready-review

#985 debug:Panic happens occasionally at func allocateIPFromPoolCandidates(...)
  pkg/ipam/ipam.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/none-required, pr/ready-review

#986 update spider subnet markdown
  .github/.spelling
  docs/concepts/annotation.md
  docs/concepts/spidersubnet.md
  docs/example/spider-subnet/deploy-use-subnet.yaml
  docs/example/spider-subnet/subnet-demo.yaml
  docs/usage/spider-subnet.md
Labels: pr/release/doc, pr/ready-review

#989 remove workqueue discarding object incase that the event is lost
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/config.go
  pkg/ippoolmanager/ippool_informer.go
Labels: pr/release/bug, pr/ready-review

#992 fix cni configuration file example
  .github/.spelling
  docs/concepts/config.md
Labels: pr/release/none-required, pr/ready-review

#994 v0.3.1
  .github/.spelling
  VERSION
  charts/spiderpool/Chart.yaml
  docs/develop/release.md
Labels: pr/release/none-required

#996 robot update changelog with tag v0.3.1 to branch github_pages
  changelogs/v0.3.0-to-v0.3.1.md
Labels: pr/release/robot_update_githubpage

#995 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.3.1.tgz
  docs/concepts/annotation/index.html
  docs/concepts/config/index.html
  docs/concepts/spidersubnet/index.html
  docs/develop/release/index.html
  docs/develop/test/index.html
  docs/example/spider-subnet/deploy-use-subnet.yaml
  docs/example/spider-subnet/subnet-demo.yaml
  docs/index.yaml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/spider-subnet/index.html
Labels: pr/release/robot_update_githubpage

#997 update readme doc
  charts/spiderpool/README.md
  docs/usage/basic.md
Labels: pr/release/doc

#998 improve spiderpool controller ippool informer log
  pkg/ippoolmanager/ippool_informer.go
Labels: pr/release/none-required, pr/ready-review

#999 fix panic in AllocateIP() api when allocate IP for pod
  pkg/constant/errors.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/podmanager/pod_manager.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
  test/scripts/debugEnv.sh
Labels: pr/release/bug

#1001 fix:Invalid validation of `spec.ips` and `spec.excludeIPs` fields of SpiderSubnet
  pkg/ippoolmanager/ippool_validate.go
  pkg/subnetmanager/subnet_validate.go
Labels: pr/release/bug, pr/ready-review, kind/bug

#1000 fix:Panic happens occasionally at func allocateIPFromPoolCandidates
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_manager.go
Labels: pr/release/none-required, pr/ready-review, kind/bug

#1005 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.3.2.tgz
  docs/index.yaml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/basic/index.html
Labels: pr/release/robot_update_githubpage

#1004 robot update changelog with tag v0.3.2 to branch github_pages
  changelogs/v0.3.1-to-v0.3.2.md
Labels: pr/release/robot_update_githubpage

#1015 fix: ctx is not used
  test/e2e/common/spidersubnet.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1017 fix: api added ip conflict
  test/e2e/common/spidersubnet.go
Labels: pr/release/none-required, pr/ready-review

#1007 Add format verification to route annotation of Pod
  pkg/ip/errors.go
  pkg/ip/route.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/none-required, pr/ready-review

#1019 Refactor SpiderSubnet controller
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/utils.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/none-required, pr/ready-review

#1021 add ipam pool candidate validation for subnet
  pkg/ipam/ipam.go
Labels: pr/release/bug, pr/ready-review, kind/bug

#1013 separate controller to v4/v6 to accelerate auto-ippool event
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/config.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/types/interface.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/reservedipmanager/utils.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/feature-new, pr/ready-review

#1033 fix subnet cursor data race
  pkg/ippoolmanager/ippool_informer.go
Labels: pr/release/none-required, pr/ready-review, kind/bug

#1035 fix statefulset ip allocation retrieve
  pkg/ipam/ipam.go
Labels: pr/release/none-required, pr/ready-review, kind/bug

#1038 fix:Panic happens occasionally when setting the label of the owner SpiderSubnet to which the SpiderIPPool belongs
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/none-required, pr/ready-review, kind/bug

#1032 Remove the verification of the array length of the field `spec.ips` of SpiderReservedIP
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderreservedips.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderreservedip_types.go
  pkg/reservedipmanager/reservedip_validate.go
Labels: pr/release/none-required, pr/ready-review

#1049 fix:Spiderpool controller lacks permission to patch Event
  charts/spiderpool/templates/role.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v1/rbac.go
Labels: pr/release/none-required, pr/ready-review, kind/bug

#1047 fix:When deleting a SpiderSubnet, its finalizer cannot be removed correctly
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/none-required, pr/ready-review, kind/bug

#1042 E2E: update ginkgo function
  test/Makefile
Labels: pr/release/none-required, pr/ready-review

#1039 fix: add gc all intervals to the env
  .github/.spelling
  charts/spiderpool/README.md
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  docs/cmdref/spiderpool-controller.md
  test/Makefile
  test/e2e/common/constant.go
Labels: pr/release/none-required, pr/ready-review

#1054 docs: Update install.md and basic.md
  docs/example/basic/custom-ippool-deploy.yaml
  docs/usage/basic.md
Labels: pr/release/doc, pr/not-ready

#1041 E2E: Automatic creation, extension and deletion of ippool by different controllers
  test/e2e/common/constant.go
  test/e2e/common/replicaset.go
  test/e2e/common/statefulset.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1058 add logutils unit test
  pkg/logutils/log_test.go
Labels: pr/release/none-required, pr/ready-review

#1059 docs: Update reserved-ip.md
  docs/example/reserved-ip/reservedip-deploy.yaml
  docs/usage/reserved-ip.md
Labels: pr/release/none-required, pr/ready-review

#1063 E2E: add test case related to subnet.spec field validation
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/not-ready

#1050 fix: add a retry mechanism for api
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/common/spiderpool.go
  test/e2e/common/tools.go
Labels: pr/release/none-required, pr/ready-review

#1009 add metircs for spider subnet
  .github/.spelling
  charts/spiderpool/README.md
  charts/spiderpool/templates/_helpers.tpl
  charts/spiderpool/templates/prometheusrule.yaml
  charts/spiderpool/templates/servicemonitor.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/ipam.go
  cmd/spiderpool-agent/cmd/metrics_server.go
  cmd/spiderpool-controller/cmd/metrics_server.go
  go.mod
  pkg/metric/README.md
  pkg/metric/metrics.go
  pkg/metric/metrics_instance.go
  pkg/metric/metrics_ipam.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/feature-new, pr/ready-review

#1073 docs: Update usage documents
  docs/example/ippool-affinity-node/master-ipv4-ippool.yaml
  docs/example/ippool-affinity-node/node-affinity-deploy.yaml
  docs/example/ippool-affinity-node/worker-ipv4-ippool.yaml
  docs/example/ippool-multi/dummy-pod.yaml
  docs/example/ippool-multi/multi-ippool-deploy.yaml
  docs/example/ippool-namespace/ns1-ippool-selection-patch.yaml
  docs/usage/ippool-affinity-node.md
  docs/usage/ippool-multi.md
  docs/usage/ippool-namespace.md
  docs/usage/reserved-ip.md
Labels: pr/release/none-required, pr/ready-review

#1061 fix: Avoid getting an empty pod list
  test/Makefile
  test/e2e/assignip/assignip_test.go
  test/e2e/common/deployment.go
  test/e2e/common/replicaset.go
  test/e2e/common/statefulset.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1057 docs: Pretty print install.md
  .github/.spelling
  docs/example/basic/custom-ippool-deploy.yaml
  docs/usage/basic.md
  docs/usage/install.md
Labels: pr/release/doc, pr/ready-review

#1068 fix ipool workequeue panic
  pkg/ippoolmanager/ippool_informer.go
Labels: pr/release/bug, pr/ready-review, kind/bug

#1046 improve statefulset ipam cmd delete
  pkg/ipam/ipam.go
Labels: pr/release/bug, pr/ready-review

#1055 make create or mark IPPool asynchronized
  pkg/ippoolmanager/ippool_manager.go
  pkg/subnetmanager/subnet_controller.go
Labels: pr/release/none-required, pr/not-ready

#1069 E2E: Improve some api
  test/e2e/common/deployment.go
  test/e2e/common/spidersubnet.go
Labels: pr/release/none-required, pr/not-ready

#1085 fix prometheus rules charts
  charts/spiderpool/README.md
  charts/spiderpool/templates/prometheusrule.yaml
  charts/spiderpool/values.yaml
Labels: pr/release/none-required, pr/ready-review, kind/bug

#1092 fix subnet create ippool asynchronous multile ippools issue
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  go.mod
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/controllers/cronjob_informer.go
  pkg/subnetmanager/controllers/daemonset_informer.go
  pkg/subnetmanager/controllers/deployment_informer.go
  pkg/subnetmanager/controllers/job_informer.go
  pkg/subnetmanager/controllers/replicaset_informer.go
  pkg/subnetmanager/controllers/statefulset_informer.go
  pkg/subnetmanager/controllers/utils.go
  pkg/subnetmanager/subnet_controller.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/none-required, kind/bug

#1094 docs: Add doc multi-interfaces-annotation.md
  .github/.spelling
  docs/example/multi-interfaces-annotation/00-multus.conf
  docs/example/multi-interfaces-annotation/different-segment-ipv4-ippools.yaml
  docs/example/multi-interfaces-annotation/macvlan-cni-default.yaml
  docs/example/multi-interfaces-annotation/multi-macvlan-interfaces-deploy.yaml
  docs/usage/basic.md
  docs/usage/cli.md
  docs/usage/debug.md
  docs/usage/install.md
  docs/usage/multi-interfaces-annotation.md
  docs/usage/reserved-ip.md
Labels: pr/release/doc, pr/ready-review

#1086 docs: Add doc ippool-affinity-namespace.md
  docs/example/ippool-affnity-namespace/different-ns-deploys.yaml
  docs/example/ippool-affnity-namespace/test-ns-ipv4-ippool.yaml
  docs/usage/ippool-affinity-namespace.md
  docs/usage/ippool-affinity-node.md
Labels: pr/release/doc, pr/ready-review

#1090 docs: Add doc ippool-affinity-pod.md
  .github/.spelling
  docs/example/ippool-affinity-pod/static-ippool-deploy.yaml
  docs/example/ippool-affinity-pod/static-ipv4-ippool.yaml
  docs/example/ippool-affinity-pod/wrong-static-ippool-deploy.yaml
  docs/usage/ippool-affinity-pod.md
  docs/usage/ippool-namespace.md
  docs/usage/reserved-ip.md
Labels: pr/release/doc, pr/ready-review

#1091 E2E: add case create deploys with the same name
  test/doc/annotation.md
  test/doc/assignip.md
  test/doc/cidr.md
  test/doc/configmap.md
  test/doc/ippoolcr.md
  test/e2e/common/constant.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review, pr/not-ready

#1103 improve subnet controller performance
  cmd/spiderpool-controller/cmd/config.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/subnetmanager/subnet_controller.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/none-required, pr/ready-review, kind/bug

#1108 v0.3.3
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required

#1110 robot update changelog with tag v0.3.3 to branch github_pages
  changelogs/v0.3.2-to-v0.3.3.md
Labels: pr/release/robot_update_githubpage

#1105 unittest: add unittest
  pkg/namespacemanager/namespace_manager_test.go
  pkg/namespacemanager/namespacemanager_suite_test.go
  pkg/nodemanager/node_manager_test.go
  pkg/nodemanager/nodemanager_suite_test.go
  pkg/podmanager/pod_manager_test.go
  pkg/podmanager/podmanager_suite_test.go
Labels: pr/release/none-required, pr/ready-review, pr/not-ready

#1111 fix: resources not released
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1113 fix:Docker automatic ARG `TARGETARCH` is missing
  images/spiderpool-agent/Dockerfile
  images/spiderpool-controller/Dockerfile
Labels: pr/release/bug, pr/ready-review

#1115 robot update changelog with tag v0.3.4 to branch github_pages
  changelogs/v0.3.3-to-v0.3.4.md
Labels: pr/release/robot_update_githubpage

#1117 fix: The architecture of base image mismatch
  images/spiderpool-agent/Dockerfile
  images/spiderpool-controller/Dockerfile
Labels: pr/release/bug, pr/ready-review

#1118 Bump Spiderpool version to v0.3.5
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#1120 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.3.5.tgz
  docs/index.yaml
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#1119 robot update changelog with tag v0.3.5 to branch github_pages
  changelogs/v0.3.4-to-v0.3.5.md
Labels: pr/release/robot_update_githubpage

#1123 ci: cherry pick
  .github/workflows/auto-cherrypick.yaml
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-update-githubpages.yaml
Labels: pr/release/none-required
