Repository spidernet-io/spiderpool, pull requests merged in 2022-09, with the labels that each got.

#676 typo
  .github/.spelling
  charts/spiderpool/templates/role.yaml
  cmd/spiderpool-init/main.go
Labels: pr/release/none-required

#675 fix:Failed to correctly judge whether the subnets of the two IP pools overlap each other
  pkg/ip/ips.go
Labels: pr/release/bug, pr/ready-review

#673 docs:Update docs ippool-affinity-node.md
  .github/.spelling
  docs/example/ippool-affinity-node/master-ipv4-ippool.yaml
  docs/example/ippool-affinity-node/node-affinity-deploy.yaml
  docs/example/ippool-affinity-node/worker-ipv4-ippool.yaml
  docs/example/ippool-multi/multi-ippool-deploy.yaml
  docs/example/ippool-multi/test-ipv4-ippools.yaml
  docs/example/ippool-namespace/ns1-default-ipv4-ippool.yaml
  docs/example/reserved-ip/already-in-use-ippool.yaml
  docs/example/reserved-ip/created-by-someone-else-ippool.yaml
  docs/example/reserved-ip/not-use-excludeips-ippool.yaml
  docs/example/reserved-ip/reservedip-deploy.yaml
  docs/example/reserved-ip/test-ipv4-ippool.yaml
  docs/example/reserved-ip/test-ipv4-reservedip.yaml
  docs/example/reserved-ip/use-excludeips-ippool.yaml
  docs/usage/ippool-affinity-node.md
  docs/usage/ippool-multi.md
  docs/usage/ippool-namespace.md
  docs/usage/reserved-ip.md
Labels: pr/release/none-required, pr/ready-review

#669 improve ipam plugin log
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
Labels: pr/release/none-required, pr/ready-review

#678 spider-init: install default ippool
  charts/spiderpool/README.md
  charts/spiderpool/templates/cluster-default-ippool.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/k8s.go
  cmd/spiderpool-init/cmd/root.go
  cmd/spiderpool-init/main.go
  docs/usage/install.md
  pkg/k8s/apis/spiderpool.spidernet.io/v1/rbac.go
  test/scripts/debugEnv.sh
Labels: pr/release/feature-new

#679 spiderpool-init: wait for helm --wait
  cmd/spiderpool-init/cmd/root.go
  test/Makefile
Labels: pr/release/none-required

#680 v0.1.2
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required

#682 robot update changelog with tag v0.1.2 to branch github_pages
  changelogs/v0.1.1-to-v0.1.2.md
Labels: pr/release/robot_update_githubpage

#681 robot update chart and website from to branch github_pages
  docs/404.html
  docs/charts/spiderpool-v0.1.2.tgz
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/ippool/index.html
  docs/concepts/metrics/index.html
  docs/concepts/roadmap/index.html
  docs/concepts/spiderendpoint/index.html
  docs/concepts/spiderippool/index.html
  docs/concepts/spiderreservedip/index.html
  docs/develop/changelog/index.html
  docs/develop/pullrequest/index.html
  docs/develop/release/index.html
  docs/develop/swagger_openapi/index.html
  docs/develop/test/index.html
  docs/example/ippool-affinity-node/master-ipv4-ippool.yaml
  docs/example/ippool-affinity-node/node-affinity-deploy.yaml
  docs/example/ippool-affinity-node/worker-ipv4-ippool.yaml
  docs/example/ippool-multi/dummy-pod.yaml
  docs/example/ippool-multi/multi-ippool-deploy.yaml
  docs/example/ippool-multi/test-ipv4-ippools.yaml
  docs/example/ippool-namespace/ns1-default-ippool-deploy.yaml
  docs/example/ippool-namespace/ns1-default-ipv4-ippool.yaml
  docs/example/ippool-namespace/ns1-ippool-selection-patch.yaml
  docs/example/reserved-ip/already-in-use-ippool.yaml
  docs/example/reserved-ip/created-by-someone-else-ippool.yaml
  docs/example/reserved-ip/not-use-excludeips-ippool.yaml
  docs/example/reserved-ip/reservedip-deploy.yaml
  docs/example/reserved-ip/test-ipv4-ippool.yaml
  docs/example/reserved-ip/test-ipv4-reservedip.yaml
  docs/example/reserved-ip/use-excludeips-ippool.yaml
  docs/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/basic/index.html
  docs/usage/cidrManager/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namespace/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/multi-interfaces-cni/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/statefulset/index.html
Labels: pr/release/robot_update_githubpage

#636 E2E: Code reduction and todo modification
  test/doc/affinity.md
  test/doc/annotation.md
  test/doc/ippoolcr.md
  test/doc/labelselector.md
  test/doc/reclaim.md
  test/doc/reliability.md
  test/doc/reservedip.md
  test/e2e/affinity/affinity_suite_test.go
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/common/deployment.go
  test/e2e/common/pod.go
  test/e2e/ippool/ippool_suite_test.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/performance/performance_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_suite_test.go
  test/e2e/reliability/reliability_test.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required, pr/ready-review

#685 ci: do not run time-cost test if possible
  .github/workflows/auto-pr-ci.yaml
  test/e2e/performance/performance_test.go
Labels: pr/release/none-required

#672 add spiderpool metrics markdown
  .github/.spelling
  docs/concepts/metrics.md
  docs/usage/statefulset.md
  pkg/metric/README.md
  pkg/metric/metrics_instance.go
Labels: pr/release/none-required, pr/ready-review

#686 Use `trap` to recycle temporary directories and files in code generation scripts
  tools/k8s-controller-gen/update-controller-gen.sh
  tools/scripts/update-codegen.sh
Labels: pr/release/none-required, pr/ready-review

#688 Add CRD SpiderSubnet
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/zz_generated.deepcopy.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v1/fake/fake_spiderpool.spidernet.io_client.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v1/fake/fake_spidersubnet.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v1/generated_expansion.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v1/spiderpool.spidernet.io_client.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v1/spidersubnet.go
  pkg/k8s/client/informers/externalversions/generic.go
  pkg/k8s/client/informers/externalversions/spiderpool.spidernet.io/v1/interface.go
  pkg/k8s/client/informers/externalversions/spiderpool.spidernet.io/v1/spidersubnet.go
  pkg/k8s/client/listers/spiderpool.spidernet.io/v1/expansion_generated.go
  pkg/k8s/client/listers/spiderpool.spidernet.io/v1/spidersubnet.go
Labels: pr/release/none-required, pr/ready-review

#674 fix issue 670, Spelling error, should not be NamesapceAffinity but NamespaceAffinity
  .github/.spelling
  pkg/ippoolmanager/ippool_manager.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/zz_generated.deepcopy.go
  test/e2e/affinity/affinity_test.go
Labels: pr/release/none-required, pr/ready-review

#696 Add function to convert []net.IP to IP ranges
  pkg/ip/cidr.go
  pkg/ip/errors.go
  pkg/ip/ip.go
  pkg/ip/iprange.go
  pkg/ip/ips.go
Labels: pr/release/none-required, pr/ready-review

#701 chart logo
  charts/spiderpool/Chart.yaml
Labels: pr/release/chart

#703 fix: failed to install default ippool
  charts/spiderpool/templates/pod.yaml
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/k8s.go
  cmd/spiderpool-init/cmd/root.go
Labels: pr/release/none-required

#702 Add comments to pkg ip
  pkg/ip/cidr.go
  pkg/ip/ip.go
  pkg/ip/iprange.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/reservedipmanager/reservedip_manager.go
Labels: pr/release/none-required, pr/ready-review

#687 Add CRD String method
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
Labels: pr/release/none-required, pr/ready-review

#689 explain SpiderIPPool and SpiderEndpoint lifecycle
  docs/concepts/gc.md
Labels: pr/release/none-required, pr/ready-review

#708 robot update changelog with tag v0.1.3 to branch github_pages
  changelogs/v0.1.2-to-v0.1.3.md
Labels: pr/release/robot_update_githubpage

#691 E2E:add case L00009 one IPPool can be used by multiple namespace
  test/e2e/affinity/affinity_test.go
  test/e2e/common/deployment.go
  test/e2e/common/namesapce.go
Labels: pr/release/none-required, pr/ready-review

#692 E2E: Improved e2e code
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/common/deployment.go
  test/e2e/common/namesapce.go
  test/e2e/common/namespace.go
  test/e2e/common/spiderpool.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/performance/performance_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required, pr/ready-review

#716 fix pool selection bug and add comments
  pkg/ipam/ipam.go
  pkg/ipam/tools.go
Labels: pr/release/none-required, pr/ready-review

#714 improve crd types string method
  pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
Labels: pr/release/none-required, pr/ready-review

#719 fix issue 718
  test/e2e/affinity/affinity_test.go
Labels: pr/release/none-required

#715 rename chart version
  .github/workflows/call-lint-chart.yaml
  Makefile
  charts/Makefile
  charts/spiderpool/Chart.yaml
  charts/spiderpool/templates/_helpers.tpl
Labels: pr/release/chart

#721 v0.1.4
  VERSION
  charts/Makefile
  charts/spiderpool/Chart.yaml
Labels: pr/release/chart

#710 Refactor ipam.go
  pkg/gcmanager/pod_cache.go
  pkg/ipam/ipam.go
  pkg/ipam/ipam_statefulset.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/utils.go
  pkg/podmanager/pod_manager.go
  pkg/podmanager/utils.go
  pkg/workloadendpointmanager/utils.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/none-required, pr/ready-review

#727 Updated e2e docs for Wei.Yang
  .github/.spelling
  test/doc/annotation.md
  test/doc/assignip.md
  test/doc/cidr.md
  test/doc/ippoolcr.md
  test/doc/reservedip.md
Labels: pr/release/none-required

#734 print stack when recover occurs
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
Labels: pr/release/none-required, pr/ready-review

#744 fix:The gateway in CIDR format passed the validating webhook by mistake
  cmd/spiderpool/cmd/command_add.go
  pkg/ip/cidr.go
  pkg/ip/ip.go
  pkg/ipam/convert.go
  pkg/ippoolmanager/utils.go
Labels: pr/release/bug, pr/ready-review

#737 Add 'OwnerControllerName' field in SpiderIPPool and SpiderEndpoint
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  pkg/gcmanager/pod_cache.go
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderendpoint_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
  pkg/podmanager/utils.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/none-required, pr/ready-review

#735 readme doc fix
  README.md
  docs/usage/install.md
Labels: pr/release/doc

#729 fix issue 720 :improve CheckPodIpRecordInIppool
  test/e2e/common/spiderpool.go
Labels: pr/release/none-required, pr/not-ready

#738 improve recover log stack
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
Labels: pr/release/none-required, pr/ready-review

#717 E2E: Supplement to S00002, IPs removed from IPPool.Spec.excludeIPs can be assigned to Pods.
  test/e2e/assignip/assignip_test.go
Labels: pr/release/none-required, pr/ready-review

#728 feat:Add webhook of SpiderSubnet
  .github/.spelling
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/templates/webhook.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/constant/k8s.go
  pkg/ip/cidr.go
  pkg/ip/ip.go
  pkg/ip/iprange.go
  pkg/ip/utils.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/ippoolmanager/utils.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/rbac.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/reservedipmanager/reservedip_webhook.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook.go
Labels: pr/release/feature-new, pr/ready-review

#750 installation: init subnet
  charts/spiderpool/README.md
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/k8s.go
  cmd/spiderpool-init/cmd/root.go
  test/Makefile
  test/Makefile.defs
Labels: pr/release/feature-new

#683 E2E: add test case L00008 && A00009 for spiderpool
  test/e2e/affinity/affinity_test.go
  test/e2e/common/spiderpool.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  test/e2e/reservedip/reservedip_suite_test.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required, pr/ready-review

#751 fix:Compare the pointer of 'spec.ipVersion' field in webhook
  pkg/ippoolmanager/ippool_validate.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/subnetmanager/subnet_validate.go
Labels: pr/release/none-required, pr/ready-review

#755 Refactor configuration related code
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/unix_server.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/config/config.go
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/ipam/config.go
  pkg/ipam/convert.go
  pkg/ipam/ipam.go
  pkg/ippoolmanager/config.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/types/interface.go
  pkg/limiter/config.go
  pkg/limiter/queue.go
  pkg/limiter/queue_test.go
  pkg/namespacemanager/namespace_manager.go
  pkg/nodemanager/node_manager.go
  pkg/podmanager/config.go
  pkg/podmanager/pod_manager.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
  pkg/types/types.go
  pkg/workloadendpointmanager/config.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/none-required, pr/ready-review

#766 E2E：Add case on CIDR IP leakage
  test/doc/cidr.md
Labels: pr/release/none-required, pr/ready-review

#748 Pending case R00005
  test/doc/affinity.md
  test/doc/reclaim.md
  test/doc/reliability.md
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required, pr/ready-review

#754 fix: Add update Ippool case to smoke, override PR CI check
  test/doc/ippoolcr.md
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: pr/release/none-required, pr/ready-review

#732 fix issue 713: `UpdatePool` Api method revised to patch
  go.mod
  go.sum
  test/e2e/affinity/affinity_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/common/spiderpool.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/reservedip/reservedip_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/framework.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#765 Add SpiderSubnet related verification in SpiderIPPool Webhook
  pkg/ip/ip.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/none-required, pr/ready-review

#774 wrong service in certificates
  charts/spiderpool/README.md
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  docs/usage/install.md
  pkg/cert/gen.go
  test/Makefile
  test/Makefile.defs
Labels: pr/release/bug

#776 update workflow
  .github/workflows/call-lint-chart.yaml
Labels: pr/release/none-required

#771 feat:Add the informer of SpiderSubnet
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/feature-new, pr/ready-review

#756 E2E：add test case A00011
  test/doc/affinity.md
  test/doc/annotation.md
  test/doc/assignip.md
  test/doc/cidr.md
  test/doc/ippoolcr.md
  test/doc/reservedip.md
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/common/constant.go
  test/e2e/common/deployment.go
  test/e2e/common/pod.go
  test/e2e/common/spiderpool.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/performance/performance_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required, pr/ready-review

#778 fix:FreeIPs of newly created SpiderSubnet cannot be synchronized automatically
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/bug, pr/ready-review

#780 v0.2.0
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required

#782 robot update chart and website from to branch github_pages
  docs/404.html
  docs/assets/javascripts/bundle.37e9125f.min.js
  docs/assets/javascripts/bundle.37e9125f.min.js.map
  docs/assets/javascripts/bundle.48f2be22.min.js
  docs/assets/javascripts/bundle.48f2be22.min.js.map
  docs/assets/javascripts/workers/search.5bf1dace.min.js
  docs/assets/javascripts/workers/search.5bf1dace.min.js.map
  docs/assets/stylesheets/main.2e8b5541.min.css
  docs/assets/stylesheets/main.2e8b5541.min.css.map
  docs/assets/stylesheets/main.7a952b86.min.css
  docs/assets/stylesheets/main.7a952b86.min.css.map
  docs/charts/spiderpool-0.2.0.tgz
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/metrics/index.html
  docs/concepts/roadmap/index.html
  docs/concepts/spiderendpoint/index.html
  docs/concepts/spiderippool/index.html
  docs/concepts/spiderreservedip/index.html
  docs/develop/changelog/index.html
  docs/develop/pullrequest/index.html
  docs/develop/release/index.html
  docs/develop/swagger_openapi/index.html
  docs/develop/test/index.html
  docs/index.html
  docs/index.yaml
  docs/overrides/assets/javascripts/bundle.33f04757.min.js
  docs/overrides/assets/javascripts/bundle.33f04757.min.js.map
  docs/overrides/assets/javascripts/iconsearch_index.json
  docs/overrides/assets/stylesheets/main.8a4f01ed.min.css
  docs/overrides/assets/stylesheets/main.8a4f01ed.min.css.map
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/basic/index.html
  docs/usage/cidrManager/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namespace/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/multi-interfaces-cni/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/statefulset/index.html
Labels: pr/release/robot_update_githubpage

#781 robot update changelog with tag v0.2.0 to branch github_pages
  changelogs/v0.1.4-to-v0.2.0.md
Labels: pr/release/robot_update_githubpage

#787 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.2.0.tgz
  docs/index.yaml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#786 robot update changelog with tag v0.2.0 to branch github_pages
  changelogs/v0.1.4-to-v0.2.0.md
Labels: pr/release/robot_update_githubpage

#788 typo
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/none-required, pr/ready-review

#791 fix subnet
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/types/interface.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/none-required, pr/ready-review

#793 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.2.0.tgz
  docs/index.yaml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#792 robot update changelog with tag v0.2.0 to branch github_pages
  changelogs/v0.1.4-to-v0.2.0.md
Labels: pr/release/robot_update_githubpage

#806 fix spider-init bug to read ipRange
  charts/spiderpool/README.md
  charts/spiderpool/templates/_helpers.tpl
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/templates/tls.yaml
  charts/spiderpool/templates/webhook.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-init/cmd/config.go
Labels: pr/release/bug

#808 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.2.0.tgz
  docs/index.yaml
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#807 robot update changelog with tag v0.2.0 to branch github_pages
  changelogs/v0.1.4-to-v0.2.0.md
Labels: pr/release/robot_update_githubpage

#805 fix: CRD Name mismatch in cleanCRD.sh
  tools/scripts/cleanCRD.sh
Labels: pr/release/none-required, pr/ready-review

#801 fromat import
  pkg/ip/ip.go
Labels: pr/release/none-required

#810 spider-init parse issue
  charts/spiderpool/templates/pod.yaml
  cmd/spiderpool-init/cmd/config.go
Labels: pr/release/bug

#812 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.2.0.tgz
  docs/index.yaml
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#811 robot update changelog with tag v0.2.0 to branch github_pages
  changelogs/v0.1.4-to-v0.2.0.md
Labels: pr/release/robot_update_githubpage

#814 docs:Add docs basic.md
  .github/.spelling
  docs/example/basic/custom-ippool-deploy.yaml
  docs/example/basic/custom-ipv4-ippool.yaml
  docs/usage/basic.md
  docs/usage/ippool-multi.md
Labels: pr/release/doc, pr/ready-review

#816 add spider subnet markdown
  .github/.spelling
  docs/concepts/spiderippool.md
  docs/concepts/spidersubnet.md
  docs/example/spider-subnet/deploy-use-subnet.yaml
  docs/example/spider-subnet/subnet-demo.yaml
  docs/example/statefulset/statefulset-demo.yaml
  docs/usage/cidrManager.md
  docs/usage/spider-subnet.md
  docs/usage/statefulset.md
Labels: pr/release/doc

#819 robot update changelog with tag v0.2.2 to branch github_pages
  changelogs/v0.2.0-to-v0.2.2.md
Labels: pr/release/robot_update_githubpage
