Repository spidernet-io/spiderpool, pull requests merged in 2022-05, with the labels that each got.

#198 Pr/welan/e2eee
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/lint-golang.yaml
  .gitignore
  Makefile
  docs/contributing/development/test.md
  test/Makefile
  test/Makefile.defs
  test/e2e/framework/framework.go
  test/e2e/ippool/ippool_suite_test.go
  test/scripts/cni-install.sh
  test/scripts/install-macvlan.sh
  test/scripts/install-whereabouts.sh
  test/yamls/10-macvlan.tmpl
  test/yamls/daemonset-install.yaml
  test/yamls/kind-config.tmpl
Labels: pr/release/none-required

#201 Pr/welan/e2eee
  .github/workflows/status.yaml
  README.md
  tools/scripts/codeCoverage.sh
Labels: pr/release/none-required

#204 update e2e status
  .github/.spelling
  .github/workflows/status.yaml
  test/doc/performance.md
  test/doc/testippool.md
  test/e2e/framework/const.go
  test/e2e/ippool/pod_test.go
  tools/scripts/e2ecover.sh
Labels: pr/release/none-required

#209 Pr/welan/optt
  .golangci.yaml
  CODEOWNERS
  test/Makefile
  test/Makefile.defs
  test/e2e/framework/framework.go
  test/e2e/ippool/ippool_suite_test.go
  test/e2e/ippool/pod_test.go
  test/e2e/tools/pod.go
Labels: pr/release/none-required

#213 update e2e framework
  go.mod
  go.sum
  test/e2e/ippool/ippool_suite_test.go
  vendor/github.com/spidernet-io/e2eframework/.gitignore
  vendor/github.com/spidernet-io/e2eframework/.golangci.yaml
  vendor/github.com/spidernet-io/e2eframework/.licenserc.yaml
  vendor/github.com/spidernet-io/e2eframework/CODEOWNERS
  vendor/github.com/spidernet-io/e2eframework/Makefile
  vendor/github.com/spidernet-io/e2eframework/Makefile.defs
  vendor/github.com/spidernet-io/e2eframework/Makefile.quiet
  vendor/github.com/spidernet-io/e2eframework/README.md
  vendor/github.com/spidernet-io/e2eframework/codecov.yml
  vendor/github.com/spidernet-io/e2eframework/framework/deployment.go
  vendor/github.com/spidernet-io/e2eframework/framework/framework.go
  vendor/github.com/spidernet-io/e2eframework/framework/job.go
  vendor/github.com/spidernet-io/e2eframework/framework/kind.go
  vendor/github.com/spidernet-io/e2eframework/framework/namespace.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/github.com/spidernet-io/e2eframework/framework/replicaset.go
  vendor/github.com/spidernet-io/e2eframework/framework/statefulset.go
  vendor/github.com/spidernet-io/e2eframework/framework/vagrant.go
  vendor/github.com/spidernet-io/e2eframework/tools/tools.go
  vendor/modules.txt
Labels: pr/release/none-required

#210 fix unix socket path already listen bug
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool/cmd/cmd_suite_test.go
  cmd/spiderpool/cmd/command_test.go
  pkg/cmdgenmd/cmd_generate_markdown.go
Labels: pr/release/none-required

#226 k8s:Add webhook test suite
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/controller_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/webhook/webhook_suite_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/helper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/errors.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_other.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_unix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/addr/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/certs/tinyca.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/auth.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/etcd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/kubectl.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/plane.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/arguments.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/bin_path_finder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/process.go
Labels: pr/release/none-required

#229 update e2e cal
  CODEOWNERS
  static/logo.svg
  tools/scripts/e2ecover.sh
Labels: pr/release/none-required

#232 update pr template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .golangci.yaml
Labels: pr/release/none-required

#233 typo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr/release/none-required

#236 add e2e test cases to markdown
  test/doc/performance.md
  test/doc/reliability.md
  test/doc/testippool.md
Labels: pr/release/none-required

#242 calculate todo number
  .github/workflows/status.yaml
  README.md
  tools/scripts/todocover.sh
Labels: pr/release/none-required

#244 update code owner
  CODEOWNERS
Labels: pr/release/none-required

#245 update code owner
  CODEOWNERS
Labels: pr/release/none-required

#247 check TODO comment
  .github/workflows/build-image-ci.yaml
  .github/workflows/lint-golang.yaml
  cmd/spiderpool-agent/cmd/command_shutdown.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/health.go
  cmd/spiderpool-agent/cmd/ipam.go
  cmd/spiderpool-agent/cmd/runtime_status.go
  cmd/spiderpool-controller/cmd/command_shutdown.go
  cmd/spiderpool-controller/cmd/command_status.go
  cmd/spiderpool-controller/cmd/controller_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-controller/cmd/runtime_status.go
  docs/contributing/development/pullrequest.md
  tools/scripts/todocover.sh
Labels: pr/release/none-required

#250 check pod ready when CI
  Makefile
  Makefile.defs
  cmd/spiderpool-controller/cmd/daemon.go
  test/Makefile
  test/scripts/install-multus.sh
  test/scripts/install-tools.sh
Labels: pr/release/none-required

#246 add e2e-test arm64 support
  Makefile.defs
  test/Makefile
  test/Makefile.defs
  test/scripts/install-whereabouts.sh
  test/scripts/prepare.sh
Labels: pr/release/none-required

#249 add e2e test case E00002
  go.mod
  go.sum
  test/e2e/common/deployment.go
  test/e2e/ippool/deployment_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/deployment.go
  vendor/github.com/spidernet-io/e2eframework/framework/framework.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/github.com/spidernet-io/e2eframework/framework/statefulset.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#252 add e2e test case E00003
  go.mod
  go.sum
  test/doc/testippool.md
  test/e2e/common/statefulset.go
  test/e2e/ippool/statefulset_test.go
Labels: pr/release/none-required, pr/ready-review

#248 case E00008 test ip gc after namespace is deleted
  go.mod
  test/e2e/common/pod.go
  test/e2e/common/tools.go
  test/e2e/ippool/namespace_test.go
Labels: pr/release/none-required, pr/ready-review

#223 improve ipam plugin add
  api/v1/agent/client/daemonset/delete_ipam_ip_parameters.go
  api/v1/agent/client/daemonset/post_ipam_ip_parameters.go
  api/v1/agent/client/daemonset/post_ipam_ip_responses.go
  api/v1/agent/models/dns.go
  api/v1/agent/models/ip_config.go
  api/v1/agent/models/ipam_add_args.go
  api/v1/agent/models/ipam_add_response.go
  api/v1/agent/models/ipam_del_args.go
  api/v1/agent/models/route.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  api/v1/agent/server/restapi/daemonset/delete_ipam_ip_parameters.go
  api/v1/agent/server/restapi/daemonset/post_ipam_ip_parameters.go
  api/v1/agent/server/restapi/daemonset/post_ipam_ip_responses.go
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/command_daemon.go
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/http_server.go
  cmd/spiderpool-agent/cmd/unix_server.go
  cmd/spiderpool/cmd/cmd_suite_test.go
  cmd/spiderpool/cmd/cni_types.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
  cmd/spiderpool/cmd/command_test.go
  cmd/spiderpool/cmd/utils.go
  cmd/spiderpool/main.go
  go.mod
  pkg/cnicommon/cni_types.go
  pkg/constant/k8s.go
  vendor/github.com/onsi/gomega/ghttp/handlers.go
  vendor/github.com/onsi/gomega/ghttp/test_server.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#255 add daemonset E00004
  go.mod
  go.sum
  test/e2e/common/daemonset.go
  test/e2e/ippool/daemonset_pod_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/daemonset.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#256 add replicaset e2e test (E00006)
  test/e2e/common/replicaset.go
  test/e2e/ippool/replicaset_pod_test.go
Labels: pr/release/none-required, pr/ready-review

#260 run all e2e when e2e updated
  .github/workflows/auto-nightly-ci.yaml
Labels: pr/release/none-required

#262 update ci
  .github/workflows/build-image-base.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/ci-images-cache-cleaner.yaml
  .github/workflows/lint-codeowners.yaml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-license.yaml
Labels: pr/release/none-required

#266 fix ci bug
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/status.yaml
Labels: pr/release/none-required

#269 update e2e markdown
  Makefile
  docs/contributing/development/test.md
  test/Makefile
  test/Makefile.defs
Labels: pr/release/none-required

#270 robot update doc from main to branch github_pages
  docs/404.html
  docs/assets/javascripts/bundle.a6c66575.min.js
  docs/assets/javascripts/bundle.a6c66575.min.js.map
  docs/assets/javascripts/bundle.ed9748b7.min.js
  docs/assets/javascripts/bundle.ed9748b7.min.js.map
  docs/assets/stylesheets/main.c382b1dc.min.css
  docs/assets/stylesheets/main.c382b1dc.min.css.map
  docs/assets/stylesheets/main.e411adfe.min.css
  docs/assets/stylesheets/main.e411adfe.min.css.map
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/arch/index.html
  docs/concepts/crd/index.html
  docs/contributing/development/changelog/index.html
  docs/contributing/development/chart/index.html
  docs/contributing/development/daily_build/index.html
  docs/contributing/development/github_pages/index.html
  docs/contributing/development/issue/index.html
  docs/contributing/development/pullrequest/index.html
  docs/contributing/development/release/index.html
  docs/contributing/development/roadmap/index.html
  docs/contributing/development/swagger_openapi/index.html
  docs/contributing/development/test/index.html
  docs/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#257 ipam plugin installation
  .github/.spelling
  charts/spiderpool/templates/daemonset.yaml
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool/cmd/cni_types.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
  cmd/spiderpool/cmd/command_test.go
  cmd/spiderpool/cmd/utils.go
  cmd/spiderpool/main.go
  test/yamls/10-macvlan.tmpl
Labels: pr/release/none-required, pr/ready-review

#271 add unit test case for plugin
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
  cmd/spiderpool/cmd/command_test.go
Labels: pr/release/none-required, pr/ready-review

#263 case R00002 create pod when etcd is unstable
  go.mod
  go.sum
  test/doc/reliability.md
  test/e2e/common/pod.go
  test/e2e/ippool/namespace_test.go
  test/e2e/ippool/pod_test.go
  test/e2e/reliability/reliability_suite_test.go
  test/e2e/reliability/reliability_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/daemonset.go
  vendor/github.com/spidernet-io/e2eframework/framework/deployment.go
  vendor/github.com/spidernet-io/e2eframework/framework/error.go
  vendor/github.com/spidernet-io/e2eframework/framework/namespace.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/github.com/spidernet-io/e2eframework/framework/replicaset.go
  vendor/github.com/spidernet-io/e2eframework/framework/statefulset.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#273 solve merge conflict
  cmd/spiderpool/cmd/command_test.go
Labels: pr/release/none-required, pr/ready-review

#274 add performance test case for spiderpool
  go.mod
  go.sum
  test/e2e/common/constant.go
  test/e2e/performance/ippool_perf_test.go
  test/e2e/performance/performance_suite_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/github.com/spidernet-io/e2eframework/framework/statefulset.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#277 update doc
  .github/.spelling
  .github/codespell-ignorewords
  README.md
  docs/concepts/allocation.md
  docs/concepts/arch.md
  docs/concepts/crd.md
  docs/concepts/gc.md
  docs/concepts/images/arch.jpg
  docs/concepts/ippool.md
  docs/concepts/reservedip.md
  docs/concepts/roadmap.md
  docs/concepts/workloadendpoint.md
  docs/contributing/development/changelog.md
  docs/contributing/development/chart.md
  docs/contributing/development/daily_build.md
  docs/contributing/development/github_pages.md
  docs/contributing/development/issue.md
  docs/contributing/development/pullrequest.md
  docs/contributing/development/release.md
  docs/develop/changelog.md
  docs/develop/pullrequest.md
  docs/develop/release.md
  docs/develop/swagger_openapi.md
  docs/develop/test.md
  docs/usage/advance.md
  docs/usage/annotation.md
  docs/usage/cli.md
  docs/usage/config.md
  docs/usage/demo.md
  docs/usage/metrics.md
  docs/usage/qa.md
  docs/usage/reservedip.md
Labels: pr/release/none-required

#278 optimize ci
  .github/workflows/auto-nightly-ci.yaml
Labels: pr/release/none-required

#280 update doc
  README.md
Labels: pr/release/none-required

#281 update doc
  docs/concepts/allocation.md
  docs/concepts/arch.md
  docs/concepts/gc.md
  docs/concepts/ippool.md
  docs/concepts/reservedip.md
  docs/concepts/workloadendpoint.md
  docs/develop/changelog.md
  docs/develop/pullrequest.md
  docs/develop/release.md
  docs/develop/swagger_openapi.md
  docs/develop/test.md
  docs/usage/advance.md
  docs/usage/annotation.md
  docs/usage/cli.md
  docs/usage/config.md
  docs/usage/demo.md
  docs/usage/metrics.md
  docs/usage/qa.md
  docs/usage/reservedip.md
Labels: pr/release/none-required

#283 add test case to md
  test/doc/annotation.md
  test/doc/assignip.md
  test/doc/cli.md
  test/doc/configmap.md
  test/doc/editcrd.md
  test/doc/gcip.md
  test/doc/metric.md
  test/doc/performance.md
  test/doc/reliability.md
  test/doc/reservedip.md
  test/doc/testippool.md
Labels: pr/release/none-required, pr/ready-review

#284 typo
  .github/workflows/auto-nightly-ci.yaml
  README.md
  test/e2e/performance/ippool_perf_test.go
  tools/scripts/e2eperformance.sh
Labels: pr/release/none-required
