Repository spidernet-io/spiderpool, pull requests merged in 2022-07, with the labels that each got.

#400 E2E:fix ci for spiderpool
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required, pr/ready-review

#408 E2E:update go.mod for E2E CI BUG
  go.mod
  go.sum
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#397 fix:IP leakage caused by IP rollback failure of incomplete IP allocation
  charts/spiderpool/templates/deployment.yaml
  pkg/ipam/ipam.go
  pkg/ipam/tools.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/Makefile
Labels: pr/release/bug, pr/ready-review

#413 fix:Failed to rollback IP allocation correctly
  charts/spiderpool/crds/spiderpool.spidernet.io_workloadendpoints.yaml
  cmd/spiderpool-agent/cmd/command_daemon.go
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/k8s/apis/v1/workloadendpoint_types.go
  pkg/k8s/apis/v1/zz_generated.deepcopy.go
  pkg/podmanager/pod_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/bug, pr/ready-review

#417 improve IP GC configuration parsing
  cmd/spiderpool-controller/cmd/command_daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/podEvent_reconcile.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
Labels: pr/release/none-required, pr/ready-review

#401 switch to client-go leader election
  charts/spiderpool/templates/deployment.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/constant/k8s.go
  pkg/election/lease_election.go
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/podEvent_reconcile.go
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
Labels: pr/release/none-required, pr/ready-review

#425 ci: add more debug information
  test/scripts/debugEnv.sh
Labels: pr/release/none-required

#402 [docs] improve README.md
  .github/.spelling
  README.md
Labels: pr/release/none-required

#423 E2E:Synchronize e2e case label with e2e case doc for spiderpool
  test/e2e/assignip/assignip_test.go
  test/e2e/labelselector/labelselector_suite_test.go
Labels: pr/release/none-required, pr/ready-review

#429 e2e: node could communicate with pod
  test/Makefile
  test/scripts/makeNodeMacvlan.sh
Labels: pr/release/none-required

#428 E2E:fail to run pod who is bound to an ippool set with no-matched selector
  test/e2e/common/pod.go
  test/e2e/labelselector/labelselector_suite_test.go
  test/e2e/labelselector/labelselector_test.go
Labels: pr/release/none-required, pr/ready-review

#438 ci: print previous log
  test/scripts/debugEnv.sh
Labels: pr/release/none-required

#441 ci: fix gateway for makeNodeMacvlan
  test/scripts/makeNodeMacvlan.sh
Labels: pr/release/none-required

#424 feat:Add pkg limiter
  pkg/limiter/limiter_suite_test.go
  pkg/limiter/queue.go
  pkg/limiter/queue_test.go
Labels: pr/release/none-required, pr/ready-review

#331 E2E: case G00003 the IP should be reclaimed after its pod is deleted , eve…
  test/e2e/assignip/assignip_test.go
  test/e2e/reclaim/reclaim_suite_test.go
  test/e2e/reclaim/reclaim_test.go
Labels: pr/release/none-required

#444 doc: fix readme
  .github/.spelling
  README.md
  charts/spiderpool/values.yaml
  docs/usage/demo.md
  docs/usage/install.md
Labels: pr/release/bug

#447 ci: add some debug log
  test/Makefile
  test/scripts/debugEnv.sh
Labels: pr/release/none-required

#416 E2E:add test case A00004 for spiderpool
  test/e2e/annotation/annotation_suite_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/common/spiderpool.go
Labels: pr/release/none-required, pr/ready-review

#451 doc: install
  docs/usage/install.md
Labels: pr/release/doc

#453 add pool validation for e2e configmap
  test/e2e/common/spiderpool.go
Labels: pr/release/bug, pr/ready-review

#460 charts: optimize configmap
  charts/spiderpool/templates/configmap.yaml
Labels: pr/release/chart

#437 fix:IP leakage caused by too many conflicts when update ippool in high concurrency case
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/crd_manager.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_test.go
  pkg/constant/ip.go
  pkg/constant/k8s.go
  pkg/ipam/ipam.go
  pkg/ipam/tools.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/limiter/queue.go
  pkg/podmanager/pod_manager.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/bug, pr/ready-review

#411 improve IPPool IP GC when containerID is different with WEP current
  pkg/gcmanager/scanAll_IPPool.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/none-required, pr/ready-review

#467 E2E: add case A00008 for fix issue #234
  test/doc/annotation.md
Labels: pr/release/none-required, pr/ready-review

#445 E2E: add test case S00001 for spiderpool
  test/e2e/common/deployment.go
  test/e2e/common/reservedip.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required, pr/ready-review

#430 ippool gc and reconcile
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/templates/webhook.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/constant/k8s.go
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/tracePod_worker.go
  pkg/ip/ips.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_reconcile.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/k8s/apis/v1/ippool_types.go
  pkg/webhook/ippool_webhook.go
  pkg/webhook/webhook_suite_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/e2e/common/spiderpool.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/helper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/errors.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_other.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_unix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/addr/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/certs/tinyca.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/auth.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/etcd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/kubectl.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/plane.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/arguments.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/bin_path_finder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/process.go
Labels: pr/release/none-required, pr/ready-review

#473 workflow: retention-days of artifact
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
Labels: pr/release/none-required

#472 Fixed the address conflict in pkg/ipam/tool.go
  pkg/ipam/tools.go
Labels: pr/release/bug, pr/ready-review

#477 IP GC podEntry improvement
  pkg/gcmanager/pod_cache.go
Labels: pr/release/none-required, pr/ready-review

#479 Fixed CI failure caused by node not ready
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required

#481 Fixed variable which share the same address in pkg/ipam/tool.go
  pkg/ipam/tools.go
Labels: pr/release/none-required, issue/bug

#484 limter pkg: avoid unnecessary wait
  pkg/limiter/queue.go
Labels: pr/release/none-required

#457 github action: submit charts to github pages
  .github/workflows/auto-release.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required

#483 feat:Add validating webhook of IPPool
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderreservedips.yaml
  charts/spiderpool/templates/cluster-default-ippool.yaml
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/ipam.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool/cmd/command_add.go
  pkg/constant/ip.go
  pkg/constant/k8s.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/ip/README.md
  pkg/ip/ips.go
  pkg/ipam/ipam.go
  pkg/ipam/tools.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_reconcile.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/ippoolmanager/tools.go
  pkg/k8s/apis/v1/groupversion_info.go
  pkg/k8s/apis/v1/ippool_types.go
  pkg/k8s/apis/v1/reservedip_types.go
  pkg/k8s/apis/v1/workloadendpoint_types.go
  pkg/k8s/apis/v1/zz_generated.deepcopy.go
  pkg/namespacemanager/namespace_manager.go
  pkg/nodemanager/node_manager.go
  pkg/podmanager/pod_manager.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/types/ip.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/e2e/annotation/annotation_test.go
  test/e2e/common/reservedip.go
  test/e2e/common/spiderpool.go
Labels: pr/release/feature-new, pr/ready-review

#491 robot update changelog with tag v0.0.5 to branch github_pages
  changelogs/v0.0.4-to-v0.0.5.md
Labels: pr/release/robot_update_githubpage

#492 workflow: comment
  .github/workflows/auto-release.yaml
  .github/workflows/call-lint-chart.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/ci-image-gc-by-pr.yaml
  .github/workflows/pr-label-assign.yaml
  .github/workflows/pr-label-check.yaml
Labels: pr/release/none-required

#499 doc: typo
  .github/.spelling
  README.md
Labels: pr/release/doc

#500 add statefulset support markdown
  .github/.spelling
  docs/usage/statefulset.md
Labels: pr/release/none-required, pr/ready-review

#501 docs:Add docs reserved-ip.md
  .github/.spelling
  docs/usage/reserved-ip.md
  docs/usage/reservedip.md
Labels: pr/release/none-required, pr/ready-review

#488 feat:Set gateway and routes for Pod
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_test.go
  pkg/constant/ip.go
  pkg/constant/k8s.go
  pkg/ipam/convert.go
  pkg/ipam/ipam.go
  pkg/ipam/ipam_config.go
  pkg/ipam/tools.go
  pkg/ipam/types.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/k8s/apis/v1/ippool_types.go
  pkg/k8s/apis/v1/reservedip_types.go
  pkg/k8s/apis/v1/workloadendpoint_types.go
  pkg/k8s/apis/v1/zz_generated.deepcopy.go
  pkg/limiter/queue.go
  pkg/logutils/log_test.go
  pkg/types/k8s.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/none-required, pr/ready-review
