Repository spidernet-io/spiderpool, pull requests merged in 2023-05, with the labels that each got.

#1746 fix third-party controller auto-pool reclaim ippool symbol
  pkg/ipam/pool_selections.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.5

#1748 title: fix third-party controller auto-pool reclaim ippool symbol
  pkg/ipam/pool_selections.go
Labels: pr/release/bug, pr/ready-review, robot-cherrypick

#1750 supplement IP GC documents
  docs/usage/gc.md
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.5

#1749 fix Auto IPPool label value over maximum length limit
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/applicationinformers/utils.go
  pkg/constant/k8s.go
  pkg/ipam/pool_selections.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_informer_test.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/ippoolmanager/utils.go
  pkg/ippoolmanager/utils_test.go
  pkg/subnetmanager/subnet_manager.go
  test/e2e/kruise/kruise_test.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.5

#1751 title: supplement IP GC documents
  docs/usage/gc.md
Labels: pr/release/none-required, pr/ready-review, robot-cherrypick

#1757 add auto pool reclaim swicth support
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/applicationinformers/utils.go
  pkg/ipam/pool_selections.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/feature-new, pr/ready-review, cherrypick-release-v0.5

#1762 Cherrypick 1749&1757 to release v0.5
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/applicationinformers/utils.go
  pkg/constant/k8s.go
  pkg/ipam/pool_selections.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/ippoolmanager/utils.go
  pkg/ippoolmanager/utils_test.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/none-required, pr/ready-review

#1764 title: add cluster subnet flexible ip number support
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/applicationcontroller/applicationinformers/utils.go
Labels: pr/release/feature-new, pr/ready-review, robot-cherrypick

#1768 supplement annotation for Auto-Pool
  pkg/applicationcontroller/app_controller.go
  pkg/ipam/pool_selections.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_manager_test.go
  pkg/types/k8s.go
Labels: pr/release/feature-new, pr/ready-review, cherrypick-release-v0.5

#1765 docs improvement
  docs/concepts/annotation.md
  docs/concepts/config.md
  docs/usage/spider-subnet.md
  docs/usage/statefulset.md
  docs/usage/third-party-controller.md
Labels: pr/release/none-required, pr/ready-review, kind/documentation, cherrypick-release-v0.5

#1774 cherrypick 1768 to release-v0.5
  pkg/applicationcontroller/app_controller.go
  pkg/ipam/pool_selections.go
  pkg/subnetmanager/subnet_manager.go
  pkg/types/k8s.go
Labels: pr/release/none-required, pr/ready-review

#1776 improve iprange function to reduce memory allocation
  pkg/ip/ip.go
  pkg/ip/iprange.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.5

#1770 compatibility Testing for kubernetes v1.27
  .github/workflows/auto-diff-k8s-ci.yaml
  test/Makefile.defs
Labels: pr/release/none-required, pr/ready-review, kind/feature

#1777 title: docs improvement
  docs/concepts/annotation.md
  docs/concepts/config.md
  docs/usage/spider-subnet.md
  docs/usage/statefulset.md
  docs/usage/third-party-controller.md
Labels: pr/release/none-required, pr/ready-review, robot-cherrypick

#1778 title: improve iprange function to reduce memory allocation
  pkg/ip/ip.go
  pkg/ip/iprange.go
Labels: pr/release/bug, pr/ready-review, robot-cherrypick

#1773 E2E: Third party controller use case changes
  test/doc/assignip.md
  test/doc/cidr.md
  test/doc/third-party-controller.md
  test/e2e/common/spiderpool.go
  test/e2e/kruise/kruise_test.go
Labels: pr/release/none-required, pr/ready-review

#1779 fix: check wbehook healthy ready for e2e
  test/e2e/common/constant.go
  test/e2e/common/spiderpool.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required, pr/ready-review

#1766 E2E: the application of the same name will inherit the automatic IPPool
  test/doc/cli.md
  test/doc/configmap.md
  test/doc/metric.md
  test/doc/subnet.md
  test/e2e/cli/cli_suite_test.go
  test/e2e/configmap/configmap_suite_test.go
  test/e2e/metric/metric_suite_test.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1760 feat: Add CRD SpiderCoordinator
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/templates/role.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1/fake/fake_spidercoordinator.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1/fake/fake_spiderpool.spidernet.io_client.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1/generated_expansion.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1/spidercoordinator.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1/spiderpool.spidernet.io_client.go
  pkg/k8s/client/informers/externalversions/generic.go
  pkg/k8s/client/informers/externalversions/spiderpool.spidernet.io/v2beta1/interface.go
  pkg/k8s/client/informers/externalversions/spiderpool.spidernet.io/v2beta1/spidercoordinator.go
  pkg/k8s/client/listers/spiderpool.spidernet.io/v2beta1/expansion_generated.go
  pkg/k8s/client/listers/spiderpool.spidernet.io/v2beta1/spidercoordinator.go
Labels: pr/release/feature-new, pr/ready-review

#1772 feat: Add SpiderCoordinator controller
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  go.mod
  go.sum
  pkg/constant/k8s.go
  pkg/coordinatormanager/calico_ippool_informer.go
  pkg/coordinatormanager/coordinator_informer.go
  pkg/subnetmanager/subnet_informer.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/projectcalico/api/LICENSE
  vendor/github.com/projectcalico/api/pkg/lib/numorstring/asnumber.go
  vendor/github.com/projectcalico/api/pkg/lib/numorstring/doc.go
  vendor/github.com/projectcalico/api/pkg/lib/numorstring/port.go
  vendor/github.com/projectcalico/api/pkg/lib/numorstring/protocol.go
  vendor/github.com/projectcalico/api/pkg/lib/numorstring/type.go
  vendor/github.com/projectcalico/api/pkg/lib/numorstring/uint8orstring.go
  vendor/github.com/tigera/api/LICENSE
  vendor/github.com/tigera/api/pkg/lib/numorstring/asnumber.go
  vendor/github.com/tigera/api/pkg/lib/numorstring/doc.go
  vendor/github.com/tigera/api/pkg/lib/numorstring/port.go
  vendor/github.com/tigera/api/pkg/lib/numorstring/protocol.go
  vendor/github.com/tigera/api/pkg/lib/numorstring/type.go
  vendor/github.com/tigera/api/pkg/lib/numorstring/uint8orstring.go
  vendor/github.com/tigera/operator/LICENSE
  vendor/github.com/tigera/operator/pkg/apis/crd.projectcalico.org/v1/bgpconfig.go
  vendor/github.com/tigera/operator/pkg/apis/crd.projectcalico.org/v1/doc.go
  vendor/github.com/tigera/operator/pkg/apis/crd.projectcalico.org/v1/externalnetwork.go
  vendor/github.com/tigera/operator/pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  vendor/github.com/tigera/operator/pkg/apis/crd.projectcalico.org/v1/ippool.go
  vendor/github.com/tigera/operator/pkg/apis/crd.projectcalico.org/v1/kubecontrollersconfiguration.go
  vendor/github.com/tigera/operator/pkg/apis/crd.projectcalico.org/v1/register.go
  vendor/github.com/tigera/operator/pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/modules.txt
Labels: pr/release/feature-new, pr/ready-review

#1784 feat: Add SpiderCoordinator webhook
  charts/spiderpool/templates/tls.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/coordinatormanager/coordinator_webhook.go
Labels: pr/release/feature-new, pr/ready-review

#1761 opt calico doc
  docs/usage/get-started-calico-zh_CN.md
  docs/usage/get-started-calico.md
Labels: pr/release/none-required, kind/documentation, kind/cleanup, cherrypick-release-v0.5

#1785 title: opt calico doc
  docs/usage/get-started-calico-zh_CN.md
  docs/usage/get-started-calico.md
Labels: robot-cherrypick

#1788 fix: CoordinatorController's member coordinatorName exists data race
  pkg/coordinatormanager/coordinator_informer.go
Labels: pr/release/none-required, pr/ready-review

#1786 feat: Auto installation of default SpiderCoordinator
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/client.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/root.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  test/Makefile
  test/Makefile.defs
Labels: pr/release/feature-new, pr/ready-review

#1789 feat: Add OpenAPI for the coordinator plugin to query its config
  api/v1/agent/client/daemonset/daemonset_client.go
  api/v1/agent/client/daemonset/get_coordinator_config_parameters.go
  api/v1/agent/client/daemonset/get_coordinator_config_responses.go
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/configure_spiderpool_agent_api.go
  api/v1/agent/server/embedded_spec.go
  api/v1/agent/server/restapi/daemonset/get_coordinator_config.go
  api/v1/agent/server/restapi/daemonset/get_coordinator_config_parameters.go
  api/v1/agent/server/restapi/daemonset/get_coordinator_config_responses.go
  api/v1/agent/server/restapi/daemonset/get_coordinator_config_urlbuilder.go
  api/v1/agent/server/restapi/spiderpool_agent_api_api.go
  cmd/spiderpool-agent/cmd/coordinator.go
  cmd/spiderpool-agent/cmd/unix_server.go
Labels: pr/release/feature-new, pr/ready-review

#1792 fix: spider-subnet.md typo
  docs/usage/spider-subnet.md
Labels: pr/release/none-required, pr/ready-review

#1794 add gateway for ippool-affinity-node.md
  docs/example/ippool-affinity-node/master-ipv4-ippool.yaml
  docs/example/ippool-affinity-node/worker-ipv4-ippool.yaml
  docs/usage/ippool-affinity-node.md
Labels: pr/release/none-required, pr/ready-review

#1798 e2e fix: add curl command max time for webhook service health check
  test/e2e/common/spiderpool.go
Labels: pr/release/none-required, pr/ready-review

#1806 add ippool podAffinity validation
  pkg/constant/k8s.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/modules.txt
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.5

#1807 title: add ippool podAffinity validation
  pkg/constant/k8s.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/modules.txt
Labels: robot-cherrypick

#1808 title: supplement spider subnet feature docs
  docs/usage/spider-subnet.md
Labels: pr/release/none-required, pr/ready-review, robot-cherrypick

#1816 fix: Update the collection method of cluster CIDR
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/coordinatormanager/coordinator_informer.go
Labels: pr/release/none-required, pr/ready-review

#1818 format markdown doc
  docs/usage/gc.md
  docs/usage/get-started-calico-zh_CN.md
  docs/usage/get-started-calico.md
  docs/usage/get-started-kind-zh_CN.md
  docs/usage/get-started-kind.md
  docs/usage/get-started-macvlan-zh_CN.md
  docs/usage/get-started-macvlan.md
  docs/usage/get-started-ovs-zh_CN.md
  docs/usage/get-started-ovs.md
  docs/usage/get-started-sriov-zh_CN.md
  docs/usage/get-started-sriov.md
  docs/usage/ippool-affinity-pod.md
  docs/usage/ippool-multi.md
  docs/usage/ipv6.md
  docs/usage/multi-interfaces-annotation.md
  docs/usage/performance-zh_CH.md
  docs/usage/performance.md
  docs/usage/route.md
  docs/usage/spider-subnet.md
  docs/usage/statefulset.md
  docs/usage/third-party-controller.md
Labels: pr/release/none-required, pr/ready-review

#1819 spider subnet docs
  docs/usage/spider-subnet.md
Labels: pr/release/none-required, pr/ready-review

#1821 release v0.5.0
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#1825 robot update changelog with tag v0.5.0 to branch github_pages
  changelogs/changelog_from_v0.4.0_to_v0.5.0.md
Labels: pr/release/robot_update_githubpage

#1824 robot update chart and website from to branch github_pages
  docs/404.html
  docs/charts/spiderpool-0.5.0.tgz
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/metrics/index.html
  docs/concepts/spiderendpoint/index.html
  docs/concepts/spiderippool/index.html
  docs/concepts/spiderreservedip/index.html
  docs/concepts/spidersubnet/index.html
  docs/develop/CODE-OF-CONDUCT/index.html
  docs/develop/contributing/index.html
  docs/develop/release/index.html
  docs/develop/roadmap/index.html
  docs/develop/swagger_openapi/index.html
  docs/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/certificate/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/gc/index.html
  docs/usage/get-started-calico-zh_CN/index.html
  docs/usage/get-started-calico/index.html
  docs/usage/get-started-kind-zh_CN/index.html
  docs/usage/get-started-kind/index.html
  docs/usage/get-started-macvlan-zh_CN/index.html
  docs/usage/get-started-macvlan/index.html
  docs/usage/get-started-ovs-zh_CN/index.html
  docs/usage/get-started-ovs/index.html
  docs/usage/get-started-sriov-zh_CN/index.html
  docs/usage/get-started-sriov/index.html
  docs/usage/get-started-weave-zh_CN/index.html
  docs/usage/get-started-weave/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namespace/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/performance-zh_CH/index.html
  docs/usage/performance/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/route/index.html
  docs/usage/spider-subnet/index.html
  docs/usage/statefulset/index.html
  docs/usage/third-party-controller/index.html
  docs/usage/upgrade/index.html
Labels: pr/release/robot_update_githubpage

#1835 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.6.0-rc0.tgz
  docs/concepts/annotation/index.html
  docs/example/ippool-affinity-node/master-ipv4-ippool.yaml
  docs/example/ippool-affinity-node/worker-ipv4-ippool.yaml
  docs/index.yaml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/gc/index.html
  docs/usage/get-started-calico-zh_CN/index.html
  docs/usage/get-started-calico/index.html
  docs/usage/get-started-ovs-zh_CN/index.html
  docs/usage/get-started-ovs/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/performance/index.html
  docs/usage/spider-subnet/index.html
  docs/usage/statefulset/index.html
  docs/usage/third-party-controller/index.html
Labels: pr/release/robot_update_githubpage

#1836 robot update changelog with tag v0.6.0-rc0 to branch github_pages
  changelogs/changelog_from_v0.5.0_to_v0.6.0-rc0.md
Labels: pr/release/robot_update_githubpage

#1839 fix spiderpool-agent daemon data race
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.5, cherrypick-release-v0.6

#1841 title: fix spiderpool-agent daemon data race
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
Labels: pr/release/bug, robot-cherrypick

#1842 title: fix spiderpool-agent daemon data race
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
Labels: pr/release/bug, robot-cherrypick

#1844 update en doc: readme, arch and solution
  README-zh_CN.md
  README.md
  docs/concepts/arch-zh_CN.md
  docs/concepts/arch.md
  docs/concepts/solution-zh_CN.md
  docs/concepts/solution.md
Labels: pr/release/doc, kind/documentation

#1848 opt spider-agent installtion
  charts/spiderpool/templates/daemonset.yaml
Labels: pr/release/none-required

#1847 add ippool resource version in ipam log
  pkg/ippoolmanager/ippool_manager.go
Labels: pr/release/none-required, pr/ready-review, enhancement, cherrypick-release-v0.6

#1832 supplement unit test
  pkg/applicationcontroller/applicationinformers/utils_test.go
Labels: pr/release/none-required, pr/ready-review

#1849 fix: Remove legacy code of kubeadm-config
  pkg/coordinatormanager/coordinator_informer.go
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.6

#1850 title: add ippool resource version in ipam log
  pkg/ippoolmanager/ippool_manager.go
Labels: pr/release/none-required, pr/ready-review, robot-cherrypick, enhancement
