Repository spidernet-io/spiderpool, pull requests merged in 2023-11, with the labels that each got.

#2515 CI: don't run node reboot case for ifacer
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/ifacer/ifacer_test.go
  test/e2e/performance/performance_test.go
Labels: release/none

#2518 fix ipam block with ip address used out
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_test.go
  pkg/ippoolmanager/utils.go
  pkg/ippoolmanager/utils_test.go
Labels: pr/ready-review, cherrypick-release-v0.6, cherrypick-release-v0.7, release/bug

#2516 init-pod: add readiness for wait spiderpool-agent pods ready
  charts/spiderpool/README.md
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/client.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/multus.go
  cmd/spiderpool-init/cmd/root.go
  test/scripts/install-multus.sh
Labels: release/none

#2523 Use github forms for issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/ci-failure.md
  .github/ISSUE_TEMPLATE/doc.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/usage.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release/none

#2524 fix github issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/ci-failure.md
  .github/ISSUE_TEMPLATE/doc.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/usage.md
Labels: release/none

#2525 fix github issue forms
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/ci-failure.yaml
  .github/ISSUE_TEMPLATE/doc.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/usage.yaml
  .github/yamllint-conf.yml
Labels: release/none

#2454 doc: add en allocation
  docs/concepts/ipam-zh_CN.md
  docs/concepts/ipam.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release/none

#2532 spiderpool-controller readiness health check failure
  cmd/spiderpool-controller/cmd/runtime_status.go
Labels: pr/ready-review, cherrypick-release-v0.7, release/bug

#2531 fix judgment on spiderpoolperformance.json file
  .github/ISSUE_TEMPLATE/doc.yaml
  .github/workflows/e2e-init.yaml
Labels: release/none

#2537 spiderpool-controller readiness health check failure
  cmd/spiderpool-controller/cmd/runtime_status.go
Labels: robot-cherrypick

#2538 fix: statefulset duplicate IP issue
  pkg/gcmanager/scanAll_IPPool.go
  pkg/ipam/allocate.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_test.go
Labels: pr/ready-review, release/bug

#2539 optimize codes to verify IP update
  pkg/gcmanager/scanAll_IPPool.go
  pkg/ipam/allocate.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_test.go
Labels: pr/ready-review, enhancement, release/none

#2542 add downward API for spiderpool-agent to get pod name and namespace
  charts/spiderpool/templates/daemonset.yaml
Labels: enhancement, release/none

#2544 cleanup: remove configmap obsolete fields
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  pkg/ipam/config.go
  test/e2e/common/spiderpool.go
  test/e2e/common/spidersubnet.go
  test/e2e/subnet/subnet_test.go
Labels: pr/ready-review, enhancement, release/none

#2549 cherrypick 2518, 2514 and 2544 to release v0.7
  charts/spiderpool/templates/daemonset.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  pkg/ipam/allocate.go
  pkg/ipam/config.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_test.go
  pkg/ippoolmanager/utils.go
  pkg/ippoolmanager/utils_test.go
  test/e2e/common/spiderpool.go
  test/e2e/common/spidersubnet.go
  test/e2e/subnet/subnet_test.go
Labels: pr/ready-review, release/bug

#2548 doc: update en route
  docs/usage/route-zh_CN.md
  docs/usage/route.md
Labels: pr/release/doc, pr/ready-review, kind/doc, release/none

#2550 doc: add en ippool
  docs/usage/spider-ippool-zh_CN.md
  docs/usage/spider-ippool.md
Labels: pr/ready-review, kind/doc, release/none

#2554 doc: add en kubevirt
  docs/usage/kubevirt-zh_CN.md
  docs/usage/kubevirt.md
Labels: pr/ready-review, kind/doc, release/none

#2551 statefulset doc
  docs/usage/statefulset-zh_CN.md
  docs/usage/statefulset.md
Labels: pr/ready-review, kind/doc, release/none

#2556 release v0.7.1
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/ready-review

#2562 rebase call-release-chart
  .github/workflows/call-release-chart.yaml
Labels: release-v0.7, release/none

#2441 docs: Accelerate access to service for underlay CNI
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/images/spiderpool_service_kube_proxy.png
  docs/images/withou_kube_proxy.png
  docs/mkdocs.yml
  docs/usage/coordinator-zh_CN.md
  docs/usage/coordinator.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  docs/usage/underlay_cni_service-zh_CN.md
  docs/usage/underlay_cni_service.md
Labels: release/none

#2546 Publish development documents through github actions.
  .github/workflows/call-release-doc.yaml
Labels: kind/feature, kind/doc, release/none

#2574 CI: use GITHUB.TOKEN to operate github
  .github/workflows/auto-cherrypick.yaml
  .github/workflows/auto-diff-k8s-ci.yaml
Labels: release/none

#2577 docs: add kind to the document navigation bar
  docs/mkdocs.yml
  docs/usage/readme.md
Labels: kind/doc, release/none

#2579 docs: fix the md format
  docs/usage/underlay_cni_service-zh_CN.md
  docs/usage/underlay_cni_service.md
Labels: release/none

#2586 e2e: pending e2e case F00002
  test/e2e/kubevirt/kubevirt_test.go
Labels: kind/test, release/none

#2584 docs: Update sriov's pfNames field
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-sriov.md
Labels: kind/doc, release/none

#2585 docs: cleanup ipversion to simplify yaml
  docs/usage/ifacer-zh_CN.md
  docs/usage/ifacer.md
  docs/usage/install/cloud/get-started-aws-zh_CN.md
  docs/usage/install/cloud/get-started-aws.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/spider-affinity-zh_CN.md
  docs/usage/spider-affinity.md
Labels: kind/doc, release/none

#2555 docs: add spiderpool io performance
  docs/concepts/io-performance-zh_CN.md
Labels: kind/doc, release/none

#2582 docs: add aws to the document navigation bar
  docs/mkdocs.yml
Labels: kind/doc, release/none

#2553 docs: update spiderpool IPAM performance
  docs/concepts/ipam-performance-zh_CN.md
  docs/concepts/ipam-performance.md
Labels: kind/doc, release/none

#2589 docs: Add en doc for io performance
  docs/concepts/io-performance.md
Labels: kind/doc, release/none

#2587 docs: ifacer configuration
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/mkdocs.yml
  docs/reference/plugin-coordinator.md
  docs/reference/plugin-ifacer.md
  docs/usage/ifacer-zh_CN.md
  docs/usage/ifacer.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
Labels: release/none

#2590 fix document wrong links
  docs/concepts/ipam.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
Labels: pr/ready-review, kind/doc, release/none

#2593 docs: format doc
  docs/usage/underlay_cni_service-zh_CN.md
  docs/usage/underlay_cni_service.md
Labels: kind/doc, release/none

#2594 docs: format upgrade doc and error link
  docs/mkdocs.yml
  docs/usage/install/upgrade.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
  docs/usage/service-zh_CN.md
  docs/usage/service.md
  docs/usage/underlay_cni_service-zh_CN.md
Labels: kind/doc, release/none

#2604 e2e: Change the gc interval to 30s
  test/Makefile
Labels: kind/test, release/none

#2602 e2e: Add a new job to test low kernels in e2e
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/e2e-init.yaml
Labels: enhancement, kind/test, release/none

#2601 docs: fix performance value units
  docs/concepts/io-performance-zh_CN.md
  docs/concepts/io-performance.md
  docs/usage/underlay_cni_service-zh_CN.md
  docs/usage/underlay_cni_service.md
Labels: kind/doc, release/none, release-v0.8, cherrypick-release-v0.8

#2616 fix invaild debug log
  test/scripts/debugEnv.sh
Labels: release/none

#2612 e2e: Support calico version use the latest
  test/Makefile.defs
  test/scripts/install-default-cni.sh
Labels: release/none

#2603 spidermultusconfig: set default value if it not set
  charts/spiderpool/templates/tls.yaml
  pkg/constant/k8s.go
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_webhook.go
  test/Makefile.defs
  test/scripts/install-multus.sh
  test/scripts/prepare.sh
Labels: release/feature-changed, cherrypick-release-v0.8

#2626 docs: Fix description when `multus.multusCNI.defaultCniCRName` is empty.
  docs/usage/install/cloud/get-started-alibaba-zh_CN.md
  docs/usage/install/cloud/get-started-aws-zh_CN.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/underlay/get-started-calico-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-weave-zh_CN.md
  docs/usage/kubevirt-zh_CN.md
  docs/usage/network-topology-zh_CN.md
  docs/usage/rdma-zh_CN.md
Labels: kind/doc, release/none, cherrypick-release-v0.8

#2623 Add a script to install yq
  test/scripts/install-tools.sh
Labels: release/none

#2632 e2e: Tips for installing development tools
  test/scripts/install-tools.sh
Labels: release/none

#2641 docs: add egress docs for spiderpool
  docs/usage/egress-zh_CN.md
  docs/usage/egress.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/spider-ippool-zh_CN.md
Labels: kind/doc, release/none

#2639 ifacer: Fix the slave with bond was not set if vlanId was set to 0
  cmd/ifacer/cmd/cmd_add.go
Labels: cherrypick-release-v0.7, release/bug, cherrypick-release-v0.8

#2618 no interface name in annotation to support multiple NIC
  docs/usage/spider-ippool-zh_CN.md
  docs/usage/spider-ippool.md
  go.mod
  go.sum
  pkg/ipam/allocate.go
  pkg/ipam/pool_selections.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_test.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/ippoolmanager/utils.go
  pkg/ippoolmanager/utils_test.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/types_string.go
  pkg/types/k8s.go
  pkg/utils/convert/convert.go
  pkg/workloadendpointmanager/utils.go
  pkg/workloadendpointmanager/utils_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/common/constant.go
  test/e2e/ippoolcr/ippoolcr_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/job.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/modules.txt
Labels: pr/ready-review, kind/feature, release/feature-new

#2637 spidermultusconfig: It's able to configure bandwidth for sriov config
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  docs/reference/crd-spidermultusconfig.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/utils.go
Labels: kind/feature, release/feature-new

#2655 coordinator: improve tuning polocy of routes to support kubevirt
  cmd/coordinator/cmd/utils.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/usage/underlay_cni_service-zh_CN.md
  docs/usage/underlay_cni_service.md
  pkg/networking/networking/route.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/none

#2656 CI: Variables such as kdoctor are only triggered in CI
  .github/workflows/e2e-init.yaml
Labels: release/none

#2661 docs: Fix NetworkManager manager ifacer's interface
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/reference/plugin-ifacer.md
  docs/usage/install/underlay/get-started-kind-zh_CN.md
  docs/usage/install/underlay/get-started-kind.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-sriov.md
Labels: kind/doc, release/none, cherrypick-release-v0.8

#2469 add e2e ovs installation and ovs net-attach-def configurations
  docs/usage/kubevirt-zh_CN.md
  docs/usage/kubevirt.md
  test/Makefile
  test/Makefile.defs
  test/doc/kubevirt.md
  test/e2e/common/constant.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/kubevirt/kubevirt_suite_test.go
  test/e2e/kubevirt/kubevirt_test.go
  test/scripts/debugEnv.sh
  test/scripts/install-kdoctor.sh
  test/scripts/install-kubevirt.sh
  test/scripts/install-multus.sh
  test/scripts/install-ovs.sh
Labels: pr/ready-review, release/feature-new

#2667 fix path typo in spiderpool-agent yaml
  charts/spiderpool/templates/daemonset.yaml
Labels: pr/ready-review, enhancement, cherrypick-release-v0.7, release/bug, cherrypick-release-v0.8

#2673 update spiderpool to v0.9.0-rc0
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/ready-review, release/none

#2681 fix charts version typo
  charts/spiderpool/Chart.yaml
Labels: pr/ready-review, release/none

#2682 update kdoctor version to v0.2.1
  test/Makefile.defs
Labels: release/none

#2685 update to v0.8.1
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/ready-review, release/none
