Repository spidernet-io/spiderpool, pull requests merged in 2023-02, with the labels that each got.

#1300 test: supplement pod manager unit test
  pkg/podmanager/pod_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1302 test: supplement cmdAdd and cmdDel unit test
  cmd/spiderpool/cmd/command_test.go
Labels: pr/release/none-required, pr/ready-review

#1272 add third party controller application support with SpiderSubnet feature
  docs/usage/third-party-controller.md
  pkg/ipam/ipam.go
  test/e2e/kruise/kruise_test.go
Labels: pr/release/feature-new, pr/ready-review

#1308 fix: Occasionally failed to set the correct SpiderSubnet owner ref in the unit test of SpiderIPPool
  cmd/spiderpool-agent/cmd/daemon.go
  pkg/ippoolmanager/ippool_mutate.go
  pkg/ippoolmanager/ippool_webhook_test.go
Labels: pr/release/none-required, pr/ready-review

#1291 improve IP GC long time lock keeping issue
  pkg/gcmanager/pod_cache.go
Labels: pr/release/none-required, pr/ready-review

#1314 fix: UT failed, but no issue was created
  .github/workflows/auto-nightly-ci.yaml
Labels: pr/release/none-required, pr/ready-review

#1304 E2E: Add E2E with SpiderSubnet supporting multiple interfaces, default subnets and third-party controllers.
  test/doc/assignip.md
  test/doc/cidr.md
  test/e2e/common/spiderpool.go
  test/e2e/common/spidersubnet.go
  test/e2e/kruise/kruise_test.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1305 refactor ippool informer
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/gcmanager/gc_manager.go
  pkg/ipam/ipam.go
  pkg/ippoolmanager/config.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/ippoolmanager/types/interface.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/none-required, pr/ready-review

#1293 [Docs] Add spidersubnet to mkdocs.yml
  docs/mkdocs.yml
  docs/usage/spider-subnet.md
Labels: pr/release/none-required

#1317 SpiderSubnet feature app operator refactor
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/metric/metrics_instance.go
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/controllers/controller.go
  pkg/subnetmanager/controllers/utils.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/none-required, pr/ready-review

#1301 E2E: Add comments, improve functionality and add some cases to e2e
  test/doc/assignip.md
  test/doc/cidr.md
  test/e2e/affinity/affinity_suite_test.go
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assiginip_suite_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/common/kruise.go
  test/e2e/common/spiderpool.go
  test/e2e/common/spidersubnet.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/kruise/kruise_test.go
  test/e2e/performance/performance_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_suite_test.go
  test/e2e/reliability/reliability_test.go
  test/e2e/reservedip/reservedip_test.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1335 fix: e2e failure to detect endpoint
  test/e2e/affinity/affinity_test.go
  test/e2e/common/spiderpool.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1334 aggreate orphan pod auto-created IPPools deletion operation with SpiderSubnet feature
  charts/spiderpool/templates/role.yaml
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/rbac.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/feature-new, pr/ready-review

#1332 ippool informer workqueue modify to decrease IPPool operation conflicts
  .github/.spelling
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/metric/README.md
  pkg/metric/metrics_instance.go
  pkg/metric/metrics_ipam.go
  pkg/metric/metrics_subnet.go
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/controllers/utils.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/feature-new, pr/ready-review

#1336 Refactor webhook
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  pkg/constant/k8s.go
  pkg/ip/utils.go
  pkg/ip/utils_test.go
  pkg/ippoolmanager/ippool_mutate.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go
  pkg/reservedipmanager/reservedip_mutate.go
  pkg/reservedipmanager/reservedip_validate.go
  pkg/reservedipmanager/reservedip_webhook_test.go
  pkg/subnetmanager/subnet_mutate.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook_test.go
Labels: pr/release/none-required, pr/ready-review

#1340 fix: Concurrently created deployments of the same name causing check events to fail.
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1342 fix: An incorrect GC occurred during IP allocation
  pkg/gcmanager/scanAll_IPPool.go
Labels: pr/release/bug, pr/ready-review

#1341 Add flag to IPsDiffSet, IPsDiffSet and IPsIntersectionSet to determine whether the IP addresses result set needs to be sorted
  pkg/ip/ip.go
  pkg/ip/ip_test.go
  pkg/ip/iprange.go
  pkg/ip/utils.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/subnetmanager/controllers/utils.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_validate.go
  test/e2e/common/spidersubnet.go
Labels: pr/release/none-required, pr/ready-review

#1338 doc
  .github/workflows/lint-markdown.yaml
  CODEOWNERS
  README-zh_CN.md
  README.md
Labels: pr/release/doc

#1349 Sync CIDR label in SpiderSubnet controller
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/none-required, pr/ready-review

#1357 doc: Update README-en
  README.md
Labels: pr/release/doc

#1346 modify ipam fetch subnet IPPool retry operation times and duration
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ipam/ipam.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/subnet_manager.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/feature-new, pr/ready-review

#1358 doc: Update README-en
  README.md
Labels: pr/release/doc

#1359 add metrics prefix and fix docs
  docs/concepts/metrics.md
  pkg/ipam/ipam.go
  pkg/metric/README.md
  pkg/metric/metrics.go
  pkg/metric/metrics_instance.go
  pkg/subnetmanager/app_controller.go
Labels: pr/release/bug, pr/ready-review

#1354 test: Add unit tests for SpiderSubnet controller
  go.mod
  go.sum
  pkg/election/mock/lease_election_mock.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_informer_test.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#1362 Adjust the burst and qps of the API server client of spiderpool-agent and spiderpool-controller
  cmd/spiderpool-agent/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool/cmd/command_delete.go
Labels: pr/release/none-required, pr/ready-review

#1364 Add the metrics of queue time and the count of conflicts when updating IPPool
  cmd/spiderpool-agent/cmd/ipam.go
  docs/concepts/metrics.md
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/metric/metrics_instance.go
  pkg/metric/metrics_ipam.go
Labels: pr/release/none-required, pr/ready-review

#1365 feat: Add filed `status.default` to the CRDs of SpiderSubnet and SpiderIPPool
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/zz_generated.deepcopy.go
Labels: pr/release/feature-new, pr/ready-review

#1371 robot update changelog with tag v0.3.7 to branch github_pages
  changelogs/v0.3.6-to-v0.3.7.md
Labels: pr/release/robot_update_githubpage

#1370 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.3.7.tgz
  docs/index.yaml
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: pr/release/robot_update_githubpage

#1374 robot update changelog with tag v0.4.0-rc2 to branch github_pages
  changelogs/changelog_from_v0.4.0-rc1_to_v0.4.0-rc2.md
Labels: pr/release/robot_update_githubpage

#1380 ut subnetmanager contorllers
  pkg/subnetmanager/controllers/controller_internal_test.go
  pkg/subnetmanager/controllers/controllers_suite_test.go
  pkg/subnetmanager/controllers/cronjob_informer_internal_test.go
  pkg/subnetmanager/controllers/daemonset_informer_internal_test.go
  pkg/subnetmanager/controllers/deployment_informer_internal_test.go
  pkg/subnetmanager/controllers/job_informer_internal_test.go
  pkg/subnetmanager/controllers/replicaset_informer_internal_test.go
  pkg/subnetmanager/controllers/statefulset_informer_internal_test.go
  pkg/subnetmanager/controllers/utils_internal_test.go
Labels: pr/release/none-required

#1343 unittest: Add ippoolmanager unit tests for pkg ippoolmanager
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_informer_test.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/ippoolmanager/ippool_manager_test.go
  pkg/ippoolmanager/mock/ippool_manager_mock.go
  pkg/ippoolmanager/utils_test.go
  pkg/reservedipmanager/mock/reservedip_manager_mock.go
  pkg/subnetmanager/mock/subnet_manager_mock.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  pkg/subnetmanager/subnet_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1377 feat: Add the 'status.default' column to the 'kubectl get' output of SpiderSubnet and SpiderIPPool
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go
Labels: pr/release/feature-new, pr/ready-review

#1386 fix the incorrect jump link address of the document
  docs/README.md
Labels: pr/release/none-required, pr/ready-review
