Repository spidernet-io/spiderpool, pull requests merged in 2023-01, with the labels that each got.

#1242 fix potential panic with SpiderSubnet feature
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.3

#1258 test: Add webhook unit tests for pkg ippoolmanager
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/ippoolmanager/ippool_mutate.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/ippoolmanager/types/interface.go
Labels: pr/release/none-required, pr/ready-review

#1260 auto-created IPPool podAffinity adjustment
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.3

#1254 fix default subnet generate ippool for non-spiderpool pod
  .github/.spelling
  cmd/spiderpool-agent/cmd/daemon.go
  docs/develop/upgrade.md
  pkg/constant/k8s.go
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/ipam/config.go
  pkg/ipam/ipam.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/podmanager/mock/pod_manager_mock.go
  pkg/podmanager/pod_manager.go
  pkg/statefulsetmanager/sts_manager.go
  pkg/statefulsetmanager/sts_manager_test.go
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/controllers/utils.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
  pkg/types/k8s.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
  test/e2e/kruise/kruise_test.go
Labels: pr/release/feature-new

#1270 subnet architecture adjustment
  docs/images/spider-subnet-architecture.png
  pkg/ipam/ipam.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/types/interface.go
  pkg/ippoolmanager/utils.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/none-required

#1269 fix potential panic with SpiderSubnet feature application pod selector
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/bug, pr/ready-review

#1255 fix: Patch reports an error version has changed
  test/e2e/common/spidersubnet.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1273 Refactor the informer code of SpiderSubnet
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/subnetmanager/app_controller.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/types/interface.go
Labels: pr/release/none-required, pr/ready-review
