Repository spidernet-io/spiderpool, pull requests merged in 2023-03, with the labels that each got.

#1378 optimized the order of import packages
  cmd/spiderpool/cmd/utils.go
  test/e2e/cli/cli_suite_test.go
  test/e2e/common/reservedip.go
  test/e2e/configmap/configmap_suite_test.go
  test/e2e/ippoolcr/ippoolcr_suite_test.go
  test/e2e/metric/metric_suite_test.go
  test/e2e/performance/performance_suite_test.go
Labels: pr/release/none-required, pr/ready-review

#1397 Revert/utcommit
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_informer_test.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/ippoolmanager/ippool_manager_test.go
  pkg/ippoolmanager/mock/ippool_manager_mock.go
  pkg/ippoolmanager/utils_test.go
  pkg/reservedipmanager/mock/reservedip_manager_mock.go
  pkg/subnetmanager/controllers/controller_internal_test.go
  pkg/subnetmanager/controllers/controllers_suite_test.go
  pkg/subnetmanager/controllers/cronjob_informer_internal_test.go
  pkg/subnetmanager/controllers/daemonset_informer_internal_test.go
  pkg/subnetmanager/controllers/deployment_informer_internal_test.go
  pkg/subnetmanager/controllers/job_informer_internal_test.go
  pkg/subnetmanager/controllers/replicaset_informer_internal_test.go
  pkg/subnetmanager/controllers/statefulset_informer_internal_test.go
  pkg/subnetmanager/controllers/utils_internal_test.go
  pkg/subnetmanager/mock/subnet_manager_mock.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  pkg/subnetmanager/subnet_manager_test.go
Labels: pr/release/none-required

#1399 Remove moby dependency
  go.mod
  go.sum
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
  vendor/github.com/moby/moby/AUTHORS
  vendor/github.com/moby/moby/LICENSE
  vendor/github.com/moby/moby/NOTICE
  vendor/github.com/moby/moby/pkg/stringid/README.md
  vendor/github.com/moby/moby/pkg/stringid/stringid.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#1400 Replace the timeout of CNI DEL's ctx to the deletion grace period of Pod
  pkg/ipam/release.go
Labels: pr/release/none-required, pr/ready-review

#1402 test: Add some unit tests for Endpoint manager and STS manager
  cmd/spiderpoolctl/cmd/command_root.go
  pkg/lock/lock_debug_test.go
  pkg/lock/lock_fast_test.go
  pkg/statefulsetmanager/sts_manager_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1403 Change `status.default` to `spec.default` in the CRDs of SpiderIPPool
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/zz_generated.deepcopy.go
Labels: pr/release/feature-new, pr/ready-review

#1413 Adjust some log messages and pkg structure
  cmd/spiderpool-agent/cmd/command_daemon.go
  cmd/spiderpool-agent/cmd/command_root.go
  cmd/spiderpool-agent/cmd/command_shutdown.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/command_daemon.go
  cmd/spiderpool-controller/cmd/command_root.go
  cmd/spiderpool-controller/cmd/command_shutdown.go
  cmd/spiderpool-controller/cmd/command_status.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpoolctl/cmd/command_root.go
  pkg/utils/cmdgenmd/cmd_generate_markdown.go
Labels: pr/release/none-required, pr/ready-review

#1414 Refactor spiderpool-init
  cmd/spiderpool-init/cmd/client.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/k8s.go
  cmd/spiderpool-init/cmd/root.go
Labels: pr/release/none-required, pr/ready-review

#1417 fix: Pod UID is an empty string when calling CNI DEL
  cmd/spiderpool-agent/cmd/ipam.go
  pkg/ipam/release.go
Labels: pr/release/bug, pr/ready-review

#1416 Adjust most fields of SpiderEndpoit CRD as required
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  pkg/ipam/allocate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderendpoint_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/zz_generated.deepcopy.go
  pkg/workloadendpointmanager/utils.go
  pkg/workloadendpointmanager/utils_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1418 feat: Use `spec.default` to make the cluster default IPPools effective instead of configuring Comfigmap spiderpool-conf
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/crd_manager.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-init/cmd/root.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
  pkg/constant/k8s.go
  pkg/ipam/allocate.go
  pkg/ipam/config.go
  pkg/ipam/ipam.go
  pkg/ipam/pool_selections.go
  pkg/ipam/release.go
  pkg/ipam/types.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/ippoolmanager/ippool_mutate.go
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderendpoint_types.go
  pkg/namespacemanager/namespace_manager.go
  pkg/namespacemanager/namespace_manager_suite_test.go
  pkg/namespacemanager/namespace_manager_test.go
  pkg/nodemanager/node_manager.go
  pkg/nodemanager/node_manager_suite_test.go
  pkg/nodemanager/node_manager_test.go
  pkg/podmanager/config.go
  pkg/podmanager/pod_manager.go
  pkg/podmanager/pod_manager_suite_test.go
  pkg/podmanager/pod_manager_test.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/reservedipmanager/reservedip_manager_suite_test.go
  pkg/reservedipmanager/reservedip_manager_test.go
  pkg/reservedipmanager/reservedip_webhook.go
  pkg/reservedipmanager/reservedip_webhook_test.go
  pkg/statefulsetmanager/sts_manager.go
  pkg/statefulsetmanager/sts_manager_suite_test.go
  pkg/statefulsetmanager/sts_manager_test.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_informer_test.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook.go
  pkg/subnetmanager/subnet_webhook_test.go
  pkg/workloadendpointmanager/config.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_suite_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
Labels: pr/release/feature-new, pr/ready-review

#1421 Add validation for `spec.default` in the webhook of SpiderSubnet and
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook_test.go
Labels: pr/release/feature-new, pr/ready-review

#1422 IP garbage collection
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/pod_informer.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/ipam/release.go
  pkg/statefulsetmanager/sts_manager.go
  pkg/statefulsetmanager/sts_manager_test.go
Labels: pr/release/feature-new, pr/ready-review

#1424 IP garbage collection
  pkg/gcmanager/scanAll_IPPool.go
Labels: pr/release/feature-new, pr/ready-review

#1425 fix: The IP allocation of Endpoint is incomplete in multi-NIC mode
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  pkg/ipam/allocate.go
  pkg/ipam/release.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderendpoint_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
  pkg/utils/convert/convert.go
  pkg/workloadendpointmanager/utils.go
  pkg/workloadendpointmanager/utils_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
Labels: pr/release/bug, pr/ready-review

#1427 Add retry util for conflict retry
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/config.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/subnetmanager/config.go
  pkg/subnetmanager/subnet_manager.go
  pkg/utils/retry/retry.go
  pkg/workloadendpointmanager/config.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_suite_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1434 refactor SpiderSubnet feature
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/applicationinformers/controller.go
  pkg/applicationcontroller/applicationinformers/cronjob_informer.go
  pkg/applicationcontroller/applicationinformers/daemonset_informer.go
  pkg/applicationcontroller/applicationinformers/deployment_informer.go
  pkg/applicationcontroller/applicationinformers/job_informer.go
  pkg/applicationcontroller/applicationinformers/replicaset_informer.go
  pkg/applicationcontroller/applicationinformers/statefulset_informer.go
  pkg/applicationcontroller/applicationinformers/utils.go
  pkg/constant/errors.go
  pkg/constant/k8s.go
  pkg/gcmanager/pod_cache.go
  pkg/ipam/allocate.go
  pkg/ipam/pool_selections.go
  pkg/ipam/release.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/utils.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/zz_generated.deepcopy.go
  pkg/podmanager/utils.go
  pkg/podmanager/utils_test.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_informer_test.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook_test.go
  pkg/types/k8s.go
  pkg/utils/convert/convert.go
  test/e2e/reclaim/reclaim_test.go
Labels: pr/release/feature-new, pr/ready-review

#1435 Refactor Subnet Controller
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ipam/allocate.go
  pkg/ipam/pool_selections.go
  pkg/ipam/release.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/utils.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spidersubnet_types.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_informer_test.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook_test.go
  pkg/utils/convert/convert.go
  test/e2e/reclaim/reclaim_test.go
Labels: pr/release/none-required, pr/ready-review

#1437 feat: Add queuer timeout mechanism based on context for pkg limiter
  pkg/limiter/queue.go
  pkg/limiter/queue_test.go
Labels: pr/release/feature-new, pr/ready-review

#1440 test: Add field index to fake client
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/namespacemanager/namespace_manager_suite_test.go
  pkg/nodemanager/node_manager_suite_test.go
  pkg/podmanager/pod_manager_suite_test.go
  pkg/reservedipmanager/reservedip_manager_suite_test.go
  pkg/statefulsetmanager/sts_manager_suite_test.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager_suite_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1441 [unit tests] pod mananger unit test
  pkg/constant/k8s.go
  pkg/ipam/pool_selections.go
  pkg/ipam/utils.go
  pkg/podmanager/pod_manager.go
  pkg/podmanager/pod_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1442 Aggregate the namespace and name field in `status.allocatedIPs` of SpiderIPPool into 'namespaced name'
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  pkg/gcmanager/scanAll_IPPool.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderendpoint_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/types_string.go
  pkg/k8s/apis/spiderpool.spidernet.io/v1/zz_generated.deepcopy.go
  pkg/k8s/client/clientset/versioned/clientset.go
  pkg/k8s/client/informers/externalversions/factory.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
Labels: pr/release/none-required, pr/ready-review

#1447 Change the request path of webhook from v1 to v2beta1
  charts/spiderpool/templates/tls.yaml
Labels: pr/release/none-required, pr/ready-review

#1450 fix: Field `status.allocatedIPCount` is empty instead of 0
  pkg/ippoolmanager/ippool_manager.go
  pkg/utils/convert/convert.go
Labels: pr/release/none-required, pr/ready-review

#1452 fix: The Pod UID of the record in the SpiderIPPool is not updated after the StatefulSet's Pod is recreated
  pkg/ippoolmanager/ippool_manager.go
Labels: pr/release/none-required, pr/ready-review

#1453 fix: In the case of IPv6 only, the default IPv6 SpiderSubnet or SpiderIPPool is not created
  cmd/spiderpool-init/cmd/config.go
Labels: pr/release/none-required, pr/ready-review

#1454 Pending for e2e, facilitating the release of new versions
  .github/workflows/e2e-init.yaml
  test/e2e/e2e_test/e2e_test_suite_test.go
Labels: pr/release/none-required, pr/ready-review

#1456 Bump spiderpool from v0.4.0-rc2 -> v0.4.0-rc3
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#1459 Resolve conflicts caused by merge main
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#1468 robot update changelog with tag v0.4.0-rc3 to branch github_pages
  changelogs/changelog_from_v0.4.0-rc2_to_v0.4.0-rc3.md
Labels: pr/release/robot_update_githubpage

#1467 robot update chart and website from to branch github_pages
  docs/charts/spiderpool-0.4.0-rc3.tgz
  docs/example/basic/custom-ipv4-ippool.yaml
  docs/example/ippool-affinity-node/master-ipv4-ippool.yaml
  docs/example/ippool-affinity-node/worker-ipv4-ippool.yaml
  docs/example/ippool-affinity-pod/static-ipv4-ippool.yaml
  docs/example/ippool-affnity-namespace/test-ns-ipv4-ippool.yaml
  docs/example/ippool-multi/test-ipv4-ippools.yaml
  docs/example/ippool-namespace/ns1-default-ipv4-ippool.yaml
  docs/example/multi-interfaces-annotation/different-segment-ipv4-ippools.yaml
  docs/example/reserved-ip/already-in-use-ippool.yaml
  docs/example/reserved-ip/created-by-someone-else-ippool.yaml
  docs/example/reserved-ip/not-use-excludeips-ippool.yaml
  docs/example/reserved-ip/test-ipv4-ippool.yaml
  docs/example/reserved-ip/test-ipv4-reservedip.yaml
  docs/example/reserved-ip/use-excludeips-ippool.yaml
  docs/example/spider-subnet/multiple-interfaces.yaml
  docs/example/spider-subnet/subnet-demo.yaml
  docs/index.html
  docs/index.yaml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/basic/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/spider-subnet/index.html
  docs/usage/third-party-controller/index.html
Labels: pr/release/robot_update_githubpage

#1472 test: Add unit tests for SubnetManager
  pkg/reservedipmanager/mock/reservedip_manager_mock.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  pkg/subnetmanager/subnet_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1479 feat: Remove field `spec.status` from SpiderSubnet CRD
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  cmd/spiderpool-agent/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-init/cmd/root.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidersubnet_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook_test.go
Labels: pr/release/feature-new, pr/ready-review

#1480 fix application controller empty APIVersion string
  pkg/applicationcontroller/app_controller.go
Labels: pr/release/bug, pr/ready-review

#1485 Add config file .trivyignore and filter vulnerability AVD-KSV-0046
  .trivyignore
  CODEOWNERS
  Makefile
Labels: pr/release/none-required, pr/ready-review

#1476 add apiversion check for statefulset pod
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/applicationinformers/utils.go
  pkg/constant/k8s.go
  pkg/ipam/allocate.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/utils.go
  pkg/podmanager/pod_manager.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/bug, pr/ready-review

#1489 test: Add unit tests for IPPoolManager
  pkg/ipam/release.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/ippoolmanager/ippool_manager_test.go
  pkg/subnetmanager/subnet_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1492 fix: The field deletionGracePeriodSeconds of Pod may be nil in K8s <=1.22
  pkg/ipam/release.go
Labels: pr/release/bug, pr/ready-review

#1496 remove cluster default subnet source codes
  pkg/applicationcontroller/applicationinformers/utils.go
  pkg/ipam/pool_selections.go
  pkg/ipam/utils.go
  pkg/singletons/singleton.go
  pkg/types/k8s.go
Labels: pr/release/none-required, pr/ready-review

#1503 e2e test case for releasing a statefulset controlled by a third party
  pkg/ipam/pool_selections.go
  test/e2e/kruise/kruise_test.go
Labels: pr/release/none-required, pr/ready-review

#1504 decrease auto-created ippool name
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/applicationinformers/utils.go
  pkg/ipam/pool_selections.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/feature-new, pr/ready-review

#1484 Update the Kubernetes version of spiderpool e2e to 1.26.x
  test/Makefile.defs
Labels: pr/release/none-required, pr/ready-review

#1390 update the crd description document entry
  docs/concepts/arch.md
Labels: pr/release/none-required, pr/ready-review

#1348 doc: add overview & optimize quick start
  docs/README.md
  docs/mkdocs.yml
  docs/usage/basic.md
  docs/usage/install.md
Labels: pr/release/none-required, pr/ready-review

#1392 Optimize some of the instructions in the documentation
  README.md
  docs/usage/basic.md
Labels: pr/release/none-required, pr/ready-review

#1505 metrics adjustment
  docs/concepts/metrics.md
  pkg/ipam/pool_selections.go
  pkg/metric/metrics_instance.go
  pkg/metric/metrics_ipam.go
  pkg/metric/metrics_subnet.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/feature-new, pr/ready-review

#1506 change statefulset pod validation
  pkg/statefulsetmanager/sts_manager.go
  pkg/statefulsetmanager/sts_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1507 Bump Spiderpool form v0.4.0-rc3 -> v0.4.0-rc4
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#1509 robot update chart and website from to branch github_pages
  docs/404.html
  docs/charts/spiderpool-0.4.0-rc4.tgz
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/metrics/index.html
  docs/concepts/roadmap/index.html
  docs/concepts/spiderendpoint/index.html
  docs/concepts/spiderippool/index.html
  docs/concepts/spiderreservedip/index.html
  docs/concepts/spidersubnet/index.html
  docs/develop/changelog/index.html
  docs/develop/pullrequest/index.html
  docs/develop/release/index.html
  docs/develop/swagger_openapi/index.html
  docs/develop/test/index.html
  docs/develop/upgrade/index.html
  docs/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/basic/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namespace/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/multi-interfaces-cni/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/spider-subnet/index.html
  docs/usage/statefulset/index.html
  docs/usage/third-party-controller/index.html
Labels: pr/release/robot_update_githubpage

#1510 robot update changelog with tag v0.4.0-rc4 to branch github_pages
  changelogs/changelog_from_v0.4.0-rc3_to_v0.4.0-rc4.md
Labels: pr/release/robot_update_githubpage

#1512 fix IP GC scan all not work issue
  pkg/gcmanager/scanAll_IPPool.go
Labels: pr/release/bug, pr/ready-review

#1513 fix: Limiter may deadlock when the queuer's ctx is about to deadline
  pkg/limiter/queue.go
  pkg/limiter/queue_test.go
Labels: pr/release/bug, pr/ready-review

#1519 fix: SubnetInformer executes SYNC too many times
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/bug, pr/ready-review

#1517 improve IP GC pod informer startup
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/pod_informer.go
Labels: pr/release/bug, pr/ready-review

#1521 fix helm IP GC env varibale
  .github/.spelling
  charts/spiderpool/templates/deployment.yaml
  cmd/spiderpool-controller/cmd/config.go
  docs/cmdref/spiderpool-controller.md
Labels: pr/release/bug, pr/ready-review

#1518 fix auto-pool shrink failure issue
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/applicationcontroller/app_controller.go
  pkg/ipam/pool_selections.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/bug, pr/ready-review

#1524 Enable feature SpiderSubnet by default
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: pr/release/none-required, pr/ready-review

#1523 Patch instead of updating the finalizer of SpiderEndpoint
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/ipam/release.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1525 modify default IP GC workers and make IP GC scan all dual stack concurrency
  cmd/spiderpool-controller/cmd/config.go
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/scanAll_IPPool.go
Labels: pr/release/feature-new, pr/ready-review

#1394 add quick start doc for macvlan
  docs/usage/get-started-macvlan-zh_CN.md
Labels: pr/ready-review, kind/documentation

#1526 fix: Subnet status IPPool allocations disappears but the IPPool still exist
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/bug, pr/ready-review

#1531 supplement spiderpool controller readiness probe
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-controller/cmd/runtime_status.go
  pkg/election/lease_election.go
  pkg/election/lease_election_test.go
  pkg/election/mock/lease_election_mock.go
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/pod_informer.go
Labels: pr/release/feature-new, pr/ready-review

#1541 [unit tests] supplement application controller unit tests
  pkg/applicationcontroller/applicationinformers/applicationinformers_suite_test.go
  pkg/applicationcontroller/applicationinformers/controller_test.go
  pkg/applicationcontroller/applicationinformers/cronjob_informer_test.go
  pkg/applicationcontroller/applicationinformers/daemonset_informer_test.go
  pkg/applicationcontroller/applicationinformers/deployment_informer_test.go
  pkg/applicationcontroller/applicationinformers/job_informer_test.go
  pkg/applicationcontroller/applicationinformers/replicaset_informer_test.go
  pkg/applicationcontroller/applicationinformers/statefulset_informer_test.go
  pkg/applicationcontroller/applicationinformers/utils_test.go
Labels: pr/release/none-required, pr/ready-review

#1542 improve statrup
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
Labels: pr/release/feature-new, pr/ready-review

#1532 add limiter for IP GC pod informer architecture
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/tracePod_worker.go
Labels: pr/release/feature-new, pr/ready-review

#1548 modify spiderpool-controller leader election env configuration
  cmd/spiderpool-controller/cmd/config.go
Labels: pr/release/none-required, pr/ready-review

#1549 support CNI V1.0.0
  cmd/spiderpool/cmd/cni_types.go
Labels: pr/release/feature-new, pr/ready-review

#1395 docs : add sriov get started
  docs/usage/get-started-sriov-zh_CN.md
Labels: kind/documentation

#1551 Adjust the parameters of the probe
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/deployment.yaml
Labels: pr/release/none-required, pr/ready-review

#1552 Remove deprecated Ginkgo flag `--slow-spec-threshold`
  Makefile
Labels: pr/release/none-required, pr/ready-review

#1451 docs: spiderpool supports calico in bgp mode
  docs/images/calico-bgp.svg
  docs/usage/calico-spiderpool.md
  docs/usage/weave-spiderpool.md
Labels: kind/documentation

#1538 docs: Add docs for performance testing
  docs/usage/performance-zh_CH.md
Labels: pr/release/doc, pr/ready-review, kind/documentation

#1564 [unit test] supplement application controller unit test
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/app_controller_test.go
  pkg/applicationcontroller/applicationcontroller_suite_test.go
Labels: pr/release/none-required, pr/ready-review

#1539 supplement SpiderSubnet usage document
  docs/example/spider-subnet/cluster-default-subnet-deployment.yaml
  docs/usage/spider-subnet.md
  docs/usage/third-party-controller.md
Labels: pr/release/doc, pr/ready-review, kind/documentation

#1565 add translation for get-started-calico
  docs/usage/get-started-calico-zh_CN.md
  docs/usage/get-started-calico.md
Labels: pr/release/doc, kind/documentation, sig/docs

#1569 docs: Add docs performance.md
  docs/usage/performance-zh_CH.md
  docs/usage/performance.md
Labels: pr/release/doc, pr/ready-review, kind/documentation

#1571 docs: add share ippool get started
  docs/example/ippool-affinity-pod/occupied-static-ippool-deploy.yaml
  docs/example/ippool-affinity-pod/occupied-static-ipv4-ippool.yaml
  docs/example/ippool-affinity-pod/shared-static-ippool-deploy.yaml
  docs/example/ippool-affinity-pod/shared-static-ipv4-ippool.yaml
  docs/example/ippool-affinity-pod/static-ipv4-subnet.yaml
  docs/usage/ippool-affinity-pod.md
Labels: pr/release/doc, kind/documentation

#1577 test: Add some unit tests for IPPoolManager
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/ippoolmanager/ippool_manager_test.go
Labels: pr/release/none-required, pr/ready-review

#1576 improve IP GC document
  docs/concepts/gc.md
  docs/usage/gc.md
  pkg/gcmanager/README.md
Labels: pr/release/doc, pr/ready-review, kind/documentation

#1580 Bump Spiderpool from v0.4.0-rc4 to v0.4.0
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#1588 Fixing ambiguous aliases
  test/e2e/affinity/affinity_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/performance/performance_test.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required, pr/ready-review

#1590 [doc] update nav list
  docs/mkdocs.yml
Labels: pr/release/doc, kind/documentation

#1591 make IP GC pod informer mechanism requeue if it failed to release IP
  cmd/spiderpool-controller/cmd/config.go
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/pod_informer.go
  pkg/gcmanager/tracePod_worker.go
Labels: pr/release/feature-new, pr/ready-review

#1589 improve e2e test log
  test/e2e/performance/performance_test.go
Labels: pr/release/none-required, pr/ready-review

#1594 update en readme
  README-zh_CN.md
  README.md
Labels: pr/release/doc, kind/documentation
