Repository spidernet-io/spiderpool, pull requests merged in 2023-08, with the labels that each got.

#2118 docs fix: update busybox to nginx
  docs/usage/install/cloud/get-started-alibaba-zh_CN.md
Labels: pr/release/none-required, pr/ready-review

#2123 update sriov get-started and coordinator docs
  docs/usage/coordinator-zh_CN.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-sriov.md
Labels: pr/release/none-required

#2126 optimize the coordinator log
  cmd/coordinator/cmd/utils.go
Labels: pr/release/none-required

#2131 fix:Missing resource type in cleanCRD scripts
  tools/scripts/cleanCRD.sh
Labels: pr/release/bug, pr/ready-review

#2119 e2e fix: use api to abbreviate ipv6 addresses and fix subnet creation failure due to duplicate names
  test/e2e/annotation/annotation_test.go
  test/e2e/common/spiderpool.go
  test/e2e/common/spidersubnet.go
Labels: pr/release/none-required, pr/ready-review

#2138 e2e docs: add new e2e case for spiderpool
  test/doc/annotation.md
  test/doc/ippoolcr.md
  test/doc/metric.md
  test/doc/spidermultus.md
Labels: pr/release/none-required, pr/ready-review, kind/documentation

#2137 docs: update get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
Labels: pr/release/none-required

#2139 docs: update coordinator-zh_CN.md
  docs/reference/crd-spidercoordinator.md
  docs/usage/coordinator-zh_CN.md
Labels: pr/release/none-required

#2148 coordinator: fix failed to setupHijackRoutes
  cmd/coordinator/cmd/utils.go
Labels: pr/release/bug, cherrypick-release-v0.6

#2046 update some outdated documentation
  README-zh_CN.md
  docs/README-zh_CN.md
  docs/concepts/performance-zh_CN.md
  docs/concepts/performance.md
  docs/images/ip-allocation-across-networks-1.png
  docs/images/ip-allocation-across-networks-2.png
  docs/usage/_feature_example_zh.md
  docs/usage/_install_example_zh.md
  docs/usage/gc-zh_CN.md
  docs/usage/gc.md
  docs/usage/install/install-zh_CN.md
  docs/usage/install/install.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-calico-zh_CN.md
  docs/usage/install/underlay/get-started-calico.md
  docs/usage/install/underlay/get-started-kind-zh_CN.md
  docs/usage/install/underlay/get-started-kind.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/install/underlay/get-started-weave-zh_CN.md
  docs/usage/install/underlay/get-started-weave.md
  docs/usage/ippool-affinity-namespace.md
  docs/usage/ippool-affinity-node.md
  docs/usage/ippool-affinity-pod.md
  docs/usage/ippool-multi.md
  docs/usage/ippool-namespace.md
  docs/usage/ipv6.md
  docs/usage/multi-interfaces-annotation.md
  docs/usage/network-topology-zh_CN.md
  docs/usage/network-topology.md
  docs/usage/reserved-ip.md
  docs/usage/route.md
  docs/usage/spider-subnet.md
  docs/usage/third-party-controller.md
  test/Makefile.defs
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.6

#2147 e2e: add use case for changing multus properties via spidermultus annotation
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: pr/release/none-required, pr/ready-review

#2152 clean up spidercoordinator.status if phase is NotReady
  cmd/spiderpool-agent/cmd/coordinator.go
  pkg/coordinatormanager/calico_ippool_informer.go
  pkg/coordinatormanager/coordinator_informer.go
Labels: pr/release/bug, cherrypick-release-v0.6

#2149 title: coordinator: fix failed to setupHijackRoutes
  cmd/coordinator/cmd/utils.go
Labels: robot-cherrypick

#2140 spidermultusconfig: remove redundant field "resourceName"
  pkg/multuscniconfig/utils.go
  test/doc/spidermultus.md
Labels: pr/release/bug, cherrypick-release-v0.6

#2150 title: update some outdated documentation
  README-zh_CN.md
  docs/README-zh_CN.md
  docs/concepts/performance-zh_CN.md
  docs/concepts/performance.md
  docs/images/ip-allocation-across-networks-1.png
  docs/images/ip-allocation-across-networks-2.png
  docs/usage/_feature_example_zh.md
  docs/usage/_install_example_zh.md
  docs/usage/gc-zh_CN.md
  docs/usage/gc.md
  docs/usage/install/install-zh_CN.md
  docs/usage/install/install.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-calico-zh_CN.md
  docs/usage/install/underlay/get-started-calico.md
  docs/usage/install/underlay/get-started-kind-zh_CN.md
  docs/usage/install/underlay/get-started-kind.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/install/underlay/get-started-weave-zh_CN.md
  docs/usage/install/underlay/get-started-weave.md
  docs/usage/ippool-affinity-namespace.md
  docs/usage/ippool-affinity-node.md
  docs/usage/ippool-affinity-pod.md
  docs/usage/ippool-multi.md
  docs/usage/ippool-namespace.md
  docs/usage/ipv6.md
  docs/usage/multi-interfaces-annotation.md
  docs/usage/network-topology-zh_CN.md
  docs/usage/network-topology.md
  docs/usage/reserved-ip.md
  docs/usage/route.md
  docs/usage/spider-subnet.md
  docs/usage/third-party-controller.md
  test/Makefile.defs
Labels: pr/release/doc, robot-cherrypick

#2141 spidercoordinator: support setting podCIDRType to none
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  docs/reference/crd-spidercoordinator.md
  pkg/coordinatormanager/coordinator_informer.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  test/doc/coordinator.md
Labels: pr/release/feature-new

#2158 typo: make spidercoordinator.status.phase uppercase
  pkg/coordinatormanager/coordinator_informer.go
Labels: pr/release/none-required

#2160 fix wrong SpiderEndpoint vlan ID number
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  docs/reference/crd-spidermultusconfig.md
  docs/reference/crd-spidersubnet.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderendpoint_types.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.6

#2155 title: clean up spidercoordinator.status if phase is NotReady
  cmd/spiderpool-agent/cmd/coordinator.go
  pkg/coordinatormanager/calico_ippool_informer.go
  pkg/coordinatormanager/coordinator_informer.go
Labels: pr/release/bug, robot-cherrypick

#2153 spidermultusconfig: validate customcniconfig if is valid
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_validate.go
  test/doc/spidermultus.md
Labels: pr/release/bug, cherrypick-release-v0.6

#2166 title: fix wrong SpiderEndpoint vlan ID number
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  docs/reference/crd-spidermultusconfig.md
  docs/reference/crd-spidersubnet.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderendpoint_types.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/bug, robot-cherrypick

#2136 add new blog for spiderpool
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: pr/release/none-required, pr/ready-review, kind/documentation

#2164 add clean for CI
  .github/workflows/e2e-init.yaml
  Makefile
  test/Makefile
Labels: pr/release/none-required, pr/ready-review

#2172 fix potential panic with CRD string method
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/types_string.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.6

#2180 fix ci cleanup script
  test/Makefile
Labels: pr/release/none-required, pr/ready-review

#2179 title: fix potential panic with CRD string method
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/types_string.go
Labels: pr/release/bug, robot-cherrypick

#2177 optimize the autopool name length to 253
  pkg/applicationcontroller/applicationinformers/utils.go
Labels: pr/release/none-required, pr/ready-review, enhancement, cherrypick-release-v0.6

#2184 doc: add en get-started-alibaba
  docs/usage/install/cloud/get-started-alibaba-zh_CN.md
  docs/usage/install/cloud/get-started-alibaba.md
Labels: pr/release/doc, kind/documentation

#2181 title: optimize the autopool name length to 253
  pkg/applicationcontroller/applicationinformers/utils.go
Labels: pr/release/bug, robot-cherrypick

#2157 new features e2e supplement
  test/doc/assignip.md
  test/doc/coordinator.md
  test/doc/ifacer.md
  test/doc/ippoolcr.md
  test/doc/spidercoodinator.md
  test/doc/spidermultus.md
Labels: pr/release/none-required, kind/test

#2190 update readme
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: pr/release/none-required

#2195 e2e: add spiderpool controller active/standby
  test/doc/reliability.md
Labels: pr/release/none-required, kind/documentation, kind/test

#2170 add SpiderMultusConfig annotation validation in webhook
  docs/mkdocs.yml
  docs/reference/crd-spidermultusconfig.md
  docs/usage/spider-multus-config.md
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/multusconfig_webhook.go
  test/e2e/spidermultus/spidermultus_test.go
Labels: pr/release/feature-new, pr/ready-review, enhancement

#2178 coordinator: auto mode is supported
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/README.md
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  charts/spiderpool/values.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/command_del.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-agent/cmd/coordinator.go
  cmd/spiderpool-init/cmd/config.go
  docs/reference/crd-spidercoordinator.md
  docs/usage/coordinator-zh_CN.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/networking/networking/route.go
  test/Makefile
  test/Makefile.defs
  test/e2e/annotation/annotation_test.go
  test/e2e/common/constant.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/subnet/subnet_test.go
  test/scripts/debugEnv.sh
  test/scripts/install-multus.sh
Labels: pr/release/feature-new

#2198 doc: add en get-started-calico
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
Labels: pr/release/doc, kind/documentation

#2196 fix IP overlap that occurs with low probability
  test/e2e/common/ips.go
  test/e2e/common/spiderpool.go
  test/e2e/common/spidersubnet.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/scripts/debugEnv.sh
Labels: pr/release/none-required, pr/ready-review

#2203 add spidermultus e2e for spiderpool
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: pr/release/none-required, pr/ready-review

#2205 single IP support in dual stack with SpiderSubnet feature
  pkg/ipam/pool_selections.go
Labels: pr/release/feature-new, pr/ready-review

#2209 Update install-zh_CN.md
  docs/usage/install/install-zh_CN.md
Labels: pr/release/none-required

#2211 doc: add en get-started -cilium
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
Labels: pr/release/doc, kind/documentation

#2185 feature : SpiderSubnet could take over orphan IPPool
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-license.yaml
  Makefile
  docs/develop/contributing.md
  docs/usage/install/underlay/get-started-kind-zh_CN.md
  docs/usage/install/underlay/get-started-kind.md
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_informer_test.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook_test.go
  test/Makefile.defs
  test/doc/subnet.md
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: pr/release/feature-new, pr/ready-review

#2214 orphan pod skip SpiderSubnet feature
  pkg/ipam/pool_selections.go
Labels: pr/release/bug, pr/ready-review

#2207 optimize IPAM pool selections
  docs/concepts/allocation.md
  pkg/ipam/allocate.go
  pkg/ippoolmanager/utils.go
  pkg/ippoolmanager/utils_test.go
  test/doc/annotation.md
  test/e2e/annotation/annotation_test.go
Labels: pr/release/feature-new, pr/ready-review

#2199 spidermultusconfig: ovs cni config supported
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/ifacer/cmd/types.go
  docs/reference/crd-spidermultusconfig.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  pkg/constant/k8s.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/utils.go
  test/doc/spidermultus.md
  test/scripts/install-multus.sh
Labels: pr/release/feature-new, kind/feature

#2225 fix SpiderMultusConfig potential panic
  pkg/multuscniconfig/multusconfig_informer.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.6

#2192 [docs]: add some usage of spiderpool
  docs/usage/network-topology-zh_CN.md
  docs/usage/spider-subnet-zh_CN.md
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.6

#2229 fix SpiderMultusConfig potential panic
  pkg/multuscniconfig/multusconfig_informer.go
Labels: pr/release/bug, robot-cherrypick

#2206 coordinator: make all host rule tables exists in table 500
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  docs/mkdocs.yml
  docs/reference/plugin-coordinator.md
  pkg/networking/networking/route.go
  test/doc/coordinator.md
Labels: pr/release/bug, cherrypick-release-v0.6

#2222 e2e: add spidermultusconfig e2e for spiderpool
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: pr/release/none-required, pr/ready-review

#2230 add multus pre-stop to remove multus CNI configuration
  charts/spiderpool/README.md
  charts/spiderpool/templates/multus-daemonset.yaml
  charts/spiderpool/values.yaml
Labels: pr/release/none-required, pr/ready-review, enhancement

#2243 e2e docs changes
  test/doc/coordinator.md
  test/doc/ifacer.md
  test/doc/ippoolcr.md
  test/doc/spidermultus.md
Labels: pr/release/none-required, pr/ready-review

#2244 update some e2e
  test/doc/ifacer.md
  test/doc/subnet.md
Labels: pr/release/none-required, pr/ready-review

#2217 support multiple versions of documents
  .github/workflows/call-release-doc.yaml
  docs/mkdocs.yml
  docs/overrides/main.html
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.6

#2249 support multiple versions of documents
  .github/workflows/call-release-doc.yaml
  docs/mkdocs.yml
  docs/overrides/main.html
Labels: pr/release/doc, robot-cherrypick, kind/documentation

#2253 typo
  .github/workflows/call-release-doc.yaml
Labels: pr/ready-review, cherrypick-release-v0.6

#2254 typo
  .github/workflows/call-release-doc.yaml
Labels: robot-cherrypick

#2256 v0.6.1
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#2259 fix docs logs
  .github/workflows/call-release-doc.yaml
Labels: pr/release/doc, cherrypick-release-v0.6

#2260 fix token
  .github/workflows/call-release-doc.yaml
Labels: pr/release/doc, cherrypick-release-v0.6

#2264 Use mike to construct the version, no artifact exists
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-update-githubpages.yaml
Labels: pr/release/doc, cherrypick-release-v0.6

#2265 Use mike to construct the version, no artifact exists
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-update-githubpages.yaml
Labels: pr/release/doc, release-v0.6

#2270 fix bug
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
Labels: pr/release/doc, pr/ready-review, release-v0.6

#2271 fix bug
  .github/workflows/call-release-doc.yaml
Labels: pr/release/doc, release-v0.6

#2274 fix incorrect packaging
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
Labels: pr/release/doc, release-v0.6

#2276 CI: fix invalid path
  .github/workflows/call-release-doc.yaml
Labels: pr/release/doc, release-v0.6

#2277 robot update changelog with tag v0.6.1 to branch github_pages
  changelogs/changelog_from_v0.6.0_to_v0.6.1.md
Labels: pr/release/robot_update_githubpage

#2279 Fix automatic publishing document version failure
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
  docs/mkdocs.yml
Labels: pr/release/doc

#2280 rebase main
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
  docs/mkdocs.yml
  docs/overrides/main.html
Labels: pr/release/none-required, pr/ready-review

#2284 fix coordinator webhook
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  cmd/spiderpool-agent/cmd/coordinator.go
  pkg/coordinatormanager/coordinator_validate.go
Labels: pr/release/none-required, pr/ready-review, kind/bug, cherrypick-release-v0.7
