Repository spidernet-io/spiderpool, pull requests merged in 2023-06, with the labels that each got.

#1856 fix coordinator disable failure
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.6

#1858 sync usage/gc.md
  docs/usage/gc-zh_CN.md
  docs/usage/gc.md
Labels: pr/release/none-required

#1866 improve log print
  pkg/gcmanager/scanAll_IPPool.go
  pkg/ipam/release.go
  pkg/ippoolmanager/ippool_informer.go
Labels: pr/release/none-required, enhancement, cherrypick-release-v0.6

#1867 e2e fix: gcAll field is incorrect
  test/Makefile
Labels: pr/release/none-required, pr/ready-review

#1880 update lock detect SelfishThresholdSec duration to 0.5 seconds
  pkg/lock/lock_debug.go
Labels: pr/release/none-required, pr/ready-review, enhancement

#1883 fix IP GC scan all running unhealthy
  pkg/gcmanager/scanAll_IPPool.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.5, cherrypick-release-v0.6

#1893 title: fix IP GC scan all running unhealthy
  pkg/gcmanager/scanAll_IPPool.go
Labels: pr/release/bug, robot-cherrypick

#1895 fix: binary absolute path for image command
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: pr/release/bug, cherrypick-release-v0.4, cherrypick-release-v0.5

#1896 title: fix: binary absolute path for image command
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: pr/release/bug, robot-cherrypick

#1897 title: fix: binary absolute path for image command
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: pr/release/bug, robot-cherrypick

#1898 fix: binary absolute path for image command
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: pr/release/none-required, cherrypick-release-v0.4, cherrypick-release-v0.5

#1900 title: fix: binary absolute path for image command
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: pr/release/bug, robot-cherrypick

#1899 title: fix: binary absolute path for image command
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: pr/release/bug, robot-cherrypick

#1914 support multiple default ippools
  .github/codespell-ignorewords
  docs/images/network-topology.png
  docs/usage/network-topology.md
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
Labels: pr/release/feature-new, pr/ready-review, cherrypick-release-v0.6

#1909 fix spiderpool-controller startup potential datarace
  Makefile
  cmd/spiderpool-controller/cmd/daemon.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.5, cherrypick-release-v0.6

#1918 support multiple default ippools
  .github/codespell-ignorewords
  docs/images/network-topology.png
  docs/usage/network-topology.md
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
Labels: pr/release/feature-new, robot-cherrypick

#1927 e2e fix: increase pod startup time
  test/e2e/common/constant.go
Labels: pr/release/none-required, pr/ready-review

#1906 IP-GC improvement with discarding tracing hostnetwork pod
  pkg/gcmanager/pod_cache.go
Labels: pr/release/none-required, pr/ready-review, enhancement, cherrypick-release-v0.6

#1930 IP-GG: discarding tracing hostnetwork pod
  pkg/gcmanager/pod_cache.go
Labels: robot-cherrypick

#1910 e2e: creating a subnet requires the subnet function to be enabled
  test/Makefile
  test/scripts/install-multus.sh
Labels: pr/release/none-required, pr/ready-review

#1876 fix coordinator disable failure
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
Labels: robot-cherrypick

#1875 multus cni config operator
  charts/spiderpool/README.md
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  charts/spiderpool/templates/_helpers.tpl
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/templates/multus-daemonset.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/templates/role_binding.yaml
  charts/spiderpool/templates/serviceaccount.yaml
  charts/spiderpool/templates/tls.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool/cmd/cni_types.go
  pkg/constant/k8s.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1/fake/fake_spidermultusconfig.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1/fake/fake_spiderpool.spidernet.io_client.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1/generated_expansion.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1/spidermultusconfig.go
  pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1/spiderpool.spidernet.io_client.go
  pkg/k8s/client/informers/externalversions/generic.go
  pkg/k8s/client/informers/externalversions/spiderpool.spidernet.io/v2beta1/interface.go
  pkg/k8s/client/informers/externalversions/spiderpool.spidernet.io/v2beta1/spidermultusconfig.go
  pkg/k8s/client/listers/spiderpool.spidernet.io/v2beta1/expansion_generated.go
  pkg/k8s/client/listers/spiderpool.spidernet.io/v2beta1/spidermultusconfig.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/multusconfig_webhook.go
  pkg/multuscniconfig/utils.go
  test/Makefile
  test/Makefile.defs
  test/scripts/install-multus.sh
Labels: pr/release/feature-new, pr/ready-review, cherrypick-release-v0.6

#1871 improve coordiantor
  Makefile.defs
  charts/spiderpool/README.md
  charts/spiderpool/templates/_helpers.tpl
  cmd/coordinator/Makefile
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  go.mod
  go.sum
  images/spiderpool-agent/Dockerfile
  pkg/networking/gwconnection/connection.go
  pkg/networking/networking/ip.go
  pkg/networking/networking/mac.go
  pkg/networking/networking/route.go
  test/Makefile
  test/Makefile.defs
  test/e2e/common/constant.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_suite_test.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  test/scripts/install-calico.sh
  test/scripts/install-default-cni.sh
  test/scripts/install-multus.sh
  test/scripts/install-spiderdoctor.sh
  test/yamls/kind-config.tmpl
  vendor/github.com/go-ping/ping/utils_linux.go
  vendor/github.com/go-ping/ping/utils_other.go
  vendor/github.com/go-ping/ping/utils_windows.go
  vendor/github.com/prometheus-community/pro-bing/.editorconfig
  vendor/github.com/prometheus-community/pro-bing/.gitignore
  vendor/github.com/prometheus-community/pro-bing/.golangci.yml
  vendor/github.com/prometheus-community/pro-bing/.goreleaser.yaml
  vendor/github.com/prometheus-community/pro-bing/CODE_OF_CONDUCT.md
  vendor/github.com/prometheus-community/pro-bing/CONTRIBUTING.md
  vendor/github.com/prometheus-community/pro-bing/LICENSE
  vendor/github.com/prometheus-community/pro-bing/MAINTAINERS.md
  vendor/github.com/prometheus-community/pro-bing/Makefile
  vendor/github.com/prometheus-community/pro-bing/README.md
  vendor/github.com/prometheus-community/pro-bing/SECURITY.md
  vendor/github.com/prometheus-community/pro-bing/logger.go
  vendor/github.com/prometheus-community/pro-bing/packetconn.go
  vendor/github.com/prometheus-community/pro-bing/ping.go
  vendor/github.com/prometheus-community/pro-bing/utils_linux.go
  vendor/github.com/prometheus-community/pro-bing/utils_other.go
  vendor/github.com/prometheus-community/pro-bing/utils_windows.go
  vendor/modules.txt
Labels: pr/release/none-required

#1940 disable subnet by default
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: pr/release/feature-changed

#1939 in dual stack environment, support only ipv4 or ipv6 address
  pkg/ipam/config.go
Labels: pr/release/feature-changed

#1942 chart: change subnetDefaultFlexibleIPNumber location
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/values.yaml
Labels: pr/release/feature-changed

#1937 e2e: Inconsistent ippool counts for subnets
  test/doc/subnet.md
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#1926 no check for the vlan of ippool
  pkg/ipam/allocate.go
  test/e2e/annotation/annotation_test.go
Labels: pr/release/feature-changed

#1934 default NIC could be specified by pod annotation
  api/v1/agent/client/daemonset/get_coordinator_config_parameters.go
  api/v1/agent/models/get_coordinator_args.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  api/v1/agent/server/restapi/daemonset/get_coordinator_config_parameters.go
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/command_del.go
  cmd/spiderpool-agent/cmd/coordinator.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/root.go
  go.mod
  pkg/constant/k8s.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/networking/gwconnection/connection.go
  pkg/networking/ipchecking/ipchecking.go
  test/scripts/install-multus.sh
Labels: pr/release/feature-new

#1948 robot update changelog with tag v0.6.0-rc1 to branch github_pages
  changelogs/changelog_from_v0.6.0-rc0_to_v0.6.0-rc1.md
Labels: pr/release/robot_update_githubpage

#1950 robot update changelog with tag v0.5.1 to branch github_pages
  changelogs/changelog_from_v0.5.0_to_v0.5.1.md
Labels: pr/release/robot_update_githubpage

#1965 fix coordinator spelling faults
  pkg/multuscniconfig/utils.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.6

#1971 fix multus-config CNI configuration master name faults and ifacer incorresponding configuration
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.6

#1972 slave must be down before creating bond
  cmd/ifacer/cmd/cmd_add.go
Labels: pr/release/bug

#1975 version 0.6.0 rc2
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#1976 robot update changelog with tag v0.6.0-rc2 to branch github_pages
  changelogs/changelog_from_v0.6.0-rc1_to_v0.6.0-rc2.md
Labels: pr/release/robot_update_githubpage

#1979 fix type assert faults
  cmd/coordinator/cmd/command_del.go
Labels: pr/release/bug, pr/ready-review
