Repository spidernet-io/spiderpool, pull requests merged in 2023-12, with the labels that each got.

#2702 add Network policy support docs for spiderpool
  docs/images/arch.png
  docs/mkdocs.yml
  docs/usage/cilium-chaining-zh_CN.md
  docs/usage/cilium-chaining.md
Labels: kind/doc, release/none

#2704 Update status of network policy support in roadmap
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: release/none

#2724 Updated docs for spiderpool v0.8
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/concepts/io-performance-zh_CN.md
  docs/concepts/io-performance.md
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  docs/concepts/ipam-performance-zh_CN.md
  docs/concepts/ipam-performance.md
  docs/develop/roadmap.md
  docs/images/arch.png
  docs/images/ipam-performance.png
  docs/images/performance-redis.png
  docs/images/performance-sockperf.png
  docs/mkdocs.yml
  docs/reference/crd-spidermultusconfig.md
  docs/usage/cilium-chaining-zh_CN.md
  docs/usage/cilium-chaining.md
  docs/usage/debug.md
  docs/usage/egress-zh_CN.md
  docs/usage/egress.md
  docs/usage/faq-zh_CN.md
  docs/usage/faq.md
  docs/usage/install/cloud/get-started-alibaba-zh_CN.md
  docs/usage/install/cloud/get-started-alibaba.md
  docs/usage/install/underlay/get-started-kind-zh_CN.md
  docs/usage/install/underlay/get-started-kind.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/kubevirt-zh_CN.md
  docs/usage/kubevirt.md
  docs/usage/network-topology-zh_CN.md
  docs/usage/network-topology.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
  docs/usage/spider-affinity-zh_CN.md
  docs/usage/spider-ippool-zh_CN.md
  docs/usage/spider-ippool.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
  docs/usage/underlay_cni_service-zh_CN.md
  docs/usage/underlay_cni_service.md
Labels: release/none, release-v0.8

#2728 fix e2e ci
  .github/workflows/e2e-init.yaml
  test/Makefile
  test/scripts/install-multus.sh
Labels: pr/ready-review, kind/ci-bug, release/none

#2733 Supports publishing rc and .z versions of docs to dev
  .github/workflows/call-release-doc.yaml
Labels: pr/dependabot/github-actions, kind/doc, release/none, release-v0.8, cherrypick-release-v0.8

#2749 bump golang to v1.21.4
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
  go.mod
  go.sum
Labels: release/none

#2756 init-pod: don't init multus CR if multus is disable
  cmd/coordinator/cmd/command_add.go
  cmd/spiderpool-init/cmd/root.go
Labels: release/bug, cherrypick-release-v0.8

#2759 don't update multus configMap if multus don't install
  charts/spiderpool/templates/pod.yaml
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/multus.go
Labels: release/bug, cherrypick-release-v0.8

#2771 Missing debug logs on different kernel versions.
  .github/workflows/e2e-init.yaml
Labels: release/none

#2773 e2e-fix: Avoid random subnets from overlapping with the subnets of clusters calico and cilium
  test/e2e/common/spiderpool.go
  test/e2e/common/spidersubnet.go
Labels: release/none

#2772 e2e-fix: Use the default calico version when getting the calico version fails
  test/Makefile.defs
  test/scripts/install-default-cni.sh
Labels: release/none

#2742 e2e-init: fix and update get-start-kind.md
  .github/.spelling
  .github/markdownlintignore
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  .gitignore
  Makefile
  Makefile.defs
  README-zh_CN.md
  README.md
  cmd/spiderpool/cmd/command_test.go
  docs/README-zh_CN.md
  docs/README.md
  docs/mkdocs.yml
  docs/usage/install/get-started-kind-zh_CN.md
  docs/usage/install/get-started-kind.md
  docs/usage/install/underlay/get-started-kind-zh_CN.md
  docs/usage/install/underlay/get-started-kind.md
  docs/usage/multi-interfaces-annotation.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
  docs/usage/third-party-controller.md
  pkg/applicationcontroller/applicationcontroller_suite_test.go
  pkg/applicationcontroller/applicationinformers/controller_test.go
  pkg/applicationcontroller/applicationinformers/cronjob_informer_test.go
  pkg/applicationcontroller/applicationinformers/daemonset_informer_test.go
  pkg/applicationcontroller/applicationinformers/deployment_informer_test.go
  pkg/applicationcontroller/applicationinformers/job_informer_test.go
  pkg/applicationcontroller/applicationinformers/replicaset_informer_test.go
  pkg/applicationcontroller/applicationinformers/statefulset_informer_test.go
  pkg/applicationcontroller/applicationinformers/utils_test.go
  pkg/election/lease_election_test.go
  pkg/ip/ip_suite_test.go
  pkg/ippoolmanager/ippool_informer_test.go
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/ippoolmanager/utils_test.go
  pkg/limiter/limiter_suite_test.go
  pkg/lock/lock_debug_test.go
  pkg/lock/lock_fast_test.go
  pkg/logutils/log_test.go
  pkg/namespacemanager/namespace_manager_suite_test.go
  pkg/nodemanager/node_manager_suite_test.go
  pkg/podmanager/pod_manager_suite_test.go
  pkg/reservedipmanager/reservedip_manager_suite_test.go
  pkg/statefulsetmanager/sts_manager_suite_test.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager_suite_test.go
  test/Makefile
  test/Makefile.defs
  test/scripts/install-tools.sh
  test/scripts/installTestPod.sh
  test/yamls/global-kind.yaml
  test/yamls/kind-config.tmpl
Labels: kind/doc, release/none, release-v0.8, cherrypick-release-v0.8

#2774 docs: add submariner get-stared
  docs/images/submariner.png
  docs/mkdocs.yml
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/submariner-zh_CN.md
  docs/usage/submariner.md
Labels: release/none, cherrypick-release-v0.8

#2777 docs: opt arch document
  docs/concepts/arch-zh_CN.md
  docs/concepts/arch.md
  docs/images/spiderpool-arch.jpg
  docs/images/spiderpool_arch.png
Labels: release/none, cherrypick-release-v0.8

#2789 e2e-init: fix and update get-start-kind.md
  .github/.spelling
  .github/markdownlintignore
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  .gitignore
  Makefile
  Makefile.defs
  README-zh_CN.md
  README.md
  cmd/spiderpool/cmd/command_test.go
  docs/README-zh_CN.md
  docs/README.md
  docs/mkdocs.yml
  docs/usage/install/get-started-kind-zh_CN.md
  docs/usage/install/get-started-kind.md
  docs/usage/install/underlay/get-started-kind-zh_CN.md
  docs/usage/install/underlay/get-started-kind.md
  docs/usage/multi-interfaces-annotation.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
  docs/usage/third-party-controller.md
  pkg/applicationcontroller/applicationcontroller_suite_test.go
  pkg/applicationcontroller/applicationinformers/controller_test.go
  pkg/applicationcontroller/applicationinformers/cronjob_informer_test.go
  pkg/applicationcontroller/applicationinformers/daemonset_informer_test.go
  pkg/applicationcontroller/applicationinformers/deployment_informer_test.go
  pkg/applicationcontroller/applicationinformers/job_informer_test.go
  pkg/applicationcontroller/applicationinformers/replicaset_informer_test.go
  pkg/applicationcontroller/applicationinformers/statefulset_informer_test.go
  pkg/applicationcontroller/applicationinformers/utils_test.go
  pkg/election/lease_election_test.go
  pkg/ip/ip_suite_test.go
  pkg/ippoolmanager/ippool_informer_test.go
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/ippoolmanager/utils_test.go
  pkg/limiter/limiter_suite_test.go
  pkg/lock/lock_debug_test.go
  pkg/lock/lock_fast_test.go
  pkg/logutils/log_test.go
  pkg/namespacemanager/namespace_manager_suite_test.go
  pkg/nodemanager/node_manager_suite_test.go
  pkg/podmanager/pod_manager_suite_test.go
  pkg/reservedipmanager/reservedip_manager_suite_test.go
  pkg/statefulsetmanager/sts_manager_suite_test.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager_suite_test.go
  test/Makefile
  test/Makefile.defs
  test/scripts/install-tools.sh
  test/scripts/installTestPod.sh
  test/yamls/global-kind.yaml
  test/yamls/kind-config.tmpl
Labels: robot-cherrypick, release/none

#2785 Update e2e framework for spiderpool
  go.mod
  go.sum
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/modules.txt
Labels: release/none

#2791 update arch.md doc
  docs/concepts/arch.md
Labels: release/none

#2794 docs: rebase main
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
  docs/concepts/arch.md
  docs/develop/roadmap.md
  docs/images/arch.png
  docs/mkdocs.yml
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
  docs/usage/submariner-zh_CN.md
  docs/usage/submariner.md
Labels: kind/doc, release/none

#2797 Cherry-pick to release-v0.8.0
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-init/cmd/root.go
  go.mod
  go.sum
  pkg/errgroup/README.md
  pkg/errgroup/errgroup.go
  pkg/networking/ipchecking/ipchecking.go
Labels: release/none

#2778 fix ovs installtation scripts
  test/e2e/kubevirt/kubevirt_test.go
  test/e2e/kubevirt/testvm.yaml
  test/scripts/install-kubevirt.sh
  test/scripts/install-multus.sh
Labels: pr/ready-review, kind/bug, release/none, cherrypick-release-v0.8

#2800 bump version to v0.8.3
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#2814 update readme.md
  README-zh_CN.md
  README.md
  docs/develop/release.md
Labels: release/none

#2816 update readme.md
  docs/README-zh_CN.md
  docs/README.md
Labels: release/none

#2805 docs: Optimize and typo
  docs/usage/cilium-chaining-zh_CN.md
  docs/usage/cilium-chaining.md
  docs/usage/install/get-started-kind-zh_CN.md
  docs/usage/install/get-started-kind.md
  docs/usage/rdma-zh_CN.md
Labels: kind/doc, release/none, release-v0.8, cherrypick-release-v0.8

#2819 e2e: Set sriov.enable Rdma to true and see if multus nad has rdma
  test/doc/coordinator.md
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: kind/test, release/none

#2821 support spidersubnet single IP in dual stack
  pkg/applicationcontroller/app_controller.go
  pkg/ipam/pool_selections.go
Labels: pr/ready-review, release/feature-new

#2826 arch picture
  docs/images/arch.png
Labels: release/none

#2834 update quick start
  docs/mkdocs.yml
  docs/usage/install/get-started-kind-zh_CN.md
  docs/usage/install/get-started-kind.md
Labels: release/none, cherrypick-release-v0.8

#2833 docs optimization
  docs/README-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
Labels: pr/ready-review, kind/doc, release/none, release-v0.8

#2836 update index
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
Labels: cherrypick-release-v0.8

#2831 e2e-fix: Unbound variable DEFAULT_CALICO_VERSION
  test/Makefile
Labels: release/none, release/bug

#2840 update quick start
  docs/usage/install/get-started-kind-zh_CN.md
  docs/usage/install/get-started-kind.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
Labels: release-v0.8

#2839 update spiderpool arch image
  docs/images/spiderpool_arch.png
Labels: release/none, cherrypick-release-v0.8

#2820 aws documents optimization
  docs/images/aws/aws-ingress.png
  docs/images/aws/aws-interfaces.png
  docs/images/aws/aws-ip-prefix.png
  docs/images/aws/aws-k8s-network.png
  docs/images/aws/aws-lb.png
  docs/images/aws/aws-secondary-nic.png
  docs/images/aws/aws-subnet-1.png
  docs/images/aws/aws-subnet-2.png
  docs/images/aws/aws-subnet.png
  docs/usage/install/cloud/get-started-aws-zh_CN.md
  docs/usage/install/cloud/get-started-aws.md
Labels: pr/ready-review, kind/doc, release/none, cherrypick-release-v0.8

#2852 docs: update docs format
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  docs/concepts/ipam-performance-zh_CN.md
  docs/concepts/ipam-performance.md
Labels: pr/release/doc, kind/doc, release/none, cherrypick-release-v0.8

#2855 doc: arch
  docs/images/spiderpool_arch.png
Labels: cherrypick-release-v0.8

#2865 docs: update AUTHORS
  AUTHORS
Labels: pr/release/doc, release/none, cherrypick-release-v0.8

#2861 docs: update images
  docs/images/across-networks-1.png
  docs/images/across-networks-2.png
  docs/images/ip-allocation-across-networks-1.png
  docs/images/ip-allocation-across-networks-2.png
  docs/usage/network-topology-zh_CN.md
  docs/usage/network-topology.md
Labels: pr/release/doc, release/none, cherrypick-release-v0.8

#2860 optimize k8s extended operator document title
  docs/mkdocs.yml
  docs/usage/operator-zh_CN.md
  docs/usage/operator.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
  docs/usage/third-party-controller-zh_CN.md
  test/Makefile
Labels: pr/ready-review, release/none, cherrypick-release-v0.8

#2867 doc: add community
  MAINTAINERS.md
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: cherrypick-release-v0.8

#2872 update contributing
  docs/develop/contributing.md
Labels: cherrypick-main

#2876 update readme
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: cherrypick-release-v0.8

#2878 typo
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: cherrypick-release-v0.8

#2882 doc: typo
  docs/concepts/arch-zh_CN.md
  docs/concepts/arch.md
Labels: cherrypick-release-v0.8

#2886 update readme
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: cherrypick-release-v0.8

#2891 update readme
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: cherrypick-release-v0.8

#2895 docs: typo
  README-zh_CN.md
  docs/README-zh_CN.md
  docs/reference/plugin-ifacer.md
Labels: release/none, cherrypick-release-v0.8

#2898 update governance document link
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: release/none, cherrypick-release-v0.8

#2897 update image for underlay_cni_service.md
  docs/images/spiderpool_service_kube_proxy.png
Labels: release/none, cherrypick-release-v0.8

#2904 update image for underlay_cni_service.md
  docs/images/spiderpool_service_kube_proxy.png
Labels: robot-cherrypick

#2815 feature: support infiniband with ib-sriov and ipoib cni
  .github/workflows/build-image-plugins.yaml
  README-zh_CN.md
  charts/spiderpool/README.md
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/multus.go
  docs/concepts/arch-zh_CN.md
  docs/concepts/arch.md
  docs/develop/roadmap.md
  docs/mkdocs.yml
  docs/reference/crd-spidermultusconfig.md
  docs/usage/install/cloud/get-started-aws-zh_CN.md
  docs/usage/install/cloud/get-started-aws.md
  docs/usage/rdma-ib-zh_CN.md
  docs/usage/rdma-ib.md
  docs/usage/rdma-roce-zh_CN.md
  docs/usage/rdma-roce.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  docs/usage/underlay_cni_service-zh_CN.md
  docs/usage/underlay_cni_service.md
  images/spiderpool-plugins/Dockerfile
  images/spiderpool-plugins/entrypoint.sh
  pkg/constant/k8s.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/utils.go
Labels: release/feature-new

#2916 cherrypick 2831 to release-v0.8
  test/Makefile
Labels: release/none, release-v0.8

#2920 doc: ipam
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: cherrypick-release-v0.8

#2921 doc: ipam
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: robot-cherrypick

#2926 coordinator: improve determining the default route for IPv6
  pkg/networking/networking/route.go
Labels: robot-cherrypick

#2925 coordinator: improve determining the default route for IPv6
  pkg/networking/networking/route.go
Labels: robot-cherrypick

#2902 add validation for IPAM IPPools annotation usage
  cmd/spiderpool/cmd/command_add.go
  pkg/ipam/pool_selections.go
  pkg/ipam/utils.go
  test/doc/annotation.md
  test/e2e/annotation/annotation_test.go
Labels: pr/ready-review, release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#2823 e2e: Optimize and add e2e use cases for 'ip rule'
  test/doc/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
Labels: kind/test, release/none

#2862 SpiderMultusConfig: support empty config with custom type
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/multus.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/multusconfig_webhook.go
  test/doc/spidermultus.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/ifacer/ifacer_test.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/spidermultus/spidermultus_suite_test.go
  test/e2e/spidermultus/spidermultus_test.go
Labels: pr/ready-review, release/feature-new, cherrypick-release-v0.9

#2935 fix merge conflict
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
Labels: pr/ready-review, release/none

#2929 spidercoordinator: It should update the status to NotReady if any errors occur
  pkg/coordinatormanager/coordinator_informer.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#2945 spidercoordinator: It should update the status to NotReady if any errors occur
  pkg/coordinatormanager/coordinator_informer.go
Labels: robot-cherrypick

#2947 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: release/none

#2937 supplement annotation e2e
  go.mod
  go.sum
  test/doc/affinity.md
  test/doc/annotation.md
  test/doc/assignip.md
  test/e2e/annotation/annotation_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/modules.txt
Labels: pr/ready-review, release/none

#2933 SpiderMultusConfig: support empty config with custom type
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/multus.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/multusconfig_webhook.go
  test/doc/spidermultus.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/ifacer/ifacer_test.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/spidermultus/spidermultus_suite_test.go
  test/e2e/spidermultus/spidermultus_test.go
Labels: pr/ready-review, robot-cherrypick, release/feature-new

#2824 CI workflow: Updated obsolete method set-output.
  .github/workflows/auto-version-release.yaml
  .github/workflows/build-image-base.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/build-image-plugins.yaml
  .github/workflows/call-clean-ghcr.yaml
  .github/workflows/call-lint-chart.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-image.yaml
  .github/workflows/call-update-githubpages.yaml
  .github/workflows/ci-image-gc-by-pr.yaml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-license.yaml
  .github/workflows/lint-spell.yaml
Labels: pr/dependabot/github-actions, release/none, release/bug

#2956 doc: update sriov note
  docs/usage/rdma-ib-zh_CN.md
  docs/usage/rdma-ib.md
  docs/usage/rdma-roce-zh_CN.md
  docs/usage/rdma-roce.md
Labels: cherrypick-release-v0.8

#2957 Warning caused by modifying invalid usage
  .github/workflows/e2e-init.yaml
Labels: pr/dependabot/github-actions, release/none

#2965 Add signoff to cherry pick robot
  .github/workflows/auto-cherrypick.yaml
Labels: pr/dependabot/github-actions, release/none

#2968 website requirement for sandbox
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: cherrypick-release-v0.7, release/none, cherrypick-release-v0.8

#2973 supplement troubleshoot documents
  docs/usage/faq-zh_CN.md
  docs/usage/faq.md
Labels: pr/ready-review, kind/doc, release/none

#2971 fix: spiderpool-agent crashes when kubevirt static IP feature is off
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
Labels: pr/ready-review, kind/bug, release/bug, cherrypick-release-v0.8

#2964 supplement assign IP e2e
  test/doc/assignip.md
  test/e2e/assignip/assignip_test.go
Labels: pr/ready-review, release/none

#2953 supplement IPPool CR e2e
  test/doc/ippoolcr.md
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: pr/ready-review, release/none

#2980 fix CI : the receiving end does not support --signed push
  .github/workflows/auto-cherrypick.yaml
Labels: pr/dependabot/github-actions, release/none

#2982 readme: add copyright
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: release/none

#2927 e2e: Add spidercoodinator e2e for spiderpool
  test/doc/spidercoodinator.md
  test/e2e/common/constant.go
  test/e2e/common/mode.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/spidercoordinator/spidercoordinator_suite_test.go
  test/e2e/spidercoordinator/spidercoordinator_test.go
  test/scripts/install-default-cni.sh
Labels: kind/test, release/none

#2974 fix chart: Values.multus.multusCNI.uninstall does not take effect
  charts/spiderpool/templates/daemonset.yaml
Labels: cherrypick-release-v0.7, release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#2246 add some e2e for spiderpool
  test/doc/coordinator.md
Labels: pr/approved, pr/ready-review, kind/doc, release/none

#2986 fix chart: Values.multus.multusCNI.uninstall does not take effect
  charts/spiderpool/templates/daemonset.yaml
Labels: robot-cherrypick, release/bug

#2985 fix chart: Values.multus.multusCNI.uninstall does not take effect
  charts/spiderpool/templates/daemonset.yaml
Labels: robot-cherrypick, release/bug

#2992 Additional performance test data notes
  test/e2e/performance/performance.md
Labels: kind/doc, release/none

#3003 Add a blog about using spiderpool in vivo.
  docs/concepts/blog-zh_CN.md
  docs/concepts/blog.md
Labels: kind/doc, release/none, cherrypick-release-v0.8

#3004 Add a blog about using spiderpool in vivo.
  docs/concepts/blog-zh_CN.md
  docs/concepts/blog.md
Labels: robot-cherrypick

#2650 coordinator: Add a new filed "txQueueLen"
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/spiderpool-agent/cmd/coordinator.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/reference/crd-spidercoordinator.md
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/networking/networking/ip.go
Labels: release/feature-new

#2996 Revert "build(deps): bump actions/download-artifact and actions/upload-artifact from 3 to 4“
  .github/workflows/auto-version-release.yaml
  .github/workflows/build-image-base.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/build-image-plugins.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-release-image.yaml
  .github/workflows/call-update-githubpages.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-yaml.yaml
  .github/workflows/trivy-scan-image.yaml
  .github/workflows/update-chart-readme.yml
Labels: pr/dependabot/github-actions, release/none

#2987 [cherrypick]fix spiderpool-agent crashes when kubevirt static IP feature is off
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
Labels: pr/ready-review, kind/bug, release/bug

#2988 supplement system requirements doc
  docs/mkdocs.yml
  docs/usage/install/cloud/get-started-alibaba-zh_CN.md
  docs/usage/install/cloud/get-started-alibaba.md
  docs/usage/install/cloud/get-started-aws-zh_CN.md
  docs/usage/install/cloud/get-started-aws.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/system-requirements-zh_CN.md
  docs/usage/install/system-requirements.md
  docs/usage/install/underlay/get-started-calico-zh_CN.md
  docs/usage/install/underlay/get-started-calico.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-sriov.md
  docs/usage/install/underlay/get-started-weave-zh_CN.md
  docs/usage/install/underlay/get-started-weave.md
Labels: pr/ready-review, kind/doc, release/none

#3008 rebase main for calico version
  test/Makefile.defs
  test/scripts/install-default-cni.sh
Labels: release/none, release-v0.8

#3001 Minor changes about bullets indentations and punctuations in docs/readme
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: kind/doc, release/none, cherrypick-release-v0.8

#3011 fix inherit subnet properties for ippool failure
  pkg/ippoolmanager/ippool_mutate.go
  pkg/subnetmanager/subnet_informer.go
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: pr/ready-review, kind/bug, cherrypick-release-v0.7, release/bug, cherrypick-release-v0.8

#2952 single POD without controller is forbidden to use SpiderSubnet feature
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
  pkg/ipam/pool_selections.go
  test/doc/subnet.md
  test/e2e/subnet/subnet_test.go
Labels: pr/ready-review, cherrypick-release-v0.7, release/bug, cherrypick-release-v0.8

#3020 spidercoordinator: fetch the serviceCIDR from kubeControllerManager pod
  pkg/coordinatormanager/coordinator_informer.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#3023 spidercoordinator: fetch the serviceCIDR from kubeControllerManager pod
  pkg/coordinatormanager/coordinator_informer.go
Labels: robot-cherrypick

#3024 spidercoordinator: fetch the serviceCIDR from kubeControllerManager pod
  pkg/coordinatormanager/coordinator_informer.go
Labels: robot-cherrypick

#3025 [cherrypick]fix inherit subnet properties for ippool failure
  pkg/ippoolmanager/ippool_mutate.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/ready-review, release/bug

#3022 [cherrypick]fix inherit subnet properties for ippool failure
  pkg/ippoolmanager/ippool_mutate.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/ready-review, release/bug

#3021 [cherrypick]single POD without controller is forbidden to use SpiderSubnet feature
  pkg/ipam/pool_selections.go
Labels: pr/ready-review, release/none, release/bug

#3026 update otel sdk
  go.mod
  go.sum
  vendor/go.opentelemetry.io/otel/sdk/metric/version.go
  vendor/go.opentelemetry.io/otel/sdk/version.go
  vendor/modules.txt
Labels: pr/ready-review, kind/cleanup, release/none

#3019 single POD without controller is forbidden to use SpiderSubnet feature
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
  pkg/ipam/pool_selections.go
  test/doc/subnet.md
  test/e2e/subnet/subnet_test.go
Labels: robot-cherrypick, release/bug

#3027 docs: update overlay mode get-started.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3029 docs: update overlay mode get-started.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
Labels: robot-cherrypick

#3028 docs: update overlay mode get-started.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
Labels: robot-cherrypick

#3032 release v0.9.0
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#3037 release v0.7.2
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/ready-review, release/none

#3038 release v0.8.4
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/ready-review, release/none
