Repository spidernet-io/spiderpool, pull requests merged in 2023-10, with the labels that each got.

#2374 doc: add en spidersubnet
  docs/usage/reserved-ip.md
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, cherrypick-release-v0.7, release/none

#2378 doc: add en spidersubnet
  docs/usage/reserved-ip.md
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
Labels: robot-cherrypick

#2370 improve GetTopController method
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/app_controller_test.go
  pkg/applicationcontroller/applicationcontroller_suite_test.go
  pkg/podmanager/pod_manager.go
  pkg/podmanager/pod_manager_test.go
Labels: pr/ready-review, cherrypick-release-v0.6, cherrypick-release-v0.7, release/bug

#2382 integrate rdma cni and rdma device plugin
  README-zh_CN.md
  README.md
  charts/spiderpool/README.md
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  charts/spiderpool/templates/_helpers.tpl
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/rdma-shared-dp.yaml
  charts/spiderpool/values.yaml
  docs/README-zh_CN.md
  docs/README.md
  docs/develop/roadmap.md
  docs/mkdocs.yml
  docs/reference/crd-spidermultusconfig.md
  docs/usage/rdma-zh_CN.md
  docs/usage/rdma.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
  test/Makefile
  test/Makefile.defs
Labels: release/feature-new

#2379 improve GetTopController method
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/app_controller_test.go
  pkg/applicationcontroller/applicationcontroller_suite_test.go
  pkg/podmanager/pod_manager.go
  pkg/podmanager/pod_manager_test.go
Labels: robot-cherrypick

#2380 improve GetTopController method
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/app_controller_test.go
  pkg/applicationcontroller/applicationcontroller_suite_test.go
  pkg/podmanager/pod_manager.go
  pkg/podmanager/pod_manager_test.go
Labels: robot-cherrypick

#2386 chart: sriov network operator
  charts/spiderpool/README.md
  charts/spiderpool/crds/k8s.cni.cncf.io_networkattachmentdefinitions_crd.yaml
  charts/spiderpool/crds/sriovnetwork.openshift.io_sriovibnetworks.yaml
  charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml
  charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworknodestates.yaml
  charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworkpoolconfigs.yaml
  charts/spiderpool/crds/sriovnetwork.openshift.io_sriovnetworks.yaml
  charts/spiderpool/crds/sriovnetwork.openshift.io_sriovoperatorconfigs.yaml
  charts/spiderpool/templates/_helpers.tpl
  charts/spiderpool/templates/multus/multus-daemonset-thick.yaml
  charts/spiderpool/templates/multus/multus-daemonset.yaml
  charts/spiderpool/templates/rdma-shared-dp/rdma-shared-dp.yaml
  charts/spiderpool/templates/sriov-network-operator/clusterrole.yaml
  charts/spiderpool/templates/sriov-network-operator/clusterrolebinding.yaml
  charts/spiderpool/templates/sriov-network-operator/configmap.yaml
  charts/spiderpool/templates/sriov-network-operator/operator.yaml
  charts/spiderpool/templates/sriov-network-operator/role.yaml
  charts/spiderpool/templates/sriov-network-operator/rolebinding.yaml
  charts/spiderpool/templates/sriov-network-operator/serviceaccount.yaml
  charts/spiderpool/values.yaml
  docs/develop/roadmap.md
  docs/usage/install/install-zh_CN.md
  docs/usage/install/install.md
  docs/usage/install/underlay/get-started-macvlan-and-sriov.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/rdma-zh_CN.md
  test/Makefile
  test/Makefile.defs
  test/doc/spidermultus.md
  tools/k8s-controller-gen/update-controller-gen.sh
Labels: release/feature-new

#2394 optimize github action no disk space left
  .github/workflows/e2e-init.yaml
Labels: pr/ready-review, kind/ci-bug, release/none

#2398 add kubernetes 1.28 version support to e2e
  .github/workflows/auto-diff-k8s-ci.yaml
Labels: release/none

#2397 fix the problem that the rc version cannot generate artifact.
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
Labels: cherrypick-release-v0.6, release-v0.6, release-v0.7, cherrypick-release-v0.7, release/none

#2346 [docs]: add some usage and concepts for spiderpool
  docs/concepts/allocation-zh_CN.md
  docs/concepts/allocation.md
  docs/mkdocs.yml
  docs/usage/spider-affinity-zh_CN.md
  docs/usage/spider-affinity.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
Labels: pr/release/doc, release-v0.7, cherrypick-release-v0.7, release/none

#2401 [docs]: add some usage and concepts for spiderpool
  docs/concepts/allocation-zh_CN.md
  docs/concepts/allocation.md
  docs/mkdocs.yml
  docs/usage/spider-affinity-zh_CN.md
  docs/usage/spider-affinity.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
Labels: robot-cherrypick

#2381 doc: add en statefulset
  docs/usage/statefulset-zh_CN.md
  docs/usage/statefulset.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release-v0.7, cherrypick-release-v0.7, release/none

#2403 Fix ci calling release-chart error
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-release-chart.yaml
Labels: cherrypick-release-v0.6, release-v0.6, release-v0.7, cherrypick-release-v0.7, release/none

#2402 doc: add en statefulset
  docs/usage/statefulset-zh_CN.md
  docs/usage/statefulset.md
Labels: pr/release/doc, robot-cherrypick

#2413 Fix ci calling release-chart error
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-release-chart.yaml
Labels: robot-cherrypick

#2420 Add e2e regarding ippool.spec.multusName affinity.
  test/doc/ippoolcr.md
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: release/none

#2419 doc: add en rdma
  docs/usage/rdma-zh_CN.md
  docs/usage/rdma.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release/none

#2417 Fix invalid link in PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release/none

#2418 doc: update readme
  README-zh_CN.md
  README.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release/none

#2410 docs: update alicloud ipv6 docs
  docs/images/alicloud-ipv6-gateway.png
  docs/usage/install/cloud/get-started-alibaba-zh_CN.md
  docs/usage/install/cloud/get-started-alibaba.md
Labels: release-v0.7, cherrypick-release-v0.7, release/none

#2425 Add and improve the e2e use case of the NIC where the default route is located
  cmd/coordinator/cmd/utils.go
  test/Makefile
  test/doc/coordinator.md
  test/e2e/common/constant.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/none

#2351 aws cloud doc
  README-zh_CN.md
  README.md
  docs/images/aws/aws-iam-policy.png
  docs/images/aws/aws-iam-role.png
  docs/images/aws/aws-ingress.png
  docs/images/aws/aws-interfaces.png
  docs/images/aws/aws-k8s-network.png
  docs/images/aws/aws-lb.png
  docs/images/aws/aws-nat-gateway.png
  docs/images/aws/aws-nat-route.png
  docs/images/aws/aws-secondary-nic.png
  docs/images/aws/aws-subnet-1.png
  docs/images/aws/aws-subnet-2.png
  docs/images/aws/aws-subnet-concept.png
  docs/usage/install/cloud/get-started-aws-zh_CN.md
  docs/usage/install/cloud/get-started-aws.md
  docs/usage/install/install-zh_CN.md
  docs/usage/install/install.md
Labels: pr/ready-review, release/none

#2443 e2e: add nodeName affinity e2e for spiderpool
  test/doc/ippoolcr.md
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: release/none

#2440 doc: update en sriov
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-sriov.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release/none

#2436 doc: update doc/readme
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release/none

#2431 CI: run cilium without kube-proxy
  .github/workflows/e2e-init.yaml
  Makefile
  test/Makefile
  test/Makefile.defs
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
  test/scripts/install-default-cni.sh
  test/scripts/install-multus.sh
Labels: release/none

#2434 spidercoordinator: fix auto fetch podCIDRType
  charts/spiderpool/README.md
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  docs/reference/spiderpool-controller.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/coordinatormanager/coordinator_informer.go
  pkg/utils/string/string.go
  pkg/utils/utils.go
  test/Makefile
  test/Makefile.defs
  test/doc/spidercoodinator.md
  test/scripts/install-default-cni.sh
  test/yamls/calico.yaml
Labels: release/bug

#2461 pending e2e kubevirt Passt with IPv6-only case
  test/e2e/kubevirt/kubevirt_test.go
Labels: pr/ready-review, release/none

#2451 init: create default spidermultusconfig network if it isn't empty
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/multus/multus-daemonset-thick.yaml
  charts/spiderpool/templates/multus/multus-daemonset.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/client.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/multus.go
  cmd/spiderpool-init/cmd/root.go
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-kind-zh_CN.md
  docs/usage/install/underlay/get-started-kind.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/network-topology-zh_CN.md
  docs/usage/network-topology.md
  docs/usage/rdma-zh_CN.md
  docs/usage/rdma.md
  docs/usage/reserved-ip-zh_CN.md
  docs/usage/reserved-ip.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
  docs/usage/statefulset-zh_CN.md
  docs/usage/statefulset.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  test/scripts/debugEnv.sh
  test/scripts/install-multus.sh
Labels: release/feature-new

#2457 docker-image: build new image for all plugins
  .github/workflows/build-image-plugins.yaml
  images/plugins/.dockerignore
  images/plugins/Dockerfile
  images/plugins/entrypoint.sh
Labels: release/feature-new

#2467 en doc: update readme and arch based on pr#2458
  README-zh_CN.md
  README.md
  docs/concepts/arch-zh_CN.md
  docs/concepts/arch.md
  docs/develop/contributing.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release/none

#2472 Update spider-multus-config.md
  docs/usage/spider-multus-config.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release/none

#2470 doc: add en affinity
  docs/usage/spider-affinity-zh_CN.md
  docs/usage/spider-affinity.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release/none

#2466 spiderAgent: install cni,ovs and rdma in init-container
  charts/spiderpool/README.md
  charts/spiderpool/templates/_helpers.tpl
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/values.yaml
  docs/usage/install/cloud/get-started-alibaba-zh_CN.md
  docs/usage/install/cloud/get-started-alibaba.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/rdma-zh_CN.md
  docs/usage/rdma.md
  test/Makefile
  test/scripts/cni-install.sh
  test/scripts/install-multus.sh
Labels: release/feature-new

#2490 set logger for controller-runtime framework
  cmd/spiderpool-agent/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  go.mod
Labels: pr/ready-review, enhancement, release/none

#2489 coordinator: fix the eth0 source IP for the packet going through veth0
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  pkg/networking/networking/route.go
  test/doc/coordinator.md
  test/scripts/install-multus.sh
Labels: release/feature-new

#2498 doc: add en aws doc
  docs/usage/install/cloud/get-started-aws-zh_CN.md
  docs/usage/install/cloud/get-started-aws.md
Labels: pr/ready-review, kind/documentation, release/none

#2493 deprecate IPPool/Subnet CRD vlan property
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  docs/reference/crd-spiderippool.md
  docs/reference/crd-spidersubnet.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidersubnet_types.go
Labels: pr/ready-review, release/none

#2504 Fix chart file cannot be found
  .github/workflows/call-release-chart.yaml
Labels: release/none, release-v0.8

#2510 CI: fix ifacer e2e case
  test/e2e/common/constant.go
  test/e2e/ifacer/ifacer_test.go
Labels: release/none
