Repository spidernet-io/spiderpool, pull requests merged in 2023-09, with the labels that each got.

#2307 repair document template
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/ci-image-gc-by-pr.yaml
  docs/mkdocs.yml
Labels: pr/release/robot_update_githubpage, pr/ready-review

#2302 set chart enableSpiderSubnet to be true
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: pr/release/chart, pr/ready-review, enhancement, cherrypick-release-v0.7, release/feature-new

#2312 [docs]: optimize doc format for spiderpool
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-sriov.md
  docs/usage/spider-subnet.md
Labels: cherrypick-release-v0.7, release/feature-changed

#2306 charts default value adjustment
  charts/spiderpool/README.md
  charts/spiderpool/templates/_helpers.tpl
  charts/spiderpool/templates/grafanaDashboard.yaml
  charts/spiderpool/templates/prometheusrule.yaml
  charts/spiderpool/templates/servicemonitor.yaml
  charts/spiderpool/values.yaml
Labels: pr/ready-review, enhancement, cherrypick-release-v0.7, release/feature-changed

#2317 spidermultusconfig: IPAM can be disabled
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  docs/reference/crd-spidermultusconfig.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
  test/doc/spidermultus.md
Labels: release/feature-new

#2314 spidercoordinator: allow set ip addr to hijackCIDR
  cmd/spiderpool-init/cmd/config.go
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/ip/ip.go
  pkg/ip/ip_test.go
  test/scripts/install-multus.sh
Labels: release/feature-new

#2318 spidermultusconfig: make IPAM field to pointer
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
Labels: release/none

#2328 README.md: update contact information
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
  docs/images/wechat.png
Labels: release/none

#2332 coordinator: bump netlink version
  go.mod
  go.sum
  pkg/networking/networking/route.go
  vendor/github.com/vishvananda/netlink/chain.go
  vendor/github.com/vishvananda/netlink/chain_linux.go
  vendor/github.com/vishvananda/netlink/conntrack_linux.go
  vendor/github.com/vishvananda/netlink/filter.go
  vendor/github.com/vishvananda/netlink/filter_linux.go
  vendor/github.com/vishvananda/netlink/handle_unspecified.go
  vendor/github.com/vishvananda/netlink/ipset_linux.go
  vendor/github.com/vishvananda/netlink/link.go
  vendor/github.com/vishvananda/netlink/link_linux.go
  vendor/github.com/vishvananda/netlink/neigh_linux.go
  vendor/github.com/vishvananda/netlink/netlink_unspecified.go
  vendor/github.com/vishvananda/netlink/nl/conntrack_linux.go
  vendor/github.com/vishvananda/netlink/nl/ipset_linux.go
  vendor/github.com/vishvananda/netlink/nl/nl_linux.go
  vendor/github.com/vishvananda/netlink/nl/route_linux.go
  vendor/github.com/vishvananda/netlink/nl/tc_linux.go
  vendor/github.com/vishvananda/netlink/nl/xfrm_linux.go
  vendor/github.com/vishvananda/netlink/nl/xfrm_state_linux.go
  vendor/github.com/vishvananda/netlink/qdisc.go
  vendor/github.com/vishvananda/netlink/qdisc_linux.go
  vendor/github.com/vishvananda/netlink/route_linux.go
  vendor/github.com/vishvananda/netlink/rule.go
  vendor/github.com/vishvananda/netlink/rule_linux.go
  vendor/github.com/vishvananda/netlink/xfrm_policy_linux.go
  vendor/github.com/vishvananda/netlink/xfrm_state.go
  vendor/github.com/vishvananda/netlink/xfrm_state_linux.go
  vendor/modules.txt
Labels: release/none

#2333 update codes comments
  pkg/ipam/pool_selections.go
Labels: pr/ready-review, enhancement

#2319 add large-scale case for spiderpool
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/common/constant.go
  test/e2e/common/deployment.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/kruise/kruise_test.go
  test/e2e/performance/performance_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  test/e2e/reservedip/reservedip_test.go
  test/e2e/spidermultus/spidermultus_test.go
  test/e2e/subnet/subnet_test.go
  test/scripts/debugEnv.sh
Labels: release/none

#2327 [docs]: add statefulset usage docs for spiderpool
  README-zh_CN.md
  docs/README-zh_CN.md
  docs/usage/statefulset-zh_CN.md
  docs/usage/statefulset.md
Labels: release/none

#2335 Update debugEnv.sh
  test/scripts/debugEnv.sh
Labels: release/none

#2298 Upgrade spiderpool from (<=0.6.0) to 0.7.0
  docs/usage/install/upgrade.md
Labels: pr/release/doc, release/none

#2354 doc: add en coordinator
  docs/usage/coordinator-zh_CN.md
  docs/usage/coordinator.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release-v0.7, cherrypick-release-v0.7, release/none

#2362 spidermultusconfig: make defaultCniCRName to empty by default
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/root.go
Labels: release/bug

#2359 doc: add en reserved-ip
  docs/usage/reserved-ip-zh_CN.md
  docs/usage/reserved-ip.md
Labels: pr/release/doc, pr/ready-review, kind/documentation, release-v0.7, cherrypick-release-v0.7, release/none

#2352 [docs]: update alibaba docs for spiderpool
  docs/usage/install/cloud/get-started-alibaba-zh_CN.md
Labels: kind/documentation, release-v0.7, cherrypick-release-v0.7, release/none

#2368 Add debug logs for ip n on the host
  test/scripts/debugEnv.sh
Labels: release-v0.7, cherrypick-release-v0.7, release/none

#2371 update version to v0.8.0-rc0
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none
