Repository spidernet-io/spiderpool, pull requests merged in 2023-07, with the labels that each got.

#2000 e2e: optimize ci and e2e
  .github/workflows/auto-diff-k8s-ci.yaml
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/call-release-image.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-markdown.yaml
  MAINTAINERS.md
  test/Makefile
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/kruise/kruise_test.go
  test/e2e/reservedip/reservedip_test.go
Labels: pr/release/none-required, pr/ready-review

#2015 set testIPv6 to false for cilium mode
  test/e2e/common/mode.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: pr/release/none-required, pr/ready-review

#2021 fix e2e: The ipv6 address is abbreviated and the expected IP address cannot be found
  test/e2e/annotation/annotation_test.go
Labels: pr/release/none-required, pr/ready-review

#2022 fix e2e: delete the subnet, prompting that the subnet does not exist
  test/e2e/subnet/subnet_test.go
Labels: pr/release/none-required, pr/ready-review

#2001 add cncf logo in README and add code-of-conduct.md
  CODEOWNERS
  CODE_OF_CONDUCT.md
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: pr/release/doc

#2003 multus affinity
  .licenserc.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/multus-daemonset.yaml
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/command_del.go
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/unix_server.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
  cmd/spiderpool/cmd/command_test.go
  pkg/constant/k8s.go
  pkg/ipam/allocate.go
  pkg/ipam/config.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderippool_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
  pkg/openapi/unix_socket.go
  test/Makefile
  test/Makefile.defs
  test/e2e/common/constant.go
  test/scripts/install-multus.sh
  test/scripts/installTestPod.sh
Labels: pr/release/feature-new, pr/ready-review

#2032 improve README-zh_CN.md
  docs/README-zh_CN.md
Labels: pr/release/doc

#2009 fix: results report exited unexpectedly before the parallel process e…
  pkg/lock/lock_debug_test.go
Labels: pr/release/none-required, pr/ready-review

#2038 header license
  pkg/statefulsetmanager/utils.go
  pkg/utils/string/string.go
  pkg/workloadendpointmanager/utils_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager_suite_test.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
  tools/k8s-controller-gen/update-controller-gen.sh
  tools/scripts/update-codegen.sh
Labels: pr/release/none-required, pr/ready-review

#2052 update readme
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
  docs/images/cncf-cloud-gophers-transparent.png
  docs/images/overlay.jpg
  docs/images/spiderpool-arch.jpg
  docs/images/spiderpool-overlay.jpg
  docs/images/spiderpool-underlay.jpg
  docs/images/underlay.jpg
Labels: pr/release/doc

#2012 fix mutlus auto-generated cni files && opt coordinator cni config fields
  .github/workflows/auto-nightly-ci.yaml
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/README.md
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  charts/spiderpool/templates/multus-daemonset.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/values.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/command_del.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-agent/cmd/coordinator.go
  cmd/spiderpool-init/cmd/client.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/root.go
  pkg/coordinatormanager/calico_ippool_informer.go
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
  pkg/networking/ipchecking/ipchecking.go
  pkg/networking/networking/route.go
  test/Makefile
  test/scripts/install-default-cni.sh
  test/scripts/install-multus.sh
  vendor/github.com/containernetworking/cni/libcni/api.go
  vendor/github.com/containernetworking/cni/libcni/conf.go
  vendor/github.com/containernetworking/cni/pkg/invoke/args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
  vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
  vendor/github.com/containernetworking/cni/pkg/invoke/find.go
  vendor/github.com/containernetworking/cni/pkg/invoke/os_unix.go
  vendor/github.com/containernetworking/cni/pkg/invoke/os_windows.go
  vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
  vendor/modules.txt
Labels: pr/release/feature-new

#2037 cleanup dirty rule、route、neigh tables in cmdAdd
  cmd/coordinator/cmd/utils.go
  pkg/networking/networking/ip.go
  pkg/networking/networking/mac.go
Labels: pr/release/bug

#2055 fix failed to init arp client
  cmd/coordinator/cmd/command_add.go
  pkg/networking/ipchecking/ipchecking.go
Labels: pr/release/bug

#2045 implement IP allocation process document
  docs/concepts/allocation.md
Labels: pr/release/bug, pr/ready-review, kind/documentation

#2059 coordinator: cmdDel should return nil
  cmd/coordinator/cmd/command_del.go
Labels: pr/release/bug

#2058 fix IPPool crd wrong vlanID range
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderippool_types.go
Labels: pr/release/bug, pr/ready-review

#1872 e2e: add case about coordinator
  go.mod
  go.sum
  pkg/networking/gwconnection/connection.go
  test/doc/coordinator.md
  test/e2e/annotation/annotation_test.go
  test/e2e/common/constant.go
  test/e2e/common/spiderpool.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/reclaim/reclaim_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/events.go
  vendor/github.com/spidernet-io/e2eframework/framework/spidermultus.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#2036 ippool inherits subnet properties
  pkg/ippoolmanager/ippool_mutate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  test/e2e/annotation/annotation_test.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.5

#2064 title: ippool inherits subnet properties
  pkg/ippoolmanager/ippool_mutate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  test/e2e/annotation/annotation_test.go
Labels: robot-cherrypick

#2068 e2e: add spidermultusconfig e2e for spiderpool
  go.mod
  go.sum
  test/Makefile
  test/doc/spidermultus.md
  test/e2e/common/constant.go
  test/e2e/spidermultus/spidermultus_suite_test.go
  test/e2e/spidermultus/spidermultus_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/framework.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#1904 update CRD documentation
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  docs/concepts/spiderendpoint.md
  docs/concepts/spiderippool.md
  docs/concepts/spidermultusconfig.md
  docs/concepts/spiderreservedip.md
  docs/concepts/spidersubnet.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
Labels: pr/release/doc, pr/release/bug, pr/ready-review, kind/documentation

#2077 e2e fix: increase check time for multus cr rebuilds.
  test/e2e/common/constant.go
Labels: pr/release/none-required, pr/ready-review

#2071 e2e: fix ipv6 address abbreviation and supplement PodCIDRType for coordinator spec
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: pr/release/none-required, pr/ready-review

#2067 fix SpiderMultusConfig ValidatingWebhookConfiguration
  charts/spiderpool/templates/tls.yaml
  pkg/coordinatormanager/coordinator_validate.go
Labels: pr/release/none-required, pr/ready-review, kind/bug

#2082 spidermultusconfig: improve parameters validate
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_validate.go
Labels: pr/release/bug

#2073 e2e fix: the conflicting IP address cannot be the IP of the gateway or NIC
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: pr/release/none-required, pr/ready-review

#2089 update cilium field ipam.operator.clusterPoolIPv4PodCIDR to ipam.operator.clusterPoolIPv4PodCIDRList
  test/scripts/install-default-cni.sh
Labels: pr/release/none-required, pr/ready-review

#2097 update spidermultusconfig
  README-zh_CN.md
  README.md
  charts/spiderpool/README.md
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/root.go
  docs/develop/roadmap.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
Labels: pr/release/none-required

#2099 v0.6.0
  VERSION
  charts/spiderpool/Chart.yaml
  docs/develop/release.md
Labels: pr/release/none-required

#2101 fix: spidermultusconfig
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/spiderpool-init/cmd/root.go
  docs/develop/contributing.md
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/networking/networking/ip.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/spidermultus/spidermultus_test.go
  test/scripts/config-network.sh
  test/scripts/install-multus.sh
Labels: pr/release/none-required

#2106 update pages
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
  docs/concepts/metrics.md
  docs/concepts/mulltusconfig-zh_CN.md
  docs/concepts/multusconfig.md
  docs/concepts/performance-zh_CH.md
  docs/concepts/performance.md
  docs/mkdocs.yml
  docs/usage/coodinator.md
  docs/usage/coordinator.md
  docs/usage/get-started-calico-zh_CN.md
  docs/usage/get-started-calico.md
  docs/usage/ifacer-zh_CN.md
  docs/usage/ifacer.md
  docs/usage/ifcacer.md
  docs/usage/install/cloud/get-started-alibaba-zh_CN.md
  docs/usage/install/cloud/get-started-alibaba.md
  docs/usage/install/cloud/get-started-openstack-zh_CN.md
  docs/usage/install/cloud/get-started-openstack.md
  docs/usage/install/cloud/get-started-vmware-zh_CN.md
  docs/usage/install/cloud/get-started-vmware.md
  docs/usage/install/install.md
  docs/usage/install/underlay/get-started-calico-zh_CN.md
  docs/usage/install/underlay/get-started-calico.md
  docs/usage/install/underlay/get-started-cloud-zh_CN.md
  docs/usage/install/underlay/get-started-cloud.md
  docs/usage/install/underlay/get-started-kind-zh_CN.md
  docs/usage/install/underlay/get-started-kind.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/ippool-affinity-pod.md
  docs/usage/network-topology-zh_CN.md
  docs/usage/route.md
  docs/usage/spider-subnet.md
  docs/usage/statefulset.md
Labels: pr/release/none-required

#2104 add required host route and neighbor in the pod
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  pkg/networking/networking/ip.go
Labels: pr/release/none-required

#2109 robot update changelog with tag v0.6.0 to branch github_pages
  changelogs/changelog_from_v0.5.0_to_v0.6.0.md
Labels: pr/release/robot_update_githubpage

#1960 [docs]: add cloud get started for spiderpool
  docs/example/alicloud-ccm/cloud-controller-manager.yaml
  docs/images/alicloud-k8s-network.png
  docs/images/alicloud-loadbalancer.png
  docs/images/alicloud-natgateway.png
  docs/images/alicloud-network-web.png
  docs/usage/install/cloud/get-started-alibaba-zh_CN.md
  docs/usage/install/cloud/get-started-alibaba.md
  docs/usage/network-topology.md
Labels: pr/release/none-required, pr/ready-review, kind/documentation

#2117 fix SpiderSubnet CRD vlanID
  charts/spiderpool/crds/spiderpool.spidernet.io_spidersubnets.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidersubnet_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
Labels: pr/release/bug, pr/ready-review

#1959 docs: coordinator config
  docs/mkdocs.yml
  docs/reference/crd-spidercoordinator.md
  docs/usage/coordinator-zh_CN.md
  docs/usage/ifacer-zh_CN.md
  docs/usage/ifacer.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-sriov.md
Labels: pr/release/doc
