Repository spidernet-io/spiderpool, pull requests merged in 2023-04, with the labels that each got.

#1600 [Docs] Fix some format and indentations
  docs/README.md
  docs/mkdocs.yml
  docs/usage/get-started-calico-zh_CN.md
  docs/usage/get-started-calico.md
  docs/usage/get-started-macvlan.md
  docs/usage/get-started-sriov-zh_CN.md
  docs/usage/get-started-sriov.md
  docs/usage/get-started-weave.md
  docs/usage/ippool-affinity-pod.md
  docs/usage/upgrade.md
  test/yamls/grafanadashboards.yaml
  test/yamls/monitoring.coreos.com_podmonitors.yaml
  test/yamls/monitoring.coreos.com_probes.yaml
  test/yamls/monitoring.coreos.com_prometheusrules.yaml
  test/yamls/monitoring.coreos.com_servicemonitors.yaml
Labels: pr/release/doc, kind/documentation

#1598 Update get-started-macvlan-zh_CN.md
  docs/usage/get-started-macvlan-zh_CN.md
Labels: pr/release/doc, kind/documentation

#1596 code optimization with third-party controller SpiderSunet feature
  pkg/ipam/pool_selections.go
  pkg/ipam/utils.go
Labels: pr/release/none-required, pr/ready-review

#1592 Synchronise the e2eframework and check the readiness of the spiderpool controller.
  go.mod
  go.sum
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/kubectl/LICENSE
  vendor/k8s.io/kubectl/pkg/util/podutils/podutils.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#1614 improve readiness probe logs
  cmd/spiderpool-agent/cmd/runtime_status.go
  cmd/spiderpool-controller/cmd/runtime_status.go
Labels: pr/release/none-required, pr/ready-review

#1611 forbidden modifying auto-created IPPool by hand
  pkg/ippoolmanager/ippool_subnet_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
Labels: pr/release/bug, pr/ready-review

#1616 add debug time for issue 1612
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
Labels: pr/release/none-required, pr/ready-review

#1624 fix IP GC health inaccurate check
  cmd/spiderpool-controller/cmd/runtime_status.go
  pkg/gcmanager/gc_manager.go
Labels: pr/release/bug, pr/ready-review

#1619 support third-party auto-created pool delete
  charts/spiderpool/templates/role.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/applicationcontroller/applicationinformers/utils.go
  pkg/ipam/pool_selections.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager.go
  test/e2e/kruise/kruise_test.go
  vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go
  vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go
  vendor/modules.txt
Labels: pr/release/feature-new, pr/ready-review

#1628 fix: SpiderSubnet or SpiderIPPool can use `spec.routes` to configure duplicate routes or default route
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook_test.go
  test/e2e/subnet/subnet_test.go
Labels: pr/release/bug, pr/ready-review

#1627 fix: The log of merging `spec.ips` and `spec.excludeIPs` in the mutating webhook is not accurate
  pkg/ippoolmanager/ippool_mutate.go
  pkg/reservedipmanager/reservedip_mutate.go
  pkg/subnetmanager/subnet_mutate.go
Labels: pr/release/none-required, pr/ready-review

#1632 E2E: Automatic pools of third party controllers can be reclaimed automatically
  test/e2e/kruise/kruise_test.go
Labels: pr/release/none-required, pr/ready-review

#1648 improve ip gc logs
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/pod_informer.go
Labels: pr/release/none-required, pr/ready-review

#1660 add readiness initialDelaySeconds for spiderpool-controller
  charts/spiderpool/templates/deployment.yaml
  cmd/spiderpool-agent/cmd/runtime_status.go
  cmd/spiderpool-controller/cmd/runtime_status.go
  pkg/gcmanager/gc_manager.go
Labels: pr/release/bug, pr/ready-review

#1661 fix IP gc
  pkg/gcmanager/pod_informer.go
Labels: pr/release/bug, pr/ready-review

#1613 docs: add get started for kind
  Makefile
  Makefile.defs
  docs/example/multi-interfaces-annotation/subnet-test-deploy.yaml
  docs/mkdocs.yml
  docs/usage/get-started-calico-zh_CN.md
  docs/usage/get-started-kind-zh_CN.md
  docs/usage/get-started-kind.md
  docs/usage/get-started-macvlan-zh_CN.md
  docs/usage/get-started-macvlan.md
  docs/usage/get-started-sriov-zh_CN.md
  docs/usage/get-started-sriov.md
  docs/usage/get-started-weave-zh_CN.md
  docs/usage/install.md
  docs/usage/multi-interfaces-annotation.md
  test/Makefile.defs
Labels: pr/release/none-required, pr/ready-review

#1664 make it takes not effect when app subnet changed in SpiderSubnet feature
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.4

#1666 fix IP GC doesn't trace statefulset terminating pod issue
  docs/usage/gc.md
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/tracePod_worker.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.4

#1667 add kubernetes StatefulSet Start ordinal support
  pkg/statefulsetmanager/sts_manager.go
  pkg/statefulsetmanager/sts_manager_test.go
Labels: pr/release/feature-new, pr/ready-review, cherrypick-release-v0.4

#1668 title: add kubernetes StatefulSet Start ordinal support
  pkg/statefulsetmanager/sts_manager.go
  pkg/statefulsetmanager/sts_manager_test.go
Labels: pr/ready-review, robot-cherrypick

#1665 title: make it takes not effect when app subnet changed in SpiderSubnet feature
  pkg/subnetmanager/subnet_manager.go
Labels: pr/ready-review, robot-cherrypick

#1669 fix: Pod of spiderpool-agent restarts too slowly when node restart
  Makefile
  cmd/spiderpool-agent/cmd/daemon.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.4

#1670 title: fix: Pod of spiderpool-agent restarts too slowly when node restart
  Makefile
  cmd/spiderpool-agent/cmd/daemon.go
Labels: pr/release/bug, pr/ready-review, robot-cherrypick

#1644 docs:add get started for ovs-cni
  docs/mkdocs.yml
  docs/usage/get-started-ovs-zh_CN.md
  docs/usage/get-started-ovs.md
  docs/usage/install.md
Labels: pr/release/none-required, pr/ready-review

#1671 fix: The gateway addresses of SpiderSubnet and SpiderIPPool conflict with `spec.ips`
  pkg/ip/iprange.go
  pkg/ip/iprange_test.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook_test.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.4

#1673 title: fix: The gateway addresses of SpiderSubnet and SpiderIPPool conflict with `spec.ips`
  pkg/ip/iprange.go
  pkg/ip/iprange_test.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook_test.go
Labels: pr/release/bug, pr/ready-review, robot-cherrypick

#1677 support cosign for image signature and SBOM
  .github/workflows/call-release-image.yaml
Labels: pr/release/feature-new

#1672 docs: add route demo
  docs/example/ippool-affinity-node/master-ipv4-ippool.yaml
  docs/example/ippool-affinity-node/worker-ipv4-ippool.yaml
  docs/example/ippool-affinity-pod/occupied-static-ipv4-ippool.yaml
  docs/example/ippool-affinity-pod/shared-static-ipv4-ippool.yaml
  docs/example/ippool-affinity-pod/static-ipv4-subnet.yaml
  docs/example/ippool-affnity-namespace/test-ns-ipv4-ippool.yaml
  docs/example/ippool-multi/test-ipv4-ippools.yaml
  docs/example/ippool-namespace/ns1-default-ipv4-ippool.yaml
  docs/example/multi-interfaces-annotation/different-segment-ipv4-ippools.yaml
  docs/example/multi-interfaces-annotation/different-segment-ipv4-subnets.yaml
  docs/example/reserved-ip/already-in-use-ippool.yaml
  docs/example/reserved-ip/created-by-someone-else-ippool.yaml
  docs/example/reserved-ip/not-use-excludeips-ippool.yaml
  docs/example/reserved-ip/test-ipv4-ippool.yaml
  docs/example/reserved-ip/test-ipv4-reservedip.yaml
  docs/example/reserved-ip/use-excludeips-ippool.yaml
  docs/example/route/ippool-route-deploy.yaml
  docs/example/route/ippool-route.yaml
  docs/example/route/subnet-route-deploy.yaml
  docs/example/route/subnet-route.yaml
  docs/example/spider-subnet/multiple-interfaces.yaml
  docs/example/spider-subnet/subnet-demo.yaml
  docs/mkdocs.yml
  docs/usage/get-started-calico-zh_CN.md
  docs/usage/get-started-calico.md
  docs/usage/get-started-macvlan-zh_CN.md
  docs/usage/get-started-macvlan.md
  docs/usage/get-started-sriov-zh_CN.md
  docs/usage/get-started-sriov.md
  docs/usage/get-started-weave-zh_CN.md
  docs/usage/get-started-weave.md
  docs/usage/ippool-affinity-namespace.md
  docs/usage/ippool-affinity-node.md
  docs/usage/ippool-affinity-pod.md
  docs/usage/reserved-ip.md
  docs/usage/route.md
  docs/usage/third-party-controller.md
Labels: pr/release/none-required, pr/ready-review

#1678 add debug level metrics
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/metrics_server.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-controller/cmd/metrics_server.go
  docs/concepts/metrics.md
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/metric/metrics.go
  pkg/metric/metrics_instance.go
  pkg/metric/metrics_ipam.go
  pkg/subnetmanager/subnet_informer.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  pkg/subnetmanager/subnet_validate.go
Labels: pr/release/feature-new, pr/ready-review

#1679 remove todo comments
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/health.go
  cmd/spiderpool-agent/cmd/ipam.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-controller/cmd/runtime_status.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/utils.go
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/none-required, pr/ready-review, enhancement

#1681 docs: Modify name specifications and maintain consistency between Chinese and English documents
  README-zh_CN.md
  docs/usage/get-started-calico.md
  docs/usage/get-started-macvlan.md
  docs/usage/get-started-sriov.md
  docs/usage/get-started-weave.md
Labels: pr/release/doc, pr/release/none-required

#1676 add grafana dashaboard
  charts/spiderpool/README.md
  charts/spiderpool/templates/grafanaDashboard.yaml
  charts/spiderpool/values.yaml
  pkg/metric/metrics_instance.go
Labels: pr/release/feature-new, pr/ready-review, cherrypick-release-v0.4

#1684 title: add grafana dashaboard
  charts/spiderpool/README.md
  charts/spiderpool/templates/grafanaDashboard.yaml
  charts/spiderpool/values.yaml
  pkg/metric/metrics_instance.go
Labels: pr/release/feature-new, pr/ready-review, robot-cherrypick

#1685 Revert "add grafana dashaboard"
  charts/spiderpool/README.md
  charts/spiderpool/templates/grafanaDashboard.yaml
  charts/spiderpool/values.yaml
  pkg/metric/metrics_instance.go
Labels: pr/release/none-required, pr/ready-review

#1687 docs: typo
  docs/usage/get-started-sriov.md
Labels: pr/release/doc, pr/release/none-required

#1683 fix metric record
  pkg/ippoolmanager/ippool_informer.go
  pkg/subnetmanager/subnet_informer.go
Labels: pr/release/none-required, pr/ready-review, kind/bug

#1691 fix metric record panic
  charts/spiderpool/README.md
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  pkg/ippoolmanager/ippool_informer.go
  pkg/subnetmanager/subnet_informer.go
  test/Makefile
Labels: pr/release/none-required, pr/ready-review, kind/bug

#1693 fix auto-created pool reconcile algorithm
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/bug, pr/ready-review, cherrypick-release-v0.4

#1694 title: fix auto-created pool reconcile algorithm
  pkg/subnetmanager/subnet_manager.go
Labels: pr/release/bug, pr/ready-review, robot-cherrypick

#1696 docs: Add CNI performance test data in IPv4 single stack case
  docs/usage/performance-zh_CH.md
  docs/usage/performance.md
Labels: pr/release/doc, pr/ready-review

#1708 fix update githubpages ci
  .github/workflows/call-update-githubpages.yaml
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.4

#1709 title: fix update githubpages ci
  .github/workflows/call-update-githubpages.yaml
Labels: pr/release/none-required, pr/ready-review, robot-cherrypick

#1713 fix ci
  .github/workflows/call-release-changelog.yaml
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.4

#1716 robot update changelog with tag v0.4.1 to branch github_pages
  changelogs/changelog_from_v0.4.0_to_v0.4.1.md
Labels: pr/release/robot_update_githubpage

#1715 robot update chart and website from to branch github_pages
  docs/404.html
  docs/charts/spiderpool-0.4.1.tgz
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/metrics/index.html
  docs/concepts/spiderendpoint/index.html
  docs/concepts/spiderippool/index.html
  docs/concepts/spiderreservedip/index.html
  docs/concepts/spidersubnet/index.html
  docs/develop/CODE-OF-CONDUCT/index.html
  docs/develop/contributing/index.html
  docs/develop/release/index.html
  docs/develop/roadmap/index.html
  docs/develop/swagger_openapi/index.html
  docs/example/multi-interfaces-annotation/macvlan-cni-default.yaml
  docs/images/spiderpoolWithName.svg
  docs/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/certificate/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/gc/index.html
  docs/usage/get-started-calico-zh_CN/index.html
  docs/usage/get-started-calico/index.html
  docs/usage/get-started-macvlan-zh_CN/index.html
  docs/usage/get-started-macvlan/index.html
  docs/usage/get-started-sriov-zh_CN/index.html
  docs/usage/get-started-sriov/index.html
  docs/usage/get-started-weave-zh_CN/index.html
  docs/usage/get-started-weave/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namespace/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/performance-zh_CH/index.html
  docs/usage/performance/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/route/index.html
  docs/usage/spider-subnet/index.html
  docs/usage/statefulset/index.html
  docs/usage/third-party-controller/index.html
  docs/usage/upgrade/index.html
Labels: pr/release/robot_update_githubpage

#1718 Revert "robot update chart and website from to branch github_pages"
  docs/404.html
  docs/charts/spiderpool-0.4.1.tgz
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/metrics/index.html
  docs/concepts/spiderendpoint/index.html
  docs/concepts/spiderippool/index.html
  docs/concepts/spiderreservedip/index.html
  docs/concepts/spidersubnet/index.html
  docs/develop/CODE-OF-CONDUCT/index.html
  docs/develop/contributing/index.html
  docs/develop/release/index.html
  docs/develop/roadmap/index.html
  docs/develop/swagger_openapi/index.html
  docs/example/multi-interfaces-annotation/macvlan-cni-default.yaml
  docs/images/spiderpoolWithName.svg
  docs/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/certificate/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/gc/index.html
  docs/usage/get-started-calico-zh_CN/index.html
  docs/usage/get-started-calico/index.html
  docs/usage/get-started-macvlan-zh_CN/index.html
  docs/usage/get-started-macvlan/index.html
  docs/usage/get-started-sriov-zh_CN/index.html
  docs/usage/get-started-sriov/index.html
  docs/usage/get-started-weave-zh_CN/index.html
  docs/usage/get-started-weave/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namespace/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/performance-zh_CH/index.html
  docs/usage/performance/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/route/index.html
  docs/usage/spider-subnet/index.html
  docs/usage/statefulset/index.html
  docs/usage/third-party-controller/index.html
  docs/usage/upgrade/index.html
Labels: pr/release/none-required, pr/ready-review

#1719 Revert "robot update changelog from tag v0.4.0 to tag v0.4.1"
  changelogs/changelog_from_v0.4.0_to_v0.4.1.md
Labels: pr/release/none-required, pr/ready-review

#1721 robot update chart and website from to branch github_pages
  docs/404.html
  docs/charts/spiderpool-0.4.1.tgz
  docs/cmdref/spiderpool-agent/index.html
  docs/cmdref/spiderpool-controller/index.html
  docs/cmdref/spiderpoolctl/index.html
  docs/concepts/allocation/index.html
  docs/concepts/annotation/index.html
  docs/concepts/arch/index.html
  docs/concepts/config/index.html
  docs/concepts/gc/index.html
  docs/concepts/metrics/index.html
  docs/concepts/spiderendpoint/index.html
  docs/concepts/spiderippool/index.html
  docs/concepts/spiderreservedip/index.html
  docs/concepts/spidersubnet/index.html
  docs/develop/CODE-OF-CONDUCT/index.html
  docs/develop/contributing/index.html
  docs/develop/release/index.html
  docs/develop/roadmap/index.html
  docs/develop/swagger_openapi/index.html
  docs/example/multi-interfaces-annotation/macvlan-cni-default.yaml
  docs/images/spiderpoolWithName.svg
  docs/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/certificate/index.html
  docs/usage/cli/index.html
  docs/usage/debug/index.html
  docs/usage/gc/index.html
  docs/usage/get-started-calico-zh_CN/index.html
  docs/usage/get-started-calico/index.html
  docs/usage/get-started-macvlan-zh_CN/index.html
  docs/usage/get-started-macvlan/index.html
  docs/usage/get-started-sriov-zh_CN/index.html
  docs/usage/get-started-sriov/index.html
  docs/usage/get-started-weave-zh_CN/index.html
  docs/usage/get-started-weave/index.html
  docs/usage/install/index.html
  docs/usage/ippool-affinity-namespace/index.html
  docs/usage/ippool-affinity-node/index.html
  docs/usage/ippool-affinity-pod/index.html
  docs/usage/ippool-multi/index.html
  docs/usage/ippool-namespace/index.html
  docs/usage/ipv6/index.html
  docs/usage/multi-interfaces-annotation/index.html
  docs/usage/performance-zh_CH/index.html
  docs/usage/performance/index.html
  docs/usage/reserved-ip/index.html
  docs/usage/route/index.html
  docs/usage/spider-subnet/index.html
  docs/usage/statefulset/index.html
  docs/usage/third-party-controller/index.html
  docs/usage/upgrade/index.html
Labels: pr/release/robot_update_githubpage

#1726 change the trivy version from latest to 0.36.0
  Makefile
  Makefile.defs
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.4

#1727 title: change the trivy version from latest to 0.36.0
  Makefile
  Makefile.defs
Labels: pr/release/none-required, pr/ready-review, robot-cherrypick

#1729 docs: Add performance test data for CNIs in fault recovery case
  docs/develop/release.md
  docs/usage/performance-zh_CH.md
  docs/usage/performance.md
Labels: pr/release/doc, pr/ready-review

#1728 bump spiderpool to v0.4.1 for main branch
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#1725 SpiderSubnet auto-created IPPool reuse
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderippools.yaml
  pkg/applicationcontroller/app_controller.go
  pkg/applicationcontroller/applicationinformers/utils.go
  pkg/applicationcontroller/applicationinformers/utils_test.go
  pkg/constant/k8s.go
  pkg/gcmanager/gc_manager.go
  pkg/ipam/allocate.go
  pkg/ipam/pool_selections.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/ippoolmanager/utils.go
  pkg/ippoolmanager/utils_test.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderippool_types.go
  pkg/subnetmanager/subnet_manager.go
  pkg/types/k8s.go
  test/e2e/kruise/kruise_test.go
Labels: pr/release/feature-new, pr/ready-review

#1730 add unit test for CNI cmdAdd and cmdDel
  cmd/spiderpool/cmd/cmd_suite_test.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_delete.go
  cmd/spiderpool/cmd/command_test.go
  go.mod
  go.sum
  vendor/github.com/containernetworking/plugins/LICENSE
  vendor/github.com/containernetworking/plugins/pkg/ns/README.md
  vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/bad_reader.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/cmd.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/dns.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/netns_linux.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/ping.go
  vendor/github.com/containernetworking/plugins/pkg/testutils/testing.go
  vendor/github.com/onsi/gomega/ghttp/handlers.go
  vendor/github.com/onsi/gomega/ghttp/test_server.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#1731 release v0.5.0-rc0
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/release/none-required, pr/ready-review

#1732 typo ci
  .github/workflows/call-release-image.yaml
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.5

#1733 title: typo ci
  .github/workflows/call-release-image.yaml
Labels: pr/release/none-required, pr/ready-review, robot-cherrypick

#1734 fix ci typo
  .github/workflows/call-release-image.yaml
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.5

#1735 title: fix ci typo
  .github/workflows/call-release-image.yaml
Labels: pr/release/none-required, pr/ready-review, robot-cherrypick

#1737 robot update changelog with tag v0.5.0-rc0 to branch github_pages
  changelogs/changelog_from_v0.4.0_to_v0.5.0-rc0.md
Labels: pr/release/robot_update_githubpage

#1738 docs: Update docs concepts/annotation.md
  docs/concepts/annotation.md
Labels: pr/release/none-required, pr/ready-review

#1740 add ippool-informer unit test
  pkg/ippoolmanager/ippool_informer_test.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: pr/release/none-required, pr/ready-review

#1739 modify github document
  docs/mkdocs.yml
Labels: pr/release/none-required, pr/ready-review, cherrypick-release-v0.5

#1742 supplement subnet-informer unit test
  pkg/ippoolmanager/ippool_informer_test.go
  pkg/subnetmanager/subnet_informer_test.go
  pkg/subnetmanager/subnet_manager_suite_test.go
Labels: pr/release/none-required, pr/ready-review

#1743 supplement subnet manager unit test
  pkg/subnetmanager/subnet_manager_test.go
Labels: pr/release/none-required, pr/ready-review
