Repository spidernet-io/spiderpool, pull requests merged in 2024-09, with the labels that each got.

#3986 coordinator: Fix error policy routing table when pod has multi nics
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-agent/cmd/coordinator.go
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/networking/networking/ip.go
  pkg/networking/networking/route.go
  test/doc/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/reclaim/reclaim_test.go
  test/scripts/debugEnv.sh
Labels: release/bug, release-v0.8

#3970 coordinator should only set rp_filter for pod not the node
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/spiderpool-agent/cmd/coordinator.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/reference/crd-spidercoordinator.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/utils.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug

#3988 Fix：the chart value tuneSysctlConfig does not work
  charts/spiderpool/templates/configmap.yaml
  test/Makefile
  test/scripts/preCheckClusterReady.sh
Labels: cherrypick-main, release/bug, cherrypick-release-v0.8, cherrypick-release-v1.0

#3991 Fix：the chart value tuneSysctlConfig does not work
  charts/spiderpool/templates/configmap.yaml
  test/Makefile
  test/scripts/preCheckClusterReady.sh
Labels: robot-cherrypick, release/bug

#3995 Release-0.8: bump version to 0.8.8
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none, release-v0.8

#4005 release-0.9: bump version to 0.9.6
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none, release-v0.9

#4010 typo
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
Labels: release/none

#4013 Update GOMAXPROCS configuration
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  go.mod
  go.sum
  vendor/go.uber.org/automaxprocs/LICENSE
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/modules.txt
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v1.0

#4014 Update GOMAXPROCS configuration
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  go.mod
  go.sum
  vendor/go.uber.org/automaxprocs/LICENSE
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/modules.txt
Labels: release/bug

#4016 Update GOMAXPROCS configuration
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  go.mod
  go.sum
  vendor/go.uber.org/automaxprocs/LICENSE
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/modules.txt
Labels: robot-cherrypick, release/bug

#3925 fix: cannot uninstall spiderpool when sriovOperatorConfig is installed
  .github/workflows/e2e-init.yaml
  Makefile
  charts/spiderpool/templates/deleteHook.yaml
  charts/spiderpool/templates/role.yaml
  cmd/spiderpool-controller/cmd/clean.go
  pkg/constant/k8s.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  pkg/k8s/utils/utils.go
  test/Makefile
  test/Makefile.defs
  test/scripts/debugEnv.sh
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4030 fix: cannot uninstall spiderpool when sriovOperatorConfig is installed
  .github/workflows/e2e-init.yaml
  Makefile
  charts/spiderpool/templates/deleteHook.yaml
  charts/spiderpool/templates/role.yaml
  cmd/spiderpool-controller/cmd/clean.go
  pkg/constant/k8s.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  pkg/k8s/utils/utils.go
  test/Makefile
  test/Makefile.defs
  test/scripts/debugEnv.sh
Labels: robot-cherrypick, release/bug, release-v1.0

#4035 Add a cluster precheck for tuneSysctlConfig
  test/Makefile
  test/scripts/installTestPod.sh
  test/scripts/preCheckClusterReady.sh
Labels: release/none

#4034 Add a cluster precheck for tuneSysctlConfig
  test/Makefile
  test/scripts/installTestPod.sh
  test/scripts/preCheckClusterReady.sh
Labels: release/none, release-v1.0

#4011 Optimize upgrade CI and clarify failed steps
  .github/workflows/auto-upgrade-ci.yaml
Labels: release/none

#4031 cherry-pick some CI changes
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  Makefile
  test/Makefile
  test/scripts/debugEnv.sh
Labels: robot-cherrypick, release/none, release-v0.9

#4032 cherry-pick some CI changes
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  Makefile
  test/Makefile
  test/scripts/debugEnv.sh
Labels: robot-cherrypick, release/none, release-v0.8

#4046 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
  go.mod
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
Labels: release/none, pr/release/robot_update_version

#4040 Update GOMAXPROCS configuration
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  go.mod
  go.sum
  vendor/go.uber.org/automaxprocs/LICENSE
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/modules.txt
Labels: release/bug

#4052 robot updated golang version
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
Labels: release/none, pr/release/robot_update_version

#4054 optimizate auto upgrade golang logic
  .github/workflows/update-golang-version.yaml
Labels: release/none

#4062 Fix panic when create spidermultusconfig with nil podRPFilter in validate webhook
  pkg/coordinatormanager/coordinator_validate.go
  pkg/multuscniconfig/multusconfig_mutate.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4049 Optimize setup kind cluster debug log
  .github/workflows/e2e-init.yaml
  test/Makefile
Labels: release/none

#3926 Added debug log of AllocatedIPCount of ippool
  pkg/ippoolmanager/ippool_manager.go
  test/e2e/reclaim/reclaim_test.go
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4078 Fix panic when create spidermultusconfig with nil podRPFilter in validate webhook
  pkg/coordinatormanager/coordinator_validate.go
  pkg/multuscniconfig/multusconfig_mutate.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: robot-cherrypick, release/bug

#4082 Added debug log of AllocatedIPCount of ippool
  pkg/ippoolmanager/ippool_manager.go
  test/e2e/reclaim/reclaim_test.go
Labels: robot-cherrypick, release/none

#4081 Added debug log of AllocatedIPCount of ippool
  pkg/ippoolmanager/ippool_manager.go
  test/e2e/reclaim/reclaim_test.go
Labels: robot-cherrypick, release/none

#4079 Fix panic when creating spidermultusconfig with nil podRPFilter in validate webhook
  pkg/coordinatormanager/coordinator_validate.go
  pkg/multuscniconfig/multusconfig_mutate.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: robot-cherrypick, release/bug

#4094 typo: spec.disable description error
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4103 typo: spec.disable description error
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
Labels: robot-cherrypick, release/none

#4105 typo: spec.disable description error
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
Labels: robot-cherrypick, release/none

#4104 typo: spec.disable description error
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
Labels: robot-cherrypick, release/none

#4098 Fix wrong validate for unicast podMACPrefix when creating spiderMultusConfig
  pkg/coordinatormanager/coordinator_validate.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4108 Fix wrong validate for unicast podMACPrefix when creating spiderMultusConfig
  pkg/coordinatormanager/coordinator_validate.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: robot-cherrypick, release/bug

#4109 Fix wrong validate for unicast podMACPrefix when creating spiderMultusConfig
  pkg/coordinatormanager/coordinator_validate.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: robot-cherrypick, release/bug

#4099 Fix panic in validate webhook for creating spidermultusconfig
  pkg/coordinatormanager/coordinator_validate.go
  pkg/multuscniconfig/multusconfig_mutate.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/bug

#4106 [docs] Fix indentations in ai/get-started-macvlan
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
Labels: kind/doc, release/none, cherrypick-release-v1.0

#4115 bump version to 0.9.7
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none, release-v0.9

#4074 optimizate spiderpool upgrade CI
  .github/workflows/auto-upgrade-ci.yaml
  Makefile
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
  test/Makefile
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4126 fix cilium installation --set tunnel
  test/scripts/install-default-cni.sh
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4128 [docs] Fix indentations in ai/get-started-macvlan
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
Labels: robot-cherrypick, release/none, release-v1.0

#4123 add delete spiderclaimparameters for cleanup scripts
  tools/scripts/cleanCRD.sh
Labels: release/none, cherrypick-release-v0.9, cherrypick-release-v1.0

#4138 fix cilium installation --set tunnel
  test/scripts/install-default-cni.sh
Labels: robot-cherrypick, release/none

#4129 robot-cherrypick: optimizate spiderpool upgrade CI
  .github/workflows/auto-upgrade-ci.yaml
  Makefile
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
  pkg/coordinatormanager/coordinator_validate.go
  test/Makefile
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
  test/scripts/install-default-cni.sh
Labels: robot-cherrypick, release/none, release-v0.8

#4137 fix cilium installation --set tunnel
  test/scripts/install-default-cni.sh
Labels: robot-cherrypick, release/none

#4140 add delete spiderclaimparameters for cleanup scripts
  tools/scripts/cleanCRD.sh
Labels: robot-cherrypick, release/none

#4139 add delete spiderclaimparameters for cleanup scripts
  tools/scripts/cleanCRD.sh
Labels: robot-cherrypick, release/none
