Repository spidernet-io/spiderpool, pull requests merged in 2024-07, with the labels that each got.

#3677 fix: CI failed to download the file
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/auto-version-release.yaml
  .github/workflows/build-image-base.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/build-image-plugins.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/trivy-scan-image.yaml
Labels: pr/dependabot/github-actions, release/none

#3687 Revert build(deps): bump actions/download-artifact and actions/upload-artifact from 3 to 4
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/auto-version-release.yaml
  .github/workflows/build-image-base.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/build-image-plugins.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-release-image.yaml
  .github/workflows/call-update-githubpages.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-yaml.yaml
  .github/workflows/trivy-scan-image.yaml
  .github/workflows/update-chart-readme.yml
Labels: release/none

#3692 Optimize clean job to use host network
  charts/spiderpool/templates/deleteHook.yaml
Labels: release/bug, cherrypick-release-v1.0

#3673 docs: add doc for ib-kubernetes and ufm
  docs/images/ib-kubernetes.png
  docs/usage/rdma-ib-zh_CN.md
  docs/usage/rdma-ib.md
Labels: release/none

#3697 Optimize clean job to use host network
  charts/spiderpool/templates/deleteHook.yaml
Labels: robot-cherrypick, release/bug

#3705 coordinator: improve error message for gateway detecting gateway
  pkg/networking/gwconnection/connection.go
Labels: release/none

#3690 ci fix: Optimize robot to update kind/node version
  .github/workflows/auto-diff-k8s-ci.yaml
  test/scripts/update-kindnode-version.sh
Labels: release/none

#3709 robot updates kind node version in k8s matrix test
  .github/workflows/auto-diff-k8s-ci.yaml
Labels: pr/dependabot/github-actions, release/none

#3708 CI: add pr reviewer
  .github/workflows/auto-diff-k8s-ci.yaml
Labels: release/none

#3706 Optimize clean scripts
  docs/usage/install/uninstall-zh_CN.md
  docs/usage/install/uninstall.md
  tools/scripts/cleanCRD.sh
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#3714 Optimize clean scripts
  docs/usage/install/uninstall-zh_CN.md
  docs/usage/install/uninstall.md
  tools/scripts/cleanCRD.sh
Labels: robot-cherrypick, release/none

#3686 fix: fail to access NodePort when pod owning multiple network cards
  cmd/coordinator/cmd/utils.go
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/networking/networking/route.go
  test/doc/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#3715 [cherry-pick] optimize clean scripts
  docs/mkdocs.yml
  docs/usage/install/uninstall-zh_CN.md
  docs/usage/install/uninstall.md
  tools/scripts/cleanCRD.sh
Labels: release/none

#3733 update version of CNI plugins
  .github/workflows/build-image-plugins.yaml
  .github/workflows/update-cniplugins-version.yaml
  charts/spiderpool/README.md
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/values.yaml
  images/spiderpool-plugins/Dockerfile
  images/spiderpool-plugins/entrypoint.sh
  images/spiderpool-plugins/version.sh
  tools/scripts/updateLatestCniPluginVersion.sh
Labels: release/feature-new

#3729 delete crd ovsnetworks.sriovnetwork.openshift.io of sriov-network-operator
  tools/scripts/cleanCRD.sh
Labels: release/none

#3704 Optimize cleangateway docs
  docs/reference/annotation.md
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3688 e2e fix: spiderpoolcontroller Pod termination failed
  test/e2e/reclaim/reclaim_test.go
Labels: release/none

#3738 Optimize cleangateway docs
  docs/reference/annotation.md
Labels: robot-cherrypick, release/none

#3739 Optimize cleangateway docs
  docs/reference/annotation.md
Labels: robot-cherrypick, release/none

#3756 [cherry-pick]e2e fix: skip About passt network core binding e2e
  test/e2e/kubevirt/kubevirt_test.go
Labels: kind/cleanup, kind/test, release/none, release-v0.9

#3752 fix: Missing GLIBC dynamic dependency makes ovs binary unavailable
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
  images/spiderpool-plugins/Dockerfile
Labels: release/bug

#3759 replace zh-cn text with english in blogs
  docs/concepts/blog.md
Labels: kind/doc, release/none, cherrypick-release-v0.9

#3757 [cherry-pick] e2e fix: skip About passt network core binding e2e
  test/e2e/kubevirt/kubevirt_test.go
Labels: kind/cleanup, release/none, release-v0.8

#3743 e2e fix: skip About passt network core binding e2e
  test/e2e/kubevirt/kubevirt_test.go
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#3763 replace zh-cn text with english in blogs
  docs/concepts/blog.md
Labels: robot-cherrypick, kind/doc, release/none

#3726 remove CRD installed by sriov-network-operator when uninstalling
  cmd/spiderpool-controller/cmd/clean.go
  pkg/k8s/utils/utils.go
  tools/scripts/cleanCRD.sh
Labels: release/bug

#3762 Change the type of cilium bpf.vlanBypass to list
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  test/scripts/install-default-cni.sh
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#3775 Change the type of cilium bpf.vlanBypass to list
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  test/scripts/install-default-cni.sh
Labels: robot-cherrypick, release/none

#3774 Change the type of cilium bpf.vlanBypass to list
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  test/scripts/install-default-cni.sh
Labels: robot-cherrypick, release/none

#3779 optimize ovs config document
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
Labels: kind/doc, release/none

#3732 init-pod: support helm wait and fix installation block when agent pods fails to run
  charts/spiderpool/README.md
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/client.go
  cmd/spiderpool-init/cmd/root.go
  test/scripts/debugEnv.sh
  test/scripts/install-multus.sh
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#3800 bump version to v1.0.0-rc1
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#3758 pod launched by unexpected CNI when the health checking of the agent fails and multus.conf is lost
  charts/spiderpool/templates/daemonset.yaml
  test/Makefile
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#3809 pod launched by unexpected CNI when the health checking of the agent fails and multus.conf is lost
  charts/spiderpool/templates/daemonset.yaml
  test/Makefile
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: robot-cherrypick, release/bug
