Repository spidernet-io/spiderpool, pull requests merged in 2024-08, with the labels that each got.

#3815 fix: fail to access NodePort when pod owning multiple network cards
  cmd/coordinator/cmd/utils.go
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/networking/networking/route.go
  test/doc/coordinator.md
  test/e2e/common/constant.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/scripts/install-default-cni.sh
Labels: release/bug

#3814 fix: fail to access NodePort when pod owning multiple network card
  cmd/coordinator/cmd/utils.go
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/networking/networking/route.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug

#3813 pod launched by unexpected CNI when the health checking of the agent fails and multus.conf is lost
  charts/spiderpool/templates/daemonset.yaml
  test/Makefile
Labels: release/bug

#3810 init-pod: fix installtion block for agent pods can't running
  charts/spiderpool/README.md
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/client.go
  cmd/spiderpool-init/cmd/root.go
  test/scripts/debugEnv.sh
  test/scripts/install-multus.sh
Labels: release/bug

#3811 init-pod: fix installtion block for agent pods can't running
  charts/spiderpool/README.md
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-init/cmd/client.go
  cmd/spiderpool-init/cmd/root.go
  test/scripts/debugEnv.sh
  test/scripts/install-multus.sh
Labels: release/bug

#3812 pod launched by unexpected CNI when the health checking of the agent fails and multus.conf is lost
  charts/spiderpool/templates/daemonset.yaml
  test/Makefile
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug

#3819 fix: unittest reports occasional upload failures
  .github/workflows/lint-golang.yaml
Labels: release/none, release-v0.8

#3830 ci: typo
  .github/workflows/auto-pr-ci.yaml
Labels: release/none

#3820 docs: removed long-term unmaintained versions from the readme file
  README-zh_CN.md
  README.md
Labels: release/none, cherrypick-release-v0.9, cherrypick-release-v1.0

#3835 docs: removed long-term unmaintained versions from the readme file
  README-zh_CN.md
  README.md
Labels: robot-cherrypick, release/none

#3772 spiderpool-agent: support to configure the sysctl config for node
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/daemon.go
  docs/reference/spiderpool-agent.md
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
  pkg/networking/sysctl/sysctl.go
  pkg/types/k8s.go
  test/Makefile
  test/scripts/install-multus.sh
Labels: release/feature-new, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#3839 spiderpool-agent: support to configure the sysctl config for node
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/daemon.go
  docs/reference/spiderpool-agent.md
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
  pkg/networking/sysctl/sysctl.go
  pkg/types/k8s.go
  test/Makefile
  test/scripts/install-multus.sh
Labels: robot-cherrypick, release/feature-new

#3842 spiderpool-agent: support to configure the sysctl config
  charts/spiderpool/README.md
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  docs/reference/spiderpool-agent.md
  pkg/networking/sysctl/sysctl.go
  test/scripts/install-multus.sh
Labels: release/feature-new

#3841 cherry-pick: removed long-term unmaintained versions from the readme file
  README-zh_CN.md
  README.md
Labels: kind/doc, release/none, release-v0.9

#3840 spiderpool-agent: support to configure the sysctl config
  charts/spiderpool/README.md
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  docs/reference/spiderpool-agent.md
  pkg/networking/sysctl/sysctl.go
  test/scripts/install-multus.sh
Labels: release/feature-new

#3829 e2e: enhance getting docker subnet infos
  test/Makefile
Labels: release/none

#3848 DRA: remove rdmaAcc field of SpiderClaimParameter
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderclaimparameters.yaml
  pkg/dra/dra-plugin/cdi.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderclaimparameters_types.go
  test/e2e/dra/dra_test.go
  test/e2e/spiderclaimparameter/spiderclaimparameter_test.go
Labels: release/none

#3850 fix: Optimize CI machine disk cleanup method to avoid no space left
  .github/workflows/e2e-init.yaml
Labels: release/none, release-v0.8

#3851 fix: Optimize CI machine disk cleanup method to avoid no space left
  .github/workflows/e2e-init.yaml
Labels: release/none, release-v0.9

#3852 DRA: update SpiderClaimParameter CRD
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderclaimparameters.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderclaimparameters_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/manager/spidercliamparameter/spidercliamparameter_webhook.go
  test/e2e/spiderclaimparameter/spiderclaimparameter_test.go
Labels: release/none

#3855 docs: fix typo in spiderpool-aget.md
  docs/reference/spiderpool-agent.md
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#3858 docs: fix typo in spiderpool-aget.md
  docs/reference/spiderpool-agent.md
Labels: robot-cherrypick, release/none

#3857 docs: fix typo in spiderpool-aget.md
  docs/reference/spiderpool-agent.md
Labels: robot-cherrypick, release/none

#3856 docs: fix typo in spiderpool-aget.md
  docs/reference/spiderpool-agent.md
Labels: robot-cherrypick, release/none

#3870 doc: ai with macvlan
  charts/spiderpool/README.md
  charts/spiderpool/templates/rdma-shared-dp/rdma-shared-dp.yaml
  charts/spiderpool/values.yaml
  docs/images/ai-cluster.png
  docs/mkdocs.yml
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/ai/get-started-sriov-zh_CN.md
  docs/usage/install/ai/get-started-sriov.md
  docs/usage/install/cloud/get-started-aws.md
  docs/usage/ipoib-zh_CN.md
  docs/usage/ipoib.md
  docs/usage/rdma-ib-zh_CN.md
  docs/usage/rdma-ib.md
  docs/usage/rdma-roce-zh_CN.md
  docs/usage/rdma-roce.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
Labels: release/feature-new

#3880 rbac: remove permissions for patch/update nodes and webhook resources
  charts/spiderpool/templates/role.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  pkg/multuscniconfig/utils.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#3885 robot updates kind node version in k8s matrix test
  .github/workflows/auto-diff-k8s-ci.yaml
Labels: pr/dependabot/github-actions, release/none

#3884 rbac: remove permissions for patch/update nodes and webhook resources
  charts/spiderpool/templates/role.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  pkg/multuscniconfig/utils.go
Labels: robot-cherrypick, release/bug

#3888 robot updates kind node version in k8s matrix test
  .github/workflows/auto-diff-k8s-ci.yaml
Labels: pr/dependabot/github-actions, release/none

#3898 agent set rp_filter to 0 for the each node
  cmd/coordinator/cmd/command_add.go
  docs/reference/spiderpool-agent.md
  pkg/networking/sysctl/sysctl.go
Labels: release/feature-new

#3778 fix: Spiderpool GC incorrect IP address during statefulset Pod scale up/down, causing IP conflict
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
  go.mod
  go.sum
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
  test/doc/reclaim.md
  test/e2e/common/constant.go
  test/e2e/common/kruise.go
  test/e2e/common/pod.go
  test/e2e/common/spiderpool.go
  test/e2e/common/statefulset.go
  test/e2e/common/tools.go
  test/e2e/reclaim/chaos_test.go
  test/e2e/reclaim/reclaim_suite_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/spidermultus/spidermultus_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/modules.txt
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#3907 agent can be set rp_filter to 0 for the each node
  cmd/coordinator/cmd/command_add.go
  docs/reference/spiderpool-agent.md
  pkg/multuscniconfig/utils.go
  pkg/networking/sysctl/sysctl.go
  test/e2e/reclaim/reclaim_test.go
Labels: release/feature-new

#3908 agent can be set rp_filter to 0 for each node
  cmd/coordinator/cmd/command_add.go
  docs/reference/spiderpool-agent.md
  pkg/networking/sysctl/sysctl.go
  test/e2e/reclaim/reclaim_test.go
Labels: release/feature-new

#3913 agent can be set rp_filter to 0 for the each node
  cmd/coordinator/cmd/command_add.go
  docs/reference/spiderpool-agent.md
  pkg/networking/sysctl/sysctl.go
Labels: release/feature-new

#3924 Added debug log for open-kruise installation failure
  test/Makefile
  test/scripts/debugEnv.sh
Labels: release/none

#3902 fix: Spiderpool GC incorrect IP address during statefulset Pod scale up/down, causing IP conflict
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
  go.mod
  go.sum
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
  test/doc/reclaim.md
  test/e2e/common/constant.go
  test/e2e/common/kruise.go
  test/e2e/common/pod.go
  test/e2e/common/spiderpool.go
  test/e2e/common/statefulset.go
  test/e2e/common/tools.go
  test/e2e/reclaim/chaos_test.go
  test/e2e/reclaim/reclaim_suite_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/spidermultus/spidermultus_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/pod.go
  vendor/modules.txt
Labels: robot-cherrypick, release/bug

#3918 Add chainCNI support for spidermultusconfig
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  docs/reference/crd-spidermultusconfig.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_validate.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/feature-new, release-v0.9, release-v1.0

#3906 coordinator should only set rp_filter for pod but not the node
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/spiderpool-agent/cmd/coordinator.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/reference/crd-spidercoordinator.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#3947 coordinator should only set rp_filter for pod but not the node
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/spiderpool-agent/cmd/coordinator.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/reference/crd-spidercoordinator.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: robot-cherrypick, release/bug

#3948 Fix a typo in changelog.sh
  tools/scripts/changelog.sh
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3950 Fix a typo in changelog.sh
  tools/scripts/changelog.sh
Labels: robot-cherrypick, release/none

#3873 coordinator: fix wrong policy route when there is more than 1 secondary nics
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-agent/cmd/coordinator.go
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/networking/networking/ip.go
  pkg/networking/networking/route.go
  test/doc/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/reclaim/reclaim_test.go
  test/scripts/debugEnv.sh
Labels: release/bug, cherrypick-release-v0.9, cherrypick-release-v1.0

#3965 fix: use latest kind binary and pending kind/node v1.31
  .github/workflows/auto-diff-k8s-ci.yaml
  .github/workflows/e2e-init.yaml
Labels: release/none

#3964 e2e fix: statistics of e2e completion rate exclude pending cases
  .github/workflows/status.yaml
  tools/scripts/e2ecover.sh
Labels: release/none

#3968 coordinator should only set rp_filter for pod not the node
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/spiderpool-agent/cmd/coordinator.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/reference/crd-spidercoordinator.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug

#3971 coordinator: Fix error policy routing table when pod has multi nics
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-agent/cmd/coordinator.go
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/networking/networking/ip.go
  pkg/networking/networking/route.go
  test/doc/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/scripts/debugEnv.sh
Labels: release/bug

#3969 coordinator: Fix error policy routing table when pod has multi nics
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-agent/cmd/coordinator.go
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
  pkg/networking/networking/ip.go
  pkg/networking/networking/route.go
  test/doc/coordinator.md
  test/e2e/common/constant.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_suite_test.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/scripts/debugEnv.sh
Labels: release/bug

#3973 Add chainCNI support for spidermultusconfig
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  docs/reference/crd-spidermultusconfig.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_validate.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/feature-new, release-v0.9

#3972 bump version to v0.9.5
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#3935 Update bug_report.yaml
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: release/none

#3936 rename ci to be easy to understand
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  Makefile
  docs/develop/contributing.md
Labels: release/none

#3974 Add chainCNI support for spidermultusconfig
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  docs/reference/crd-spidermultusconfig.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_validate.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/feature-new, release-v1.0
