Repository spidernet-io/spiderpool, pull requests merged in 2024-12, with the labels that each got.

#4350 docs typo: annotations is incorrectly written as labels
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/ai/get-started-sriov-zh_CN.md
  docs/usage/install/ai/get-started-sriov.md
Labels: release/none

#4360 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
Labels: release/none, pr/release/robot_update_version

#4351 [Docs] Update spider-affinity to relocate code comments
  docs/usage/spider-affinity-zh_CN.md
  docs/usage/spider-affinity.md
Labels: kind/doc, release/none, cherrypick-release-v0.9, cherrypick-release-v1.0

#4378 [Docs] Update spider-affinity to relocate code comments
  docs/usage/spider-affinity-zh_CN.md
  docs/usage/spider-affinity.md
Labels: robot-cherrypick, kind/doc, release/none

#4377 [Docs] Update spider-affinity to relocate code comments
  docs/usage/spider-affinity-zh_CN.md
  docs/usage/spider-affinity.md
Labels: robot-cherrypick, kind/doc, release/none

#4379 Fix: one NIC's IP pool shortage depleted IPs of other NICs in a multi-NIC setup.
  pkg/ippoolmanager/ippool_manager.go
  test/doc/annotation.md
  test/e2e/annotation/annotation_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4382 Fix: one NIC's IP pool shortage depleted IPs of other NICs in a multi-NIC setup.
  pkg/ippoolmanager/ippool_manager.go
  test/doc/annotation.md
  test/e2e/annotation/annotation_test.go
Labels: robot-cherrypick, release/bug

#4384 Fix: one NIC's IP pool shortage depleted IPs of other NICs in a multi-NIC setup.
  pkg/ippoolmanager/ippool_manager.go
  test/doc/annotation.md
  test/e2e/annotation/annotation_test.go
Labels: robot-cherrypick, release/bug, release-v0.8

#4383 Fix: one NIC's IP pool shortage depleted IPs of other NICs in a multi-NIC setup.
  pkg/ippoolmanager/ippool_manager.go
  test/doc/annotation.md
  test/e2e/annotation/annotation_test.go
Labels: robot-cherrypick, release/bug, release-v0.9

#4390 Fix: statefulSet applications failed to create in multi-NIC scenarios.
  pkg/ipam/allocate.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
  test/doc/annotation.md
  test/doc/ippoolcr.md
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
Labels: robot-cherrypick, release/bug, release-v0.9

#4391 Fix: fail to create statefulSet applications in multi-NIC scenarios.
  pkg/ipam/allocate.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
  test/doc/annotation.md
  test/doc/ippoolcr.md
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
Labels: robot-cherrypick, release/bug, release-v0.8

#4385 doc: subnet
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
Labels: release/none

#4398 remove maintainer: ty-dc
  .github/ISSUE_TEMPLATE/ci-failure.yaml
  .github/ISSUE_TEMPLATE/usage.yaml
  .github/workflows/auto-diff-k8s-ci.yaml
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-update-authors.yaml
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-release-version.yaml
  .github/workflows/call-update-githubpages.yaml
  .github/workflows/update-cniplugins-version.yaml
  .github/workflows/update-golang-version.yaml
  CODEOWNERS
  MAINTAINERS.md
Labels: release/none

#4413 ci fix: fails to run ovs
  test/scripts/install-ovs.sh
Labels: release/none

#4414 ci fix: fails to run ovs
  test/scripts/install-ovs.sh
Labels: release/none

#4401 e2e: fix openkruise installtion and debug ovs installtion
  Makefile
  test/Makefile
  test/Makefile.defs
  test/scripts/install-ovs.sh
Labels: kind/ci-bug, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4415 ci fix: fails to run ovs
  test/scripts/install-ovs.sh
Labels: release/none

#4432 docs: updates blogs.md
  docs/concepts/blog-zh_CN.md
  docs/concepts/blog.md
Labels: release/none

#4425 e2e: fix openkruise installtion and debug ovs installtion
  Makefile
  test/Makefile
  test/Makefile.defs
  test/scripts/install-ovs.sh
Labels: release/none, release-v1.0

#4406 chart: update plugins image
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: release/feature-new

#4409 Add cluster dropdown menu for grafana dashboard
  charts/spiderpool/files/grafana-ipam.json
  charts/spiderpool/files/grafana-rdma-cluster.json
  charts/spiderpool/files/grafana-rdma-node.json
  charts/spiderpool/files/grafana-rdma-pod.json
  charts/spiderpool/files/grafana-rdma-workload.json
  charts/spiderpool/templates/grafanaDashboard.yaml
Labels: release/feature-new

#4424 e2e: fix openkruise installtion and debug ovs installtion
  Makefile
  test/Makefile
  test/Makefile.defs
  test/scripts/install-ovs.sh
Labels: release/none, release-v0.9

#4435 e2e: debug
  test/Makefile
Labels: release/none

#4437 Github Action: Fix fail to download artifact
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/auto-version-release.yaml
  .github/workflows/build-image-base.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/build-image-plugins.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/trivy-scan-image.yaml
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4439 CI: FIx fail to upload multiple artifacts with the same name
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/build-image-base.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/build-image-plugins.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  .github/workflows/trivy-scan-image.yaml
  .github/workflows/update-chart-readme.yml
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4443 CI: use merge-multiple for download-artifact
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/build-image-plugins.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/trivy-scan-image.yaml
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4423 e2e: fix openkruise installtion and debug ovs installtion
  Makefile
  test/Makefile
  test/Makefile.defs
  test/scripts/install-ovs.sh
Labels: release/none, release-v0.8

#4420 Fix: the pod fails to run because the certificate of the pod webhook is not up to data after helm upgrading
  .github/workflows/trivy-scan-image.yaml
  charts/spiderpool/templates/tls.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/podmanager/pod_webhook.go
  pkg/podmanager/utils.go
  pkg/podmanager/utils_test.go
Labels: release/bug, cherrypick-release-v0.9, cherrypick-release-v1.0

#4451 Fix: the pod fails to run because the certificate of the pod webhook is not up to data after helm upgrade
  charts/spiderpool/templates/tls.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/podmanager/pod_webhook.go
  pkg/podmanager/utils.go
  pkg/podmanager/utils_test.go
  test/Makefile
Labels: release/bug, release-v1.0

#4433 Fix controller panic in cilium ipam is multi-pool
  pkg/coordinatormanager/coordinator_informer.go
  test/Makefile
  test/Makefile.defs
  test/e2e/common/spiderpool.go
  test/e2e/spidercoordinator/spidercoordinator_test.go
  test/scripts/install-default-cni.sh
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4393 fix: multus fails to reach api server when the old service account is out of data && update multus to v4
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/multus.go
  cmd/spiderpool-init/cmd/root.go
  test/Makefile
  test/Makefile.defs
  test/e2e/common/constant.go
Labels: pr/ready-review, release/feature-new, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4366 fix: fail to get podCIDR and serviceCIDR
  Makefile
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_informer_test.go
  pkg/coordinatormanager/coordinatormanager_suite_test.go
  test/Makefile.defs
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4455 Fix controller panic in cilium ipam is multi-pool
  pkg/coordinatormanager/coordinator_informer.go
  test/Makefile
  test/Makefile.defs
  test/e2e/common/spiderpool.go
  test/e2e/spidercoordinator/spidercoordinator_test.go
  test/scripts/install-default-cni.sh
Labels: robot-cherrypick, release/bug

#4459 Fix controller panic in cilium ipam is multi-pool
  pkg/coordinatormanager/coordinator_informer.go
  test/Makefile.defs
  test/e2e/common/spiderpool.go
  test/scripts/install-default-cni.sh
Labels: release/bug, release-v0.8

#4461 Fix controller panic in cilium ipam is multi-pool
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/multus.go
  cmd/spiderpool-init/cmd/root.go
  pkg/coordinatormanager/coordinator_informer.go
  test/Makefile
  test/Makefile.defs
  test/e2e/common/constant.go
  test/e2e/common/spiderpool.go
  test/e2e/spidercoordinator/spidercoordinator_test.go
  test/scripts/install-default-cni.sh
Labels: release/bug, release-v0.9

#4466 fix: fail to get podCIDR and serviceCIDR
  Makefile
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_informer_test.go
  pkg/coordinatormanager/coordinatormanager_suite_test.go
  test/Makefile.defs
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: robot-cherrypick, release/bug

#4463 bump version to v1.0.0-rc4
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#4477 fix: fix get null podCIDR and serviceCIDR
  Makefile
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_informer_test.go
  pkg/coordinatormanager/coordinatormanager_suite_test.go
  test/Makefile.defs
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/bug, release-v0.9

#4476 fix: fix get null podCIDR and serviceCIDR
  Makefile
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_informer_test.go
  pkg/coordinatormanager/coordinatormanager_suite_test.go
  test/Makefile.defs
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/bug, release-v0.8

#4460 bump multus to v4 & fix multus fails to reach api server when the old service account is out of data
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/multus.go
  cmd/spiderpool-init/cmd/root.go
  test/Makefile
  test/Makefile.defs
  test/e2e/common/constant.go
Labels: release/bug, release-v0.8

#4462 bump multus to v4 & fix multus fails to reach api server when the old service account is out of data
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/multus.go
  cmd/spiderpool-init/cmd/root.go
  test/Makefile
  test/Makefile.defs
  test/e2e/common/constant.go
Labels: release/bug, release-v1.0

#4474 Detect IP conflicts before gateway detection to fix communication fail
  .github/workflows/trivy-scan-image.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4478 utils: improve unittest coverage
  Makefile
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_informer_test.go
  pkg/coordinatormanager/coordinatormanager_suite_test.go
  pkg/ippoolmanager/config_test.go
  pkg/utils/utils.go
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/none

#4486 CI: Fix auto-version-release with upload-artifact failed
  .github/workflows/call-release-image.yaml
Labels: release/none

#4490 CI: Fix fail to download chart artifact
  .github/workflows/auto-version-release.yaml
Labels: release/none

#4494 CI: Fix Download Chart Artifact
  .github/workflows/auto-version-release.yaml
Labels: release/none

#4498 Fix CI Download Artifact
  .github/workflows/auto-version-release.yaml
Labels: release/none
