Repository spidernet-io/spiderpool, pull requests merged in 2024-04, with the labels that each got.

#3322 supplement right AlreadyExist error return for IPPool/Subnet webhook
  pkg/ippoolmanager/ippool_validate.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/subnetmanager/subnet_validate.go
  pkg/subnetmanager/subnet_webhook.go
  pkg/subnetmanager/subnet_webhook_test.go
Labels: pr/ready-review, kind/bug, release/none

#3335 chart: Support configure ifNames for rdmaSharedDevicePlugin
  charts/spiderpool/README.md
  charts/spiderpool/templates/rdma-shared-dp/rdma-shared-dp.yaml
  charts/spiderpool/values.yaml
Labels: release/feature-new

#3340 update maintainers
  .github/.spelling
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/workflows/auto-diff-k8s-ci.yaml
  .github/workflows/auto-nightly-ci.yaml
  CODEOWNERS
  MAINTAINERS.md
  pkg/gcmanager/pod_cache.go
  pkg/multuscniconfig/multusconfig_informer.go
  test/e2e/kubevirt/kubevirt_test.go
Labels: pr/ready-review, release/none

#3241 subnet feature: support to turn on or off the feature of managing automatic-ippool
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
  pkg/applicationcontroller/applicationinformers/utils.go
  pkg/applicationcontroller/applicationinformers/utils_test.go
  pkg/ipam/config.go
  pkg/ipam/pool_selections.go
  pkg/ippoolmanager/ippool_informer.go
  pkg/types/k8s.go
  test/Makefile
  test/doc/subnet.md
  test/e2e/subnet/subnet_test.go
Labels: pr/ready-review, release/feature-new

#3262 feature: support wildcard match for IPPool
  cmd/spiderpool-agent/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  docs/concepts/coordinator.md
  docs/usage/spider-ippool-zh_CN.md
  docs/usage/spider-ippool.md
  docs/usage/spider-subnet-zh_CN.md
  docs/usage/spider-subnet.md
  pkg/constant/k8s.go
  pkg/ipam/pool_selections.go
  pkg/ipam/utils.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/ippoolmanager/ippool_manager_test.go
  pkg/ippoolmanager/utils.go
  pkg/ippoolmanager/utils_test.go
  pkg/reservedipmanager/reservedip_manager.go
  pkg/reservedipmanager/reservedip_manager_suite_test.go
  test/doc/annotation.md
  test/e2e/annotation/annotation_test.go
Labels: pr/ready-review, release/feature-new

#3349 Update codecov-action to v4
  .github/workflows/lint-golang.yaml
Labels: release/none

#3351 When the kind cluster cannot be created, add the step of restarting docker and try again.
  .github/workflows/e2e-init.yaml
Labels: release/none

#3346 Fix: check if err occurs during e2e create IPPool step
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: pr/ready-review, release/none

#3358 coordinator: ensure hijickRoute's gw is from hostIPRouteForPod
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
Labels: cherrypick-release-v0.7, release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#3363 coordinator: ensure hijickRoute's gw is from hostIPRouteForPod
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
Labels: robot-cherrypick, release/bug

#3364 coordinator: ensure hijickRoute's gw is from hostIPRouteForPod
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
Labels: robot-cherrypick, release/bug

#3366 bump version to v0.9.3
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#3368 bump cosign-release to v2.2.3
  .github/workflows/call-release-image.yaml
Labels: cherrypick-release-v0.7, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3371 bump cosign-release to v2.2.3
  .github/workflows/call-release-image.yaml
Labels: release/none

#3370 bump cosign-release to v2.2.3
  .github/workflows/call-release-image.yaml
Labels: release/none

#3369 bump cosign-release to v2.2.3
  .github/workflows/call-release-image.yaml
Labels: release/none

#3381 Optimize IPPool multus affinity code comments
  pkg/ipam/allocate.go
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: enhancement, release/none

#3365 coordinator: ensure hijickRoute's gw is from hostIPRouteForPod
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  test/scripts/install-default-cni.sh
Labels: release/bug

#3339 feature: run a clean-up job when uninstalling
  .github/workflows/e2e-init.yaml
  charts/spiderpool/README.md
  charts/spiderpool/templates/deleteHook.yaml
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/clean.go
  cmd/spiderpool-controller/cmd/command_root.go
  docs/mkdocs.yml
  docs/usage/install/uninstall-zh_CN.md
  docs/usage/install/uninstall.md
  docs/usage/readme-zh_CN.md
  docs/usage/readme.md
  go.mod
  go.sum
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  test/Makefile
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/group.go
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/modules.txt
Labels: release/feature-new

#3377 CI: update release version in readme
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-release-version.yaml
  docs/README-zh_CN.md
  docs/README.md
Labels: pr/ready-review, enhancement, cherrypick-release-v0.7, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3393 CI: update release version in readme
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-release-version.yaml
  docs/README-zh_CN.md
  docs/README.md
Labels: pr/ready-review, robot-cherrypick, enhancement, release/none

#3395 [chery-pick] CI: update release version in readme
  .github/workflows/auto-version-release.yaml
  .github/workflows/call-release-version.yaml
  docs/README-zh_CN.md
Labels: robot-cherrypick, release/none

#3323 Add upgrade test for spiderpool
  .github/workflows/auto-upgrade-ci.yaml
  Makefile
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
  test/Makefile
Labels: kind/test, release/none

#3401 fix: confirm that the SpiderSubnet AutoPool feature is really disabled
  test/e2e/subnet/subnet_test.go
  test/scripts/debugEnv.sh
Labels: release/none

#3409 fix upgrade test
  .github/workflows/auto-upgrade-ci.yaml
Labels: release/none

#3412 ci: optimize upgrade
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/auto-version-release.yaml
Labels: kind/test, release/none

#3408 docs: aws optimization
  docs/usage/install/cloud/get-started-aws-zh_CN.md
  docs/usage/install/cloud/get-started-aws.md
Labels: kind/doc, release/none

#3416 Add upgrade test for spiderpool
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/auto-version-release.yaml
  Makefile
  test/Makefile
Labels: robot-cherrypick, release/none, release-v0.8

#3417 Add upgrade test for spiderpool
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/auto-version-release.yaml
  Makefile
  test/Makefile
Labels: robot-cherrypick, release-v0.7, release/none

#3411 e2e fix: restart the spider-Agent to make the configuration take effect.
  test/e2e/subnet/subnet_test.go
Labels: release/none

#3421 bump version to v1.0.0-rc0
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#3433 fix: add kdoctor debug log
  test/scripts/debugEnv.sh
Labels: release/none

#3432 fix: Ignore rc version when updating readme
  .github/workflows/call-release-version.yaml
Labels: cherrypick-release-v0.7, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3403 doc: optimize ovs
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3438 fix: Ignore rc version when updating readme
  .github/workflows/call-release-version.yaml
Labels: robot-cherrypick, release/none

#3437 fix: Ignore rc version when updating readme
  .github/workflows/call-release-version.yaml
Labels: robot-cherrypick, release/none

#3436 fix: Ignore rc version when updating readme
  .github/workflows/call-release-version.yaml
Labels: robot-cherrypick, release/none

#3288 E2E: testing if neither kubeadm-config nor kube-controller-manager no found
  test/doc/spidercoodinator.md
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/none, cherrypick-release-v0.9

#3442 [cherry-pick]: doc: optimize ovs
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
Labels: robot-cherrypick, release/none, release-v0.8
