Repository spidernet-io/spiderpool, pull requests merged in 2024-05, with the labels that each got.

#3463 [Docs] Fix links to anchors in /docs/reference
  docs/reference/crd-spiderendpoint.md
  docs/reference/crd-spiderippool.md
  docs/reference/crd-spidermultusconfig.md
  docs/reference/crd-spidersubnet.md
  docs/reference/plugin-ifacer.md
  docs/usage/dra.md
  docs/usage/install/uninstall-zh_CN.md
  docs/usage/install/uninstall.md
Labels: kind/doc, release/none, cherrypick-release-v0.9

#3462 e2e fix: increase the timeout for service accounts
  test/e2e/common/constant.go
Labels: release/none

#3468 [Docs] Fix links to anchors in /docs/reference
  docs/reference/crd-spiderendpoint.md
  docs/reference/crd-spiderippool.md
  docs/reference/crd-spidermultusconfig.md
  docs/reference/crd-spidersubnet.md
  docs/reference/plugin-ifacer.md
Labels: robot-cherrypick, release/none

#3445 e2e fix: extend the waiting time after restarting spiderpool-agent and add some logs
  test/e2e/subnet/subnet_test.go
Labels: release/none

#3475 e2e fix: the kube-controller-manager Pod runs successfully when the label is kube-controller-manager1.
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/none

#3481 fix: Logic issues with releasing version x
  tools/scripts/changelog.sh
Labels: release/none

#3485 fix: restarting the kcm Pod helps restore its labels
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/none

#3492 Update USERS.md
  docs/USERS.md
Labels: release/none

#3493 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: release/none

#3496 typo: dra docs
  docs/usage/dra.md
  docs/usage/dra_zh_CN.md
Labels: release/none

#3504 DRA: fix error start of agent
  pkg/dra/dra-plugin/device_state.go
Labels: release/bug

#3518 E2E: add timeout for spidercoordinator case
  test/e2e/common/pod.go
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/none

#3512 CI: Add k8s 1.30 version compatibility test
  .github/workflows/auto-diff-k8s-ci.yaml
  test/scripts/update-kindnode-version.sh
Labels: release/none

#3544 bump version to 0.9.4
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#3506 ci: Add automatic update of spiderpool authors
  .github/workflows/auto-update-authors.yaml
  AUTHORS
  Makefile
  tools/scripts/extractAuthors.sh
Labels: release/none
