Repository spidernet-io/spiderpool, pull requests merged in 2024-10, with the labels that each got.

#4143 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
Labels: release/none, pr/release/robot_update_version

#4130 fix: avoid failures when cleaning up spiderpool resources due to resourceVersion conflicts.
  cmd/spiderpool-controller/cmd/clean.go
Labels: release/bug, cherrypick-release-v1.0

#4151 fix: avoid failures when cleaning up spiderpool resources due to resourceVersion conflicts.
  cmd/spiderpool-controller/cmd/clean.go
Labels: robot-cherrypick, release/bug

#4153 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release/none

#4155 fix: ovs docs formatting errors and AI docs typo
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
Labels: kind/doc, release/none, cherrypick-release-v0.9, cherrypick-release-v1.0

#4161 fix: ovs docs formatting errors and AI docs typo
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
Labels: robot-cherrypick, kind/doc, release/none

#4156 fix: optimize the cleanup code judgment of NotFound resources
  cmd/spiderpool-controller/cmd/clean.go
Labels: release/bug, cherrypick-release-v1.0

#4163 fix: ovs docs formatting errors and AI docs typo
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
Labels: robot-cherrypick, release/none, release-v0.9

#4162 fix: optimize the cleanup code judgment of NotFound resources
  cmd/spiderpool-controller/cmd/clean.go
Labels: robot-cherrypick, release/bug

#4171 fix: Added retries to avoid openvswitch installation failures.
  test/scripts/install-ovs.sh
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4180 fix: Added retries to avoid openvswitch installation failures.
  test/scripts/install-ovs.sh
Labels: robot-cherrypick, release/none

#4181 fix: Added retries to avoid openvswitch installation failures.
  test/scripts/install-ovs.sh
Labels: robot-cherrypick, release/none

#4182 fix: Added retries to avoid openvswitch installation failures.
  test/scripts/install-ovs.sh
Labels: robot-cherrypick, release/none

#4172 fix: Optimize CI fails sporadically.
  test/e2e/common/constant.go
  test/e2e/common/node.go
  test/e2e/common/pod.go
  test/e2e/common/spiderpool.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  test/scripts/debugEnv.sh
  test/scripts/install-kdoctor.sh
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4195 fix: Optimize CI fails sporadically.
  go.mod
  go.sum
  test/e2e/common/constant.go
  test/e2e/common/node.go
  test/e2e/common/pod.go
  test/e2e/common/spiderpool.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_suite_test.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
  test/e2e/reliability/reliability_test.go
  test/scripts/debugEnv.sh
  test/scripts/install-kdoctor.sh
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/group.go
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
  vendor/modules.txt
Labels: robot-cherrypick, kind/test, release/none, release-v0.8

#4194 fix: Optimize CI fails sporadically.
  go.mod
  go.sum
  test/e2e/common/constant.go
  test/e2e/common/node.go
  test/e2e/common/pod.go
  test/e2e/common/spiderpool.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_suite_test.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  test/scripts/debugEnv.sh
  test/scripts/install-kdoctor.sh
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/group.go
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
  vendor/modules.txt
Labels: robot-cherrypick, kind/test, release/none, release-v0.9

#4193 fix: Optimize CI fails sporadically.
  test/e2e/common/constant.go
  test/e2e/common/node.go
  test/e2e/common/pod.go
  test/e2e/common/spiderpool.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  test/scripts/debugEnv.sh
  test/scripts/install-kdoctor.sh
Labels: robot-cherrypick, release/none

#4168 fix: same-name conflict check specified by multus.spidernet.io/cr-name
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/multusconfig_webhook.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4196 optimize ipam concepts
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  docs/concepts/ipam-performance-zh_CN.md
  docs/concepts/ipam-performance.md
  docs/images/ipam-concepts.jpg
  docs/usage/dra.md
  docs/usage/dra_zh_CN.md
  docs/usage/faq-zh_CN.md
  docs/usage/ipvlan_bandwidth-zh_CN.md
  docs/usage/ipvlan_bandwidth.md
  docs/usage/kubevirt-zh_CN.md
  docs/usage/multi_cni_coexist-zh_CN.md
  docs/usage/multi_cni_coexist.md
  docs/usage/operator-zh_CN.md
  docs/usage/readme-zh_CN.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  docs/usage/underlay_cni_service-zh_CN.md
  docs/usage/underlay_cni_service.md
Labels: kind/doc, release/none, cherrypick-release-v0.9, cherrypick-release-v1.0

#4200 fix: same-name conflict check specified by multus.spidernet.io/cr-name
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/multusconfig_webhook.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: robot-cherrypick, release/bug

#4201 fix: same-name conflict check specified by multus.spidernet.io/cr-name
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/multusconfig_webhook.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: robot-cherrypick, release/bug

#4208 optimize ipam concepts
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  docs/concepts/ipam-performance-zh_CN.md
  docs/concepts/ipam-performance.md
  docs/images/ipam-concepts.jpg
  docs/usage/dra.md
  docs/usage/dra_zh_CN.md
  docs/usage/faq-zh_CN.md
  docs/usage/ipvlan_bandwidth-zh_CN.md
  docs/usage/ipvlan_bandwidth.md
  docs/usage/kubevirt-zh_CN.md
  docs/usage/multi_cni_coexist-zh_CN.md
  docs/usage/multi_cni_coexist.md
  docs/usage/operator-zh_CN.md
  docs/usage/readme-zh_CN.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  docs/usage/underlay_cni_service-zh_CN.md
  docs/usage/underlay_cni_service.md
Labels: robot-cherrypick, kind/doc, release/none

#4202 fix: same-name conflict check specified by multus.spidernet.io/cr-name
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/multusconfig_webhook.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: robot-cherrypick, release/bug, release-v0.8

#4205 fix: kdoctor log comparison failed.
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
Labels: kind/cleanup, release/none, cherrypick-release-v0.9, cherrypick-release-v1.0

#4198 e2e fix: A conflict occurred while updating the IPPool resource.
  test/e2e/reclaim/reclaim_test.go
Labels: release/none, cherrypick-release-v0.9, cherrypick-release-v1.0

#4215 e2e fix: error matching is more accurate.
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4210 optimize ipam concepts
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  docs/concepts/ipam-performance-zh_CN.md
  docs/concepts/ipam-performance.md
  docs/images/ipam-concepts.jpg
  docs/usage/faq-zh_CN.md
  docs/usage/ipvlan_bandwidth-zh_CN.md
  docs/usage/ipvlan_bandwidth.md
  docs/usage/kubevirt-zh_CN.md
  docs/usage/multi_cni_coexist-zh_CN.md
  docs/usage/multi_cni_coexist.md
  docs/usage/operator-zh_CN.md
  docs/usage/readme-zh_CN.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  docs/usage/underlay_cni_service-zh_CN.md
  docs/usage/underlay_cni_service.md
Labels: robot-cherrypick, release/none, release-v0.9

#4222 fix: kdoctor log comparison failed.
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
Labels: robot-cherrypick, kind/cleanup, release/none

#4224 e2e fix: A conflict occurred while updating the IPPool resource.
  test/e2e/reclaim/reclaim_test.go
Labels: robot-cherrypick, release/none

#4227 e2e fix: error matching is more accurate.
  test/e2e/spidermultus/spidermultus_test.go
Labels: robot-cherrypick, release/none

#4226 e2e fix: error matching is more accurate.
  test/e2e/spidermultus/spidermultus_test.go
Labels: robot-cherrypick, release/none

#4221 fix: kdoctor log comparison failed.
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
Labels: robot-cherrypick, kind/cleanup, release/none

#4218 document: Add network forward workflow
  docs/concepts/multi_cni_coexist-zh_CN.md
  docs/concepts/multi_cni_coexist.md
  docs/images/calico-calico.png
  docs/images/calico-macvlan-nodeport.png
  docs/images/macvlan-calico-service.png
  docs/images/macvlan-calico.png
  docs/images/macvlan-macvlan-service.png
  docs/images/macvlan-macvlan.png
  docs/images/macvlan-overlay.png
  docs/images/spine-leaf.png
  docs/mkdocs.yml
  docs/usage/multi_cni_coexist-zh_CN.md
  docs/usage/multi_cni_coexist.md
Labels: release/none

#4234 e2e fix: the latest version of calico cannot find the felixconfigurations resource
  test/scripts/install-default-cni.sh
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4237 e2e fix: the latest version of calico cannot find the felixconfigurations resource
  test/scripts/install-default-cni.sh
Labels: robot-cherrypick, release/none

#4236 e2e fix: the latest version of calico cannot find the felixconfigurations resource
  test/scripts/install-default-cni.sh
Labels: robot-cherrypick, release/none

#4235 e2e fix: the latest version of calico cannot find the felixconfigurations resource
  test/scripts/install-default-cni.sh
Labels: robot-cherrypick, release/none

#4179 Add a pod mutating webhook to auto inject the pod network resources
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  docs/reference/spiderpool-controller.md
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/ai/get-started-sriov-zh_CN.md
  docs/usage/install/ai/get-started-sriov.md
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
  pkg/constant/k8s.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  pkg/multuscniconfig/utils.go
  pkg/podmanager/pod_manager.go
  pkg/podmanager/pod_webhook.go
  pkg/podmanager/utils.go
  pkg/podmanager/utils_test.go
  pkg/types/k8s.go
  test/Makefile
  test/doc/podwebhook.md
  test/e2e/podwebhook/podwebhook_suite_test.go
  test/e2e/podwebhook/podwebhook_test.go
  test/e2e/reliability/reliability_test.go
Labels: release/feature-new

#4238 update roadmap
  docs/develop/roadmap.md
Labels: release/none

#4240 Update base image add rdma-core
  images/spiderpool-base/install-others.sh
Labels: release/none

#4239 Add a pod mutating webhook to auto inject the pod RDMA resources
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  docs/reference/spiderpool-controller.md
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/ai/get-started-sriov-zh_CN.md
  docs/usage/install/ai/get-started-sriov.md
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
  pkg/constant/k8s.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
  pkg/multuscniconfig/utils.go
  pkg/podmanager/pod_manager.go
  pkg/podmanager/pod_webhook.go
  pkg/podmanager/utils.go
  pkg/podmanager/utils_test.go
  pkg/types/k8s.go
  test/Makefile
  test/doc/podwebhook.md
  test/e2e/podwebhook/podwebhook_suite_test.go
  test/e2e/podwebhook/podwebhook_test.go
  test/e2e/reliability/reliability_test.go
Labels: release/feature-new, release-v1.0

#4241 Update version to v1.0.0-rc2
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#4245 Fix podwebhook cert don't update when spiderpool-controller restart
  pkg/podmanager/utils.go
  pkg/podmanager/utils_test.go
  test/Makefile
Labels: release/none, cherrypick-release-v1.0

#4157 fix: scanAll typo
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-init/cmd/client.go
  docs/concepts/arch-zh_CN.md
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/usage/network-topology-zh_CN.md
  docs/usage/network-topology.md
  docs/usage/route-zh_CN.md
  pkg/coordinatormanager/coordinator_validate.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/ip/cidr.go
  pkg/multuscniconfig/multusconfig_validate.go
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4206 Add a flag to configure an link-local address to veth0 for istio
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/README.md
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-agent/cmd/coordinator.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/root.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/mkdocs.yml
  docs/reference/crd-spidercoordinator.md
  docs/usage/istio-zh_CN.md
  docs/usage/istio.md
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/utils.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
  test/scripts/install-multus.sh
Labels: release/feature-new, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4112 Add RDAM metrics
  charts/spiderpool/README.md
  charts/spiderpool/files/grafana-rdma-cluster.json
  charts/spiderpool/files/grafana-rdma-node.json
  charts/spiderpool/files/grafana-rdma-pod.json
  charts/spiderpool/templates/daemonset.yaml
  charts/spiderpool/templates/grafanaDashboardRdmaCluster.yaml
  charts/spiderpool/templates/grafanaDashboardRdmaNode.yaml
  charts/spiderpool/templates/grafanaDashboardRdmaPod.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/metrics_server.go
  docs/mkdocs.yml
  docs/usage/rdma-metrics-zh-CN.md
  docs/usage/rdma-metrics.md
  go.mod
  images/spiderpool-agent/Dockerfile
  pkg/ippoolmanager/ippool_manager_suite_test.go
  pkg/metric/metrics.go
  pkg/metric/metrics_instance.go
  pkg/rdmametrics/ethtool/ethtool.go
  pkg/rdmametrics/metrics.go
  pkg/rdmametrics/metrics_test.go
  pkg/subnetmanager/subnet_manager_suite_test.go
  test/doc/metric.md
  vendor/k8s.io/utils/exec/testing/fake_exec.go
  vendor/modules.txt
Labels: release/feature-new
