Repository spidernet-io/spiderpool, pull requests merged in 2024-06, with the labels that each got.

#3482 docs: add underlay and overlay network coexist
  docs/images/underlay_overlay_cni.png
  docs/mkdocs.yml
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/multi_cni_coexist-zh_CN.md
  docs/usage/multi_cni_coexist.md
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3553 docs: add underlay and overlay network coexist
  docs/images/underlay_overlay_cni.png
  docs/mkdocs.yml
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/multi_cni_coexist-zh_CN.md
  docs/usage/multi_cni_coexist.md
Labels: robot-cherrypick, release/none

#3557 docs: add underlay and overlay network coexist
  docs/images/underlay_overlay_cni.png
  docs/mkdocs.yml
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/multi_cni_coexist-zh_CN.md
  docs/usage/multi_cni_coexist.md
Labels: release/none

#3536 DOC-123: 更新了基于macvlan和ipvlan的RDMA网卡安装Spiderpool的命令
  docs/usage/rdma-ib-zh_CN.md
  docs/usage/rdma-ib.md
  docs/usage/rdma-roce-zh_CN.md
  docs/usage/rdma-roce.md
Labels: kind/doc, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3567 DOC-123: 更新了基于macvlan和ipvlan的RDMA网卡安装Spiderpool的命令
  docs/usage/rdma-ib-zh_CN.md
  docs/usage/rdma-ib.md
  docs/usage/rdma-roce-zh_CN.md
  docs/usage/rdma-roce.md
Labels: robot-cherrypick, kind/doc, release/none

#3526 optimizate upgrade
  .github/workflows/auto-upgrade-ci.yaml
  test/Makefile
  test/e2e/annotation/annotation_test.go
  test/scripts/debugEnv.sh
Labels: cherrypick-release-v0.7, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3522 fix(charts): Remove unnecessary sensitive permissions for DaemonSet agent and Pod init
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/templates/role_binding.yaml
Labels: release/feature-new

#3603 RBAC: rebase pull 3522
  charts/spiderpool/templates/role.yaml
  charts/spiderpool/templates/role_binding.yaml
Labels: release/none

#3608 RBAC: avoiding too high permissions leading to potential CVE risks
  charts/spiderpool/templates/role.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/rbac.go
Labels: release/bug

#3592 [cherrypick-release-v0.9] optimization upgrade
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/auto-version-release.yaml
  test/Makefile
  test/scripts/debugEnv.sh
Labels: release/none

#3620 the PR upgrade CI failed, there is no need to create an issue.
  .github/workflows/auto-upgrade-ci.yaml
Labels: release/none, cherrypick-release-v0.9

#3588 add link-local IP to veth0 for istio
  cmd/coordinator/cmd/utils.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#3621 the PR upgrade CI failed, there is no need to create an issue.
  .github/workflows/auto-upgrade-ci.yaml
Labels: robot-cherrypick, release/none

#3527 update crds for spiderpool dra feature
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderclaimparameters.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderclaimparameters_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
Labels: release/feature-new

#3630 docs: note label worker nodes for sriov-operator
  docs/usage/rdma-ib-zh_CN.md
  docs/usage/rdma-ib.md
  docs/usage/rdma-roce-zh_CN.md
  docs/usage/rdma-roce.md
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3636 Optimize upgrade CI, and use the self-built image in the release branch
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/build-image-ci.yaml
  test/Makefile
Labels: release/none, release-v0.8

#3634 to avoid codecov update failure, update codecov-action to v4
  .github/workflows/lint-golang.yaml
Labels: release/none, release-v0.9

#3635 Optimize upgrade CI, and use the self-built image in the release branch
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/build-image-ci.yaml
Labels: release/none

#3638 docs: note label worker nodes for sriov-operator
  docs/usage/rdma-ib-zh_CN.md
  docs/usage/rdma-ib.md
  docs/usage/rdma-roce-zh_CN.md
  docs/usage/rdma-roce.md
Labels: robot-cherrypick, release/none

#3632 Optimize upgrade CI, and use the self-built image in the release branch
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/build-image-ci.yaml
  Makefile
  test/e2e/common/constant.go
Labels: release/none, release-v0.9

#3622 add link-local IP to veth0 for istio
  cmd/coordinator/cmd/utils.go
Labels: robot-cherrypick, release/bug

#3623 add link-local IP to veth0 for istio
  cmd/coordinator/cmd/utils.go
Labels: robot-cherrypick, release/bug

#3628 fix: it is so slow to create a Pod requiring IP from a super big CIDR
  pkg/ip/ip.go
  pkg/ip/ip_test.go
  pkg/ippoolmanager/ippool_manager.go
  pkg/subnetmanager/subnet_manager.go
  pkg/subnetmanager/subnet_validate.go
  test/e2e/common/spidersubnet.go
Labels: release/bug

#3584 coordinator: Use ARP to detect the gateway rather than ICMP
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  go.mod
  go.sum
  pkg/constant/errors.go
  pkg/networking/gwconnection/connection.go
  pkg/networking/networking/route.go
  vendor/github.com/prometheus-community/pro-bing/.editorconfig
  vendor/github.com/prometheus-community/pro-bing/.gitignore
  vendor/github.com/prometheus-community/pro-bing/.golangci.yml
  vendor/github.com/prometheus-community/pro-bing/.goreleaser.yaml
  vendor/github.com/prometheus-community/pro-bing/CODE_OF_CONDUCT.md
  vendor/github.com/prometheus-community/pro-bing/CONTRIBUTING.md
  vendor/github.com/prometheus-community/pro-bing/LICENSE
  vendor/github.com/prometheus-community/pro-bing/MAINTAINERS.md
  vendor/github.com/prometheus-community/pro-bing/Makefile
  vendor/github.com/prometheus-community/pro-bing/README.md
  vendor/github.com/prometheus-community/pro-bing/SECURITY.md
  vendor/github.com/prometheus-community/pro-bing/logger.go
  vendor/github.com/prometheus-community/pro-bing/packetconn.go
  vendor/github.com/prometheus-community/pro-bing/ping.go
  vendor/github.com/prometheus-community/pro-bing/utils_linux.go
  vendor/github.com/prometheus-community/pro-bing/utils_other.go
  vendor/github.com/prometheus-community/pro-bing/utils_windows.go
  vendor/modules.txt
Labels: release/feature-changed, cherrypick-release-v0.8, cherrypick-release-v0.9

#3646 coordinator: Use ARP to detect the gateway rather than ICMP
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  go.mod
  go.sum
  pkg/constant/errors.go
  pkg/networking/gwconnection/connection.go
  pkg/networking/networking/route.go
  vendor/github.com/prometheus-community/pro-bing/.editorconfig
  vendor/github.com/prometheus-community/pro-bing/.gitignore
  vendor/github.com/prometheus-community/pro-bing/.golangci.yml
  vendor/github.com/prometheus-community/pro-bing/.goreleaser.yaml
  vendor/github.com/prometheus-community/pro-bing/CODE_OF_CONDUCT.md
  vendor/github.com/prometheus-community/pro-bing/CONTRIBUTING.md
  vendor/github.com/prometheus-community/pro-bing/LICENSE
  vendor/github.com/prometheus-community/pro-bing/MAINTAINERS.md
  vendor/github.com/prometheus-community/pro-bing/Makefile
  vendor/github.com/prometheus-community/pro-bing/README.md
  vendor/github.com/prometheus-community/pro-bing/SECURITY.md
  vendor/github.com/prometheus-community/pro-bing/logger.go
  vendor/github.com/prometheus-community/pro-bing/packetconn.go
  vendor/github.com/prometheus-community/pro-bing/ping.go
  vendor/github.com/prometheus-community/pro-bing/utils_linux.go
  vendor/github.com/prometheus-community/pro-bing/utils_other.go
  vendor/github.com/prometheus-community/pro-bing/utils_windows.go
  vendor/modules.txt
Labels: robot-cherrypick, release/feature-changed

#3652 coordinator: Use arping to detect the gateway rather than ICMP
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  go.mod
  go.sum
  pkg/constant/errors.go
  pkg/networking/gwconnection/connection.go
  pkg/networking/networking/route.go
  vendor/github.com/prometheus-community/pro-bing/.editorconfig
  vendor/github.com/prometheus-community/pro-bing/.gitignore
  vendor/github.com/prometheus-community/pro-bing/.golangci.yml
  vendor/github.com/prometheus-community/pro-bing/.goreleaser.yaml
  vendor/github.com/prometheus-community/pro-bing/CODE_OF_CONDUCT.md
  vendor/github.com/prometheus-community/pro-bing/CONTRIBUTING.md
  vendor/github.com/prometheus-community/pro-bing/LICENSE
  vendor/github.com/prometheus-community/pro-bing/MAINTAINERS.md
  vendor/github.com/prometheus-community/pro-bing/Makefile
  vendor/github.com/prometheus-community/pro-bing/README.md
  vendor/github.com/prometheus-community/pro-bing/SECURITY.md
  vendor/github.com/prometheus-community/pro-bing/logger.go
  vendor/github.com/prometheus-community/pro-bing/packetconn.go
  vendor/github.com/prometheus-community/pro-bing/ping.go
  vendor/github.com/prometheus-community/pro-bing/utils_linux.go
  vendor/github.com/prometheus-community/pro-bing/utils_other.go
  vendor/github.com/prometheus-community/pro-bing/utils_windows.go
  vendor/modules.txt
Labels: release/bug

#3657 bump version to v0.8.7
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#3664 fix: release note
  tools/scripts/changelog.sh
Labels: robot-cherrypick, release/none

#3668 spiderclaimparameter: add webhook to verify the create and update
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderclaimparameters.yaml
  charts/spiderpool/templates/tls.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderclaimparameters_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/manager/spidercliamparameter/spidercliamparameter_webhook.go
  test/doc/spidercclaimparameter.md
  test/e2e/dra/dra_test.go
  test/e2e/spiderclaimparameter/spiderclaimparameter_suite_test.go
  test/e2e/spiderclaimparameter/spiderclaimparameter_test.go
Labels: release/feature-new

#3669 Fix: Statefulset pod should change IP when recreating with a changed pool in annotation
  docs/usage/statefulset-zh_CN.md
  docs/usage/statefulset.md
  pkg/ipam/allocate.go
  pkg/ipam/utils.go
  test/e2e/affinity/affinity_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#3675 Fix: Statefulset pod should change IP when recreating with a changed pool in annotation
  docs/usage/statefulset-zh_CN.md
  docs/usage/statefulset.md
  pkg/ipam/allocate.go
  pkg/ipam/utils.go
  test/e2e/affinity/affinity_test.go
Labels: robot-cherrypick, release/bug

#3674 Fix: Statefulset pod should change IP when recreating with a changed pool in annotation
  docs/usage/statefulset-zh_CN.md
  docs/usage/statefulset.md
  pkg/ipam/allocate.go
  pkg/ipam/utils.go
  test/e2e/affinity/affinity_test.go
Labels: robot-cherrypick, release/bug
