Repository spidernet-io/spiderpool, pull requests merged in 2024-01, with the labels that each got.

#3056 update label in depenndabot
  .github/dependabot.yml
Labels: release/none

#3059 v0.7 call-release-doc.yaml rebase to main
  .github/workflows/call-release-doc.yaml
Labels: release-v0.7, release/none

#3061 List the stable versions of spiderpool
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: kind/doc, release/none, cherrypick-release-v0.9

#3068 add IPPool and Subnet property subnet field format validation
  pkg/ip/cidr.go
  pkg/ip/cidr_test.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/subnetmanager/subnet_validate.go
  test/e2e/common/tools.go
Labels: pr/ready-review, enhancement, release/none

#3065 e2e fix: SpiderSubnet and SpiderIPPool resource subnet overlap.
  test/doc/ippoolcr.md
  test/doc/performance.md
  test/e2e/affinity/affinity_test.go
  test/e2e/annotation/annotation_test.go
  test/e2e/assignip/assignip_test.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
  test/e2e/ifacer/ifacer_test.go
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/kruise/kruise_test.go
  test/e2e/reclaim/reclaim_test.go
  test/e2e/reliability/reliability_test.go
  test/e2e/reservedip/reservedip_test.go
  test/e2e/subnet/subnet_test.go
  test/scripts/debugEnv.sh
Labels: kind/test, release/none

#3069 Add e2e for active-standby switching of spidercontroller
  test/doc/metric.md
  test/doc/reliability.md
  test/e2e/common/constant.go
  test/e2e/reliability/reliability_suite_test.go
  test/e2e/reliability/reliability_test.go
Labels: kind/test, release/none

#3072 Add e2e about nodeName,namespaceName priority
  test/doc/ippoolcr.md
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: kind/test, release/none

#3051 cherry-pick PRs submitted by robots can be verified.
  .github/workflows/auto-cherrypick.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
Labels: pr/dependabot/github-actions, cherrypick-release-v0.7, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3076 cherry-pick PRs submitted by robots can be verified.
  .github/workflows/auto-cherrypick.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
Labels: robot-cherrypick, release/none

#3077 [release-v0.7]cherry-pick PRs submitted by robots can be verified.
  .github/workflows/auto-cherrypick.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
Labels: pr/dependabot/github-actions, release-v0.7, release/none

#3078 [release-v0.8]cherry-pick PRs submitted by robots can be verified.
  .github/workflows/auto-cherrypick.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-update-githubpages.yaml
Labels: pr/dependabot/github-actions, release/none, release-v0.8

#3066 e2e fix: The kind image name is wrong.
  test/Makefile
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3079 e2e fix: The kind image name is wrong.
  test/Makefile
Labels: robot-cherrypick, release/none

#3080 e2e fix: The kind image name is wrong.
  test/Makefile
Labels: robot-cherrypick, release/none

#3071 fix document example typo
  docs/example/spider-subnet/multiple-interfaces.yaml
Labels: pr/ready-review, enhancement, cherrypick-release-v0.7, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3082 fix document example typo
  docs/example/spider-subnet/multiple-interfaces.yaml
Labels: robot-cherrypick, release/none

#3084 fix document example typo
  docs/example/spider-subnet/multiple-interfaces.yaml
Labels: robot-cherrypick, release/none

#3083 fix document example typo
  docs/example/spider-subnet/multiple-interfaces.yaml
Labels: robot-cherrypick, release/none

#3088 fix: the parent interface is down, set it to up before creating the vlan sub-interface
  cmd/ifacer/cmd/cmd_add.go
Labels: cherrypick-release-v0.7, release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#3091 fix: the parent interface is down, set it to up before creating the vlan sub-interface
  cmd/ifacer/cmd/cmd_add.go
Labels: robot-cherrypick, release/bug

#3090 fix: the parent interface is down, set it to up before creating the vlan sub-interface
  cmd/ifacer/cmd/cmd_add.go
Labels: robot-cherrypick, release/bug

#3089 fix: the parent interface is down, set it to up before creating the vlan sub-interface
  cmd/ifacer/cmd/cmd_add.go
Labels: robot-cherrypick, release/bug

#3085 docs: fix SpiderMultusConfig.spec.cniType in IPoIB
  docs/usage/rdma-ib-zh_CN.md
  docs/usage/rdma-ib.md
Labels: kind/doc, release/none, cherrypick-release-v0.9

#3073 update document blog
  docs/concepts/blog-zh_CN.md
  docs/concepts/blog.md
Labels: pr/ready-review, kind/doc, release/none, cherrypick-release-v0.9

#3095 docs: fix SpiderMultusConfig.spec.cniType in IPoIB
  docs/usage/rdma-ib-zh_CN.md
  docs/usage/rdma-ib.md
Labels: robot-cherrypick, release/none

#3096 update document blog
  docs/concepts/blog-zh_CN.md
  docs/concepts/blog.md
Labels: robot-cherrypick, release/none

#3086 Fixed some incorrect labels and added some e2e.
  test/doc/coordinator.md
  test/doc/spidermultus.md
  test/e2e/annotation/annotation_test.go
  test/e2e/common/constant.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/ifacer/ifacer_test.go
  test/e2e/reliability/reliability_test.go
  test/e2e/spidermultus/spidermultus_test.go
  tools/scripts/e2ecover.sh
Labels: kind/test, release/none

#3097 fix CI 'Update badge' steps failure
  tools/scripts/e2ecover.sh
Labels: release/none

#3099 docs: Update upgrade docs
  README-zh_CN.md
  docs/README-zh_CN.md
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
Labels: kind/doc, release/none, cherrypick-release-v0.9

#3101 fix: Added judgment that SpiderControllerLeases.Spec.HolderIdentity is an empty string.
  test/e2e/reliability/reliability_test.go
Labels: kind/test, release/none

#3107 docs: Added docs for ebpf acceleration of pods on the same node
  docs/concepts/io-performance-zh_CN.md
  docs/concepts/io-performance.md
  docs/usage/install/system-requirements-zh_CN.md
Labels: pr/ready-review, kind/doc, release/none, cherrypick-release-v0.9

#3110 docs: Added docs for ebpf acceleration of pods on the same node
  docs/concepts/io-performance-zh_CN.md
  docs/concepts/io-performance.md
  docs/usage/install/system-requirements-zh_CN.md
Labels: robot-cherrypick, release/none

#3113 Add inline comment to code blocks in docs
  docs/mkdocs.yml
  docs/usage/install/underlay/get-started-calico-zh_CN.md
  docs/usage/install/underlay/get-started-calico.md
Labels: kind/doc, release/none

#3112 Fix formats in underlay and overlay docs
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-calico-zh_CN.md
  docs/usage/install/underlay/get-started-calico.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-sriov.md
  docs/usage/install/underlay/get-started-weave-zh_CN.md
  docs/usage/install/underlay/get-started-weave.md
Labels: kind/doc, release/none

#3116 fix ippool inherits subnet attributes e2e case
  test/e2e/ippoolcr/ippoolcr_test.go
Labels: pr/ready-review, kind/ci-bug, release/none

#3117 fix e2e concurrency problems
  test/e2e/assignip/assignip_test.go
Labels: pr/ready-review, kind/ci-bug, release/none

#3123 optimize spiderpool-init restart spiderpool-agent codes
  cmd/spiderpool-init/cmd/client.go
Labels: pr/ready-review, enhancement, release/none, cherrypick-release-v0.9

#3062 Spidercoordinator: It able to get CIDR from kubeadm-config
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/coordinatormanager/coordinator_informer.go
  test/doc/spidercoodinator.md
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#3118 fix coordinator upgrade panic with CRD property empty
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/spiderpool-init/cmd/root.go
  docs/reference/crd-spidercoordinator.md
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
Labels: pr/ready-review, release/bug, cherrypick-release-v0.9

#3124 optimize spiderpool-init restart spiderpool-agent codes
  cmd/spiderpool-init/cmd/client.go
Labels: robot-cherrypick, release/none

#3127 fix coordinator upgrade panic with CRD property empty
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  cmd/spiderpool-init/cmd/root.go
  docs/reference/crd-spidercoordinator.md
  docs/usage/install/upgrade-zh_CN.md
  docs/usage/install/upgrade.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
Labels: robot-cherrypick, release/none

#3128 e2e: case miss labels
  test/doc/spidercoodinator.md
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: kind/test, release/none

#3002 IP reclaim: differentiate stateless workload under deleting-timeout state on ready node and not-ready node
  .github/.spelling
  charts/spiderpool/README.md
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  docs/reference/spiderpool-controller.md
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/pod_cache.go
  pkg/nodemanager/utils.go
  pkg/nodemanager/utils_test.go
  test/doc/reclaim.md
  test/e2e/ippoolcr/ippoolcr_test.go
  test/e2e/reclaim/reclaim_test.go
  test/yamls/global-kind.yaml
Labels: pr/ready-review, release/feature-new

#3129 Spidercoordinator: It able to get CIDR from kubeadm-config
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/coordinatormanager/coordinator_informer.go
  test/doc/spidercoodinator.md
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: robot-cherrypick, release/bug

#3130 Spidercoordinator: It able to get CIDR from kubeadm-config
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  pkg/coordinatormanager/coordinator_informer.go
  test/doc/spidercoodinator.md
  test/e2e/common/constant.go
  test/e2e/common/mode.go
  test/e2e/spidercoordinator/spidercoordinator_suite_test.go
  test/e2e/spidercoordinator/spidercoordinator_test.go
  test/scripts/install-default-cni.sh
Labels: robot-cherrypick, release/bug

#3131 fix image link
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: release/none, cherrypick-release-v0.9

#3133 fix image link
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: robot-cherrypick, release/none

#3136 CI: make k8s 1.29 to default
  .github/workflows/e2e-init.yaml
Labels: release/none

#3137 docs: bandwidth for ipvlan datapath
  docs/mkdocs.yml
  docs/usage/ipvlan_bandwidth-zh_CN.md
  docs/usage/ipvlan_bandwidth.md
Labels: release/feature-new

#3140 CI: Fix E2E_KIND_IMAGE_TAG don't works
  .github/workflows/e2e-init.yaml
Labels: release/none

#3144 update spiderpool to v0.9.1
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/ready-review, release/none

#3152 Added signoff for robot submission changelog
  .github/workflows/call-release-changelog.yaml
Labels: robot-cherrypick, release/none

#3153 Added signoff for robot submission changelog
  .github/workflows/call-release-changelog.yaml
Labels: robot-cherrypick, release/none

#3154 Added signoff for robot submission changelog
  .github/workflows/call-release-changelog.yaml
Labels: robot-cherrypick, release/none

#3158 typo
  .github/workflows/e2e-init.yaml
Labels: pr/dependabot/github-actions, release/none

#3157 fix coordinator e2e V00003
  go.mod
  go.sum
  test/e2e/spidercoordinator/spidercoordinator_test.go
  vendor/github.com/spidernet-io/e2eframework/framework/configmap.go
  vendor/github.com/spidernet-io/e2eframework/framework/daemonset.go
  vendor/github.com/spidernet-io/e2eframework/framework/deployment.go
  vendor/github.com/spidernet-io/e2eframework/framework/error.go
  vendor/github.com/spidernet-io/e2eframework/framework/events.go
  vendor/github.com/spidernet-io/e2eframework/framework/job.go
  vendor/github.com/spidernet-io/e2eframework/framework/replicaset.go
  vendor/github.com/spidernet-io/e2eframework/framework/statefulset.go
  vendor/modules.txt
Labels: pr/ready-review, release/none

#3081 release conflicted ip of stateless workload to trigger assigning a new one
  api/v1/agent/client/daemonset/delete_ipam_ips_parameters.go
  api/v1/agent/client/daemonset/delete_ipam_ips_responses.go
  api/v1/agent/models/ipam_batch_del_args.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  api/v1/agent/server/restapi/daemonset/delete_ipam_ips_parameters.go
  api/v1/agent/server/restapi/daemonset/delete_ipam_ips_responses.go
  charts/spiderpool/crds/spiderpool.spidernet.io_spiderendpoints.yaml
  cmd/coordinator/cmd/command_add.go
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-agent/cmd/ipam.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/develop/roadmap.md
  docs/reference/spiderpool-agent.md
  pkg/constant/errors.go
  pkg/ipam/config.go
  pkg/ipam/ipam.go
  pkg/ipam/release.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spiderendpoint_types.go
  pkg/networking/ipchecking/ipchecking.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager_test.go
  test/doc/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: pr/ready-review, release/feature-new

#3159 update to v0.8.5
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/ready-review, release/none

#3166 e2e: fix typo in serviceCIDR case
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/none

#3167 rebase: fix e2e curl failure
  test/e2e/performance/performance_test.go
Labels: release-v0.7, release/none
