Repository spidernet-io/spiderpool, pull requests merged in 2024-03, with the labels that each got.

#3268 Add a low-k8s version of job to PR CI
  .github/workflows/auto-pr-ci.yaml
Labels: enhancement, kind/test, release/none

#3273 Update document format
  docs/concepts/coordinator-zh_CN.md
  docs/reference/plugin-ifacer.md
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/install/underlay/get-started-sriov-zh_CN.md
  docs/usage/install/underlay/get-started-sriov.md
Labels: robot-cherrypick, kind/doc, release/none

#3269 Fix panic in spidercoordinator informer
  pkg/coordinatormanager/coordinator_informer.go
Labels: release/bug, cherrypick-release-v0.9

#3274 Fix panic in spidercoordinator informer
  pkg/coordinatormanager/coordinator_informer.go
Labels: robot-cherrypick, release/bug

#3278 Free Disk Space for CI
  .github/workflows/e2e-init.yaml
Labels: kind/cleanup, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3284 spidercoordinator: Enhance the edge case
  pkg/coordinatormanager/coordinator_informer.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#3286 spidercoordinator: Enhance the edge case
  pkg/coordinatormanager/coordinator_informer.go
Labels: robot-cherrypick, release/bug

#3287 spidercoordinator: Enhance the edge case
  pkg/coordinatormanager/coordinator_informer.go
Labels: robot-cherrypick, release/bug

#3283 spidermultusconfig: add missing filed for generateCoordinatorCNIConf
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/utils.go
Labels: release/bug

#3291 Spidercoordinator: sync kubeadm-config event to trigger the status update
  go.mod
  pkg/coordinatormanager/coordinator_informer.go
Labels: release/bug, release-v0.8, cherrypick-release-v0.8, cherrypick-release-v0.9

#3294 Spidercoordinator: sync kubeadm-config event to trigger the status update
  go.mod
  pkg/coordinatormanager/coordinator_informer.go
Labels: robot-cherrypick, release/bug, release-v0.9

#3297 bump version to v0.9.2
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#3302 coordinator: rework GetDefaultRouteInterface to get pod's default route nic
  pkg/networking/networking/route.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#3307 coordinator: rework GetDefaultRouteInterface to get pod's default route nic
  pkg/networking/networking/route.go
Labels: robot-cherrypick, release/bug

#3306 coordinator: rework GetDefaultRouteInterface to get pod's default route nic
  pkg/networking/networking/route.go
Labels: robot-cherrypick, release/bug

#3304 Spidercoordinator: Add kubeadm-config event to workQueue
  go.mod
  pkg/coordinatormanager/coordinator_informer.go
Labels: release/bug

#3265 Add e2e about multiple NICs
  test/doc/coordinator.md
  test/e2e/common/constant.go
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: kind/test, release/none

#3305 Added docs for node NIC renaming
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
Labels: kind/feature, kind/doc, release/none

#3312 bump release-v0.8 to v0.8.6
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#3317 Fixed the failure to obtain environment variables in build-image-base.yaml
  .github/workflows/build-image-base.yaml
Labels: release/none, cherrypick-release-v0.9

#3320 Fixed the failure to obtain environment variables in build-image-base.yaml
  .github/workflows/build-image-base.yaml
Labels: robot-cherrypick, release/none

#3326 docs: update installtion for spidercoordinator
  docs/usage/install/underlay/get-started-macvlan-zh_CN.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs-zh_CN.md
  docs/usage/install/underlay/get-started-ovs.md
Labels: release/none
