Repository spidernet-io/spiderpool, pull requests merged in 2024-02, with the labels that each got.

#3176 robot: add committer for create_pr
  .github/workflows/call-release-changelog.yaml
Labels: pr/dependabot/github-actions, cherrypick-release-v0.7, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3177 robot: add committer for create_pr
  .github/workflows/call-release-changelog.yaml
Labels: robot-cherrypick, release/none

#3178 robot: add committer for create_pr
  .github/workflows/call-release-changelog.yaml
Labels: robot-cherrypick, release/none

#3179 robot: add committer for create_pr
  .github/workflows/call-release-changelog.yaml
Labels: robot-cherrypick, release/none

#3168 enable coordinate to support serviceCIDR according to a matched k8s version.
  pkg/coordinatormanager/coordinator_informer.go
  test/Makefile
  test/scripts/install-default-cni.sh
  test/yamls/global-kind.yaml
Labels: release/bug

#3185 add kubernetes serviceCIDR APIResource register validation
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/constant/k8s.go
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/service_cidr_informer.go
Labels: pr/ready-review, enhancement, release/none

#3160 release v0.7.3
  VERSION
  charts/spiderpool/Chart.yaml
Labels: pr/ready-review, release/none

#3182 use helm charts value control coordinator components startup
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/templates/tls.yaml
  cmd/spiderpool-controller/cmd/config.go
  cmd/spiderpool-controller/cmd/daemon.go
Labels: pr/ready-review, cherrypick-release-v0.7, release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9

#3201 Update auto-pr-ci.yaml
  .github/workflows/auto-pr-ci.yaml
Labels: release/none

#3195 docs: Update supported stable versions
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: cherrypick-release-v0.7, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3207 docs: Update supported stable versions
  README-zh_CN.md
  README.md
  docs/README-zh_CN.md
  docs/README.md
Labels: robot-cherrypick, release/none

#3211 fix the logic of obtaining kubeadm-config to avoid being unable to create Pods
  pkg/coordinatormanager/coordinator_informer.go
  test/scripts/install-default-cni.sh
Labels: release/bug, release-v0.9

#3208 docs: typo
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-macvlan.md
Labels: release/none, cherrypick-release-v0.9

#3227 Fix typos in usage and underlay-install docs
  docs/usage/egress.md
  docs/usage/install/underlay/get-started-calico.md
  docs/usage/install/underlay/get-started-macvlan.md
  docs/usage/install/underlay/get-started-ovs.md
  docs/usage/install/underlay/get-started-weave.md
Labels: pr/ready-review, kind/doc, release/none

#3228 docs: typo
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/underlay/get-started-macvlan.md
Labels: robot-cherrypick, release/none

#3186 Add e2e about service spec.externalTrafficPolicy
  test/doc/coordinator.md
  test/doc/ifacer.md
  test/doc/spidercoodinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
  test/e2e/coordinator/macvlan-underlay-one/macvlan_underlay_one_test.go
Labels: kind/test, release/none

#3229 optimize makefile for e2e setup
  test/Makefile
Labels: pr/ready-review, enhancement, release/none

#3223 supplement pyroscope profile types
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  test/Makefile.defs
Labels: pr/ready-review, enhancement, cherrypick-release-v0.7, release/none, cherrypick-release-v0.8, cherrypick-release-v0.9

#3226 optimize e2e kubelet restart case
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-controller/cmd/daemon.go
  cmd/spiderpool-controller/cmd/runtime_status.go
  pkg/constant/k8s.go
  pkg/openapi/webhook_checker.go
  test/e2e/reclaim/reclaim_test.go
Labels: pr/ready-review, enhancement, release/none

#3236 supplement pyroscope profile types
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  test/Makefile.defs
Labels: robot-cherrypick

#3244 Ignore local-path-storage log messages
  test/scripts/debugEnv.sh
Labels: release/none

#3246 fix e2e cilium installation failure with IPv6
  test/scripts/install-default-cni.sh
Labels: pr/ready-review, kind/ci-bug, release/none

#3245 fix e2e cilium installation failure with IPv6
  test/scripts/install-default-cni.sh
Labels: pr/ready-review, kind/ci-bug, release/none

#3250 automatically port the label from the initial cherry-picked PR
  .github/workflows/auto-cherrypick.yaml
Labels: release/none

#3235 supplement pyroscope profile types
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  test/Makefile.defs
Labels: robot-cherrypick

#3234 supplement pyroscope profile types
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/daemon.go
  test/Makefile.defs
Labels: robot-cherrypick

#3243 Support getting serviceCIDR from spec.Containers[0].Args of kube-controller-manager Pod
  pkg/coordinatormanager/coordinator_informer.go
Labels: release/bug

#3257 clean up source codes todo
  cmd/spiderpool-agent/cmd/command_shutdown.go
  cmd/spiderpool-controller/cmd/command_daemon.go
  cmd/spiderpool-controller/cmd/command_shutdown.go
  cmd/spiderpool-controller/cmd/command_status.go
  cmd/spiderpool-controller/cmd/config.go
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/pod_cache.go
  pkg/ipam/allocate.go
  pkg/ippoolmanager/ippool_mutate.go
  pkg/ippoolmanager/ippool_validate.go
  pkg/subnetmanager/subnet_informer_test.go
  pkg/subnetmanager/subnet_manager.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/doc/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: enhancement, release/none
