Repository spidernet-io/spiderpool, pull requests merged in 2024-11, with the labels that each got.

#4251 Add a flag to configure an link-local address to veth0 for istio
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/README.md
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-agent/cmd/coordinator.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/root.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/mkdocs.yml
  docs/reference/crd-spidercoordinator.md
  docs/usage/istio-zh_CN.md
  docs/usage/istio.md
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/utils.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
  test/scripts/install-multus.sh
Labels: robot-cherrypick, release/feature-new

#4246 Fix podwebhook cert don't update when spiderpool-controller restart
  pkg/podmanager/utils.go
  pkg/podmanager/utils_test.go
  test/Makefile
Labels: robot-cherrypick, release/none

#4252 Add a flag to configure an link-local address to veth0 for istio
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/README.md
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-agent/cmd/coordinator.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/root.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/mkdocs.yml
  docs/reference/crd-spidercoordinator.md
  docs/usage/istio-zh_CN.md
  docs/usage/istio.md
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/utils.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
  test/scripts/install-multus.sh
Labels: robot-cherrypick, release/feature-new

#4249 fix: scanAll typo
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-init/cmd/client.go
  docs/concepts/arch-zh_CN.md
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/usage/network-topology-zh_CN.md
  docs/usage/network-topology.md
  docs/usage/route-zh_CN.md
  pkg/coordinatormanager/coordinator_validate.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/ip/cidr.go
  pkg/multuscniconfig/multusconfig_validate.go
Labels: robot-cherrypick, release/none

#4248 fix: scanAll typo
  cmd/spiderpool-agent/cmd/daemon.go
  cmd/spiderpool-controller/cmd/crd_manager.go
  cmd/spiderpool-init/cmd/client.go
  docs/concepts/arch-zh_CN.md
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/usage/network-topology-zh_CN.md
  docs/usage/network-topology.md
  docs/usage/route-zh_CN.md
  pkg/coordinatormanager/coordinator_validate.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/ip/cidr.go
  pkg/multuscniconfig/multusconfig_validate.go
Labels: robot-cherrypick, release/none

#4261 Add a flag to configure an link-local address to veth0 for istio
  api/v1/agent/models/coordinator_config.go
  api/v1/agent/openapi.yaml
  api/v1/agent/server/embedded_spec.go
  charts/spiderpool/README.md
  charts/spiderpool/crds/spiderpool.spidernet.io_spidercoordinators.yaml
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  charts/spiderpool/templates/pod.yaml
  charts/spiderpool/values.yaml
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  cmd/coordinator/cmd/utils.go
  cmd/spiderpool-agent/cmd/coordinator.go
  cmd/spiderpool-init/cmd/config.go
  cmd/spiderpool-init/cmd/root.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  docs/mkdocs.yml
  docs/reference/crd-spidercoordinator.md
  docs/usage/istio-zh_CN.md
  docs/usage/istio.md
  pkg/coordinatormanager/coordinator_mutate.go
  pkg/coordinatormanager/coordinator_validate.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidercoordinator_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/utils.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
  test/scripts/install-multus.sh
Labels: release/feature-new

#4258 podResourceInject: annotate a group of spidermultusconfig without labels
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/ai/get-started-sriov-zh_CN.md
  docs/usage/install/ai/get-started-sriov.md
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/utils.go
  pkg/podmanager/utils.go
  pkg/podmanager/utils_test.go
  test/doc/spidermultus.md
  test/e2e/podwebhook/podwebhook_test.go
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/none

#4259 Add RDMA ref in AI scene doc.
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/ai/get-started-sriov-zh_CN.md
  docs/usage/install/ai/get-started-sriov.md
Labels: pr/release/doc, release/none

#4271 Remove ServiceMonitor dup namespaceSelector
  charts/spiderpool/templates/servicemonitor.yaml
Labels: kind/bug, release/bug

#4276 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
Labels: release/none, pr/release/robot_update_version

#4268 optimize rdma metrics and podwebhook docs
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/ai/get-started-sriov-zh_CN.md
  docs/usage/install/ai/get-started-sriov.md
  docs/usage/rdma-metrics-zh_CN.md
  docs/usage/rdma-metrics.md
Labels: release/none, cherrypick-release-v1.0

#4305 Update base image
  images/spiderpool-agent/Dockerfile
  images/spiderpool-controller/Dockerfile
Labels: release/none

#4285 Fix TOOMANYREQUESTS failure in Trivy Action
  .github/workflows/build-image-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/trivy-scan-image.yaml
  Makefile
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4320 Fix TOOMANYREQUESTS failure in Trivy Action
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/trivy-scan-image.yaml
  test/Makefile
Labels: robot-cherrypick, release/none, release-v0.8

#4319 Fix TOOMANYREQUESTS failure in Trivy Action
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/trivy-scan-image.yaml
  test/Makefile
Labels: robot-cherrypick, release/none, release-v0.9

#4318 Fix TOOMANYREQUESTS failure in Trivy Action
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/trivy-scan-image.yaml
  Makefile
  test/Makefile
Labels: robot-cherrypick, release/none, release-v1.0

#4316 After changing the image type to docker, updating CI should synchronize the changes.
  .github/workflows/auto-upgrade-ci.yaml
Labels: kind/test, release/none

#4324 update codeowners file
  CODEOWNERS
Labels: release/none

#4293 fix: after the installation of openvswitch failed, retrying did not work.
  test/scripts/install-ovs.sh
Labels: release/none, cherrypick-release-v0.9, cherrypick-release-v1.0

#4322 charts: Fix error nident in daemonset.yaml
  charts/spiderpool/templates/daemonset.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/podmanager/utils.go
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4326 fix: after the installation of openvswitch failed, retrying did not work.
  test/scripts/install-ovs.sh
Labels: robot-cherrypick, release/none

#4325 fix: after the installation of openvswitch failed, retrying did not work.
  test/scripts/install-ovs.sh
Labels: robot-cherrypick, release/none

#4331 charts: Fix error nident in daemonset.yaml
  charts/spiderpool/templates/daemonset.yaml
Labels: robot-cherrypick, release/none, release-v0.9

#4330 charts: Fix error nident in daemonset.yaml
  charts/spiderpool/templates/daemonset.yaml
Labels: robot-cherrypick, release/none, release-v1.0

#4280 fix: pod not-ready causes webhook call failure
  test/e2e/reclaim/reclaim_test.go
Labels: release/none, cherrypick-release-v1.0

#4336 fix: pod not-ready causes webhook call failure
  test/e2e/reclaim/reclaim_test.go
Labels: robot-cherrypick, release/none

#4333 bump version to v1.0.0-rc3
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none
