Repository spidernet-io/spiderpool, pull requests merged in 2025-09, with the labels that each got.

#5115 Fix json formatting for configList in rdma-shared-dp.yaml to ensure p…
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/templates/rdma-shared-dp/rdma-shared-dp.yaml
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#5137 rdma rule
  tools/scripts/setRdmaRule.sh
Labels: robot-cherrypick, release/none

#5178 e2e: fix kubevirt vm can't running
  Makefile
  test/scripts/debugEnv.sh
  test/scripts/install-kubevirt.sh
Labels: release/none, cherrypick-release-v0.9, cherrypick-release-v1.0
