Repository spidernet-io/spiderpool, pull requests merged in 2025-01, with the labels that each got.

#4507 Detecting IP conflicts takes place before gateway detection, avoiding communication failure
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug, release-v1.0

#4506 Detecting IP conflicts takes place before gateway detection, avoiding communication failure
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug, release-v0.9

#4505 Detecting IP conflicts takes place before gateway detection, avoiding communication failure
  cmd/coordinator/cmd/cni_types.go
  cmd/coordinator/cmd/command_add.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go
Labels: release/bug, release-v0.8

#4504 coodirnator: optimize the detectiong timeout for ip conflict and gateway detection
  cmd/coordinator/cmd/cni_types.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  pkg/errgroup/errgroup.go
  pkg/networking/gwconnection/connection.go
  pkg/networking/ipchecking/ipchecking.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4511 coodirnator: optimize the detectiong timeout for ip conflict and gateway detection
  Makefile
  cmd/coordinator/cmd/cni_types.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_informer_test.go
  pkg/coordinatormanager/coordinatormanager_suite_test.go
  pkg/errgroup/errgroup.go
  pkg/ippoolmanager/config_test.go
  pkg/networking/gwconnection/connection.go
  pkg/networking/ipchecking/ipchecking.go
  pkg/utils/utils.go
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/bug, release-v0.9

#4512 coodirnator: optimize the detectiong timeout for ip conflict and gateway detection
  Makefile
  cmd/coordinator/cmd/cni_types.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_informer_test.go
  pkg/coordinatormanager/coordinatormanager_suite_test.go
  pkg/errgroup/errgroup.go
  pkg/ippoolmanager/config_test.go
  pkg/networking/gwconnection/connection.go
  pkg/networking/ipchecking/ipchecking.go
  pkg/utils/utils.go
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
  test/e2e/spidercoordinator/spidercoordinator_test.go
Labels: release/bug, release-v0.8

#4510 coodirnator: optimize the detectiong timeout for ip conflict and gateway detection
  cmd/coordinator/cmd/cni_types.go
  docs/concepts/coordinator-zh_CN.md
  docs/concepts/coordinator.md
  pkg/errgroup/errgroup.go
  pkg/networking/gwconnection/connection.go
  pkg/networking/ipchecking/ipchecking.go
Labels: robot-cherrypick, release/bug

#4518 Release v0.8.9
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#4517 Release v0.9.8
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#4516 Release-1.0: bump version to v1.0.0-rc4
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#4532 doc: blog
  docs/concepts/blog-zh_CN.md
  docs/concepts/blog.md
Labels: release/none

#4535 Update blog.md
  docs/concepts/blog.md
Labels: release/none

#4536 Update blog-zh_CN.md
  docs/concepts/blog-zh_CN.md
Labels: release/none

#4542 CI: Debug openkruise installtion
  test/Makefile
Labels: release/none

#4562 CI: fix upload charts artifact
  .github/workflows/update-chart-readme.yml
Labels: release/none, cherrypick-release-v1.0

#4566 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
Labels: release/none, pr/release/robot_update_version

#4561 optimize the amount of ip usage
  pkg/ippoolmanager/ippool_manager.go
Labels: release/none

#4579 CI: FIx lint openapi yaml
  .github/workflows/lint-openapi.yaml
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4585 CI: Fix ImagePullBackOff for kruise instation
  test/Makefile
  test/Makefile.defs
Labels: release/none

#4421 add annotation cni.spidernet.io/network-resource-inject
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/ai/get-started-sriov-zh_CN.md
  docs/usage/install/ai/get-started-sriov.md
  docs/usage/install/overlay/get-started-calico-zh_cn.md
  docs/usage/install/overlay/get-started-calico.md
  docs/usage/install/overlay/get-started-cilium-zh_cn.md
  docs/usage/install/overlay/get-started-cilium.md
  docs/usage/install/overlay/multi-underlay-nic-zh_CN.md
  docs/usage/install/overlay/multi-underlay-nic.md
  pkg/constant/k8s.go
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_informer_test.go
  pkg/coordinatormanager/coordinatormanager_suite_test.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/utils.go
  pkg/podmanager/pod_webhook.go
  pkg/podmanager/utils.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: pr/ready-review, release/feature-new

#4591 Release-0.8: bump version to v0.8.10
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none, release-v0.8

#4590 Release-0.9: bump version to v0.9.9
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#4589 bump version to v1.0.0
  VERSION
  charts/spiderpool/Chart.yaml
  pkg/coordinatormanager/coordinator_informer.go
  pkg/coordinatormanager/coordinator_informer_test.go
  pkg/coordinatormanager/coordinatormanager_suite_test.go
Labels: release/none

#4600 Fix typo
  pkg/multuscniconfig/multusconfig_validate.go
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/none
