Repository spidernet-io/spiderpool, pull requests merged in 2025-06, with the labels that each got.

#4900 Add node rdma device traffic class to metrics
  charts/spiderpool/files/grafana-rdma-node.json
  docs/reference/metrics.md
  pkg/rdmametrics/metrics.go
  pkg/rdmametrics/tos.go
  pkg/rdmametrics/tos_test.go
Labels: release/feature-new, v1.1.0

#4948 Remove outdated endpoints to prevent blocking the creation of new Pods
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/ipam/allocate.go
  pkg/types/k8s.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/Makefile
  test/e2e/annotation/annotation_test.go
Labels: release/bug, cherrypick-release-v0.9, cherrypick-release-v1.0

#4960 Remove outdated endpoints to prevent blocking the creation of new Pods
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/scanAll_IPPool.go
  pkg/gcmanager/tracePod_worker.go
  pkg/ipam/allocate.go
  pkg/types/k8s.go
  pkg/workloadendpointmanager/workloadendpoint_manager.go
  test/Makefile
  test/e2e/annotation/annotation_test.go
Labels: robot-cherrypick, release/bug

#4965 bump version to v0.9.13
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#4974 Add a knob to initiate webhook deletion checks for ip resources (#4675)
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/podmanager/pod_manager_suite_test.go
  pkg/podmanager/pod_webhook.go
  pkg/podmanager/pod_webhook_test.go
  pkg/subnetmanager/subnet_webhook.go
  pkg/subnetmanager/subnet_webhook_test.go
  pkg/types/k8s.go
  test/e2e/common/resourceclaim.go
Labels: release/feature-changed, release-v1.0
