Repository spidernet-io/spiderpool, pull requests merged in 2025-08, with the labels that each got.

#5039 Optimize GitHub Actions to prevent duplicate PRs
  .github/workflows/auto-update-authors.yaml
  .github/workflows/update-cniplugins-version.yaml
  .github/workflows/update-golang-version.yaml
Labels: enhancement, release/none, automation

#5040 docs: add comprehensive repository documentation for OpenHands
  .openhands/microagents/repo.md
Labels: release/none

#5041 Update CODEOWNERS
  CODEOWNERS
Labels: release/none

#5066 Optimize IPConflictDetection to fix syscall fails to receive ARP resp…
  cmd/spiderpool/cmd/cni_types.go
  cmd/spiderpool/cmd/command_add.go
  cmd/spiderpool/cmd/command_test.go
  go.mod
  go.sum
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/networking/networking/ipam_detection.go
  vendor/github.com/josharian/native/doc.go
  vendor/github.com/josharian/native/endian_big.go
  vendor/github.com/josharian/native/endian_generic.go
  vendor/github.com/josharian/native/endian_little.go
  vendor/github.com/josharian/native/license
  vendor/github.com/josharian/native/readme.md
  vendor/github.com/mdlayher/arp/.travis.yml
  vendor/github.com/mdlayher/arp/LICENSE.md
  vendor/github.com/mdlayher/arp/README.md
  vendor/github.com/mdlayher/arp/client.go
  vendor/github.com/mdlayher/arp/doc.go
  vendor/github.com/mdlayher/arp/fuzz.go
  vendor/github.com/mdlayher/arp/packet.go
  vendor/github.com/mdlayher/arp/string.go
  vendor/github.com/mdlayher/ethernet/.travis.yml
  vendor/github.com/mdlayher/ethernet/LICENSE.md
  vendor/github.com/mdlayher/ethernet/README.md
  vendor/github.com/mdlayher/ethernet/ethernet.go
  vendor/github.com/mdlayher/ethernet/fuzz.go
  vendor/github.com/mdlayher/ethernet/string.go
  vendor/github.com/mdlayher/ethernet/vlan.go
  vendor/github.com/mdlayher/packet/.gitignore
  vendor/github.com/mdlayher/packet/CHANGELOG.md
  vendor/github.com/mdlayher/packet/LICENSE.md
  vendor/github.com/mdlayher/packet/README.md
  vendor/github.com/mdlayher/packet/doc.go
  vendor/github.com/mdlayher/packet/packet.go
  vendor/github.com/mdlayher/packet/packet_linux.go
  vendor/github.com/mdlayher/packet/packet_others.go
  vendor/github.com/mdlayher/socket/CHANGELOG.md
  vendor/github.com/mdlayher/socket/LICENSE.md
  vendor/github.com/mdlayher/socket/README.md
  vendor/github.com/mdlayher/socket/accept.go
  vendor/github.com/mdlayher/socket/accept4.go
  vendor/github.com/mdlayher/socket/conn.go
  vendor/github.com/mdlayher/socket/conn_linux.go
  vendor/github.com/mdlayher/socket/doc.go
  vendor/github.com/mdlayher/socket/netns_linux.go
  vendor/github.com/mdlayher/socket/netns_others.go
  vendor/github.com/mdlayher/socket/setbuffer_linux.go
  vendor/github.com/mdlayher/socket/setbuffer_others.go
  vendor/github.com/mdlayher/socket/typ_cloexec_nonblock.go
  vendor/github.com/mdlayher/socket/typ_none.go
  vendor/modules.txt
Labels: release/bug, release-v1.0

#5083 Refactor DSCP mapping in rdma-qos.sh
  docs/example/qos/rdma-qos.sh
Labels: release/bug, cherrypick-release-v1.0
