Repository spidernet-io/spiderpool, pull requests merged in 2025-02, with the labels that each got.

#4623 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
Labels: release/none, pr/release/robot_update_version

#4628 CI: make open-kruise version to 1.7.2
  .github/workflows/call-lint-chart.yaml
  test/Makefile.defs
Labels: release/none

#4639 CI: fix cilium multiPoolPreAllocation installtion
  test/scripts/install-default-cni.sh
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4645 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
  go.mod
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
Labels: release/none, pr/release/robot_update_version

#4633 webhook: prevent delete ippool with allocated IPs
  pkg/ippoolmanager/ippool_webhook.go
  pkg/subnetmanager/subnet_webhook.go
Labels: release/none

#4649 Ensure kernel sends GARPs to avoid communication failures
  cmd/spiderpool/cmd/command_add.go
  pkg/networking/networking/packet.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4657 bump version to v1.0.1
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#4663 Update charts for ippool/subnet ValidatingWebhook
  charts/spiderpool/templates/tls.yaml
Labels: release/bug

#4675 Add a knob to initiate webhook deletion checks for ip resources
  charts/spiderpool/README.md
  charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/daemon.go
  pkg/ippoolmanager/ippool_webhook.go
  pkg/ippoolmanager/ippool_webhook_test.go
  pkg/podmanager/pod_manager_suite_test.go
  pkg/podmanager/pod_webhook.go
  pkg/podmanager/pod_webhook_test.go
  pkg/subnetmanager/subnet_webhook.go
  pkg/subnetmanager/subnet_webhook_test.go
  pkg/types/k8s.go
  test/e2e/common/resourceclaim.go
Labels: release/feature-changed

#4681 Ensure kernel sends GARPs to avoid communication failures
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/auto-version-release.yaml
  .github/workflows/build-image-base.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/build-image-plugins.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-release-image.yaml
  .github/workflows/call-update-githubpages.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-yaml.yaml
  .github/workflows/trivy-scan-image.yaml
  .github/workflows/update-chart-readme.yml
  cmd/spiderpool/cmd/command_add.go
  pkg/networking/networking/packet.go
Labels: release/bug, release-v0.8, cherrypick-release-v0.9

#4684 Bump gh-actions deps
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/auto-version-release.yaml
  .github/workflows/build-image-base.yaml
  .github/workflows/build-image-ci.yaml
  .github/workflows/build-image-plugins.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-doc.yaml
  .github/workflows/call-release-image.yaml
  .github/workflows/call-update-githubpages.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-yaml.yaml
  .github/workflows/trivy-scan-image.yaml
  .github/workflows/update-chart-readme.yml
Labels: release/bug, release-v0.9

#4690 CI: Fix fail to upload artifact for same name
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/e2e-init.yaml
Labels: release/none

#4691 Bump gh-actions deps for release-v0.9
  .github/workflows/auto-pr-ci.yaml
Labels: release/none, release-v0.9

#4689 IPAM sends GARPS to updating arp cache table
  cmd/spiderpool/cmd/command_add.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/networking/networking/packet.go
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/bug, release-v1.0

#4646 Docs: add mtu size configuration and RDMA QoS
  docs/example/qos/rdma-qos.sh
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/ai/get-started-sriov-zh_CN.md
  docs/usage/install/ai/get-started-sriov.md
  docs/usage/roce-qos-zh_CN.md
  docs/usage/roce-qos.md
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
Labels: release/none

#4636 SpiderMultusConfig: Add mtu size support for macvlan / ipvlan / sriov
  charts/spiderpool/crds/spiderpool.spidernet.io_spidermultusconfigs.yaml
  docs/reference/crd-spidermultusconfig.md
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/spidermultus_types.go
  pkg/k8s/apis/spiderpool.spidernet.io/v2beta1/zz_generated.deepcopy.go
  pkg/multuscniconfig/multusconfig_informer.go
  pkg/multuscniconfig/multusconfig_mutate.go
  pkg/multuscniconfig/multusconfig_validate.go
  pkg/multuscniconfig/utils.go
  test/doc/spidermultus.md
  test/e2e/spidermultus/spidermultus_test.go
Labels: release/feature-new

#4696 Release-0.8: bump version to v0.8.11
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none, release-v0.8

#4697 Release-0.9: bump version to v0.9.10
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none
