Repository spidernet-io/spiderpool, pull requests merged in 2025-05, with the labels that each got.

#4857 CI: ubuntu20-04 has been depreted
  .github/workflows/auto-nightly-ci.yaml
Labels: release/none

#4830 Update cni latest plugin
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: release/none

#4861 doc: set rdma nic
  docs/usage/install/ai/get-started-macvlan-zh_CN.md
  docs/usage/install/ai/get-started-macvlan.md
  docs/usage/install/ai/get-started-sriov-zh_CN.md
  docs/usage/install/ai/get-started-sriov.md
  tools/scripts/setNicAddr.sh
  tools/scripts/setNicRdmaMode.sh
Labels: release/none

#4865 Fix unit test of pod owner cache
  pkg/podownercache/pod_owner_cache_test.go
Labels: release/none

#4869 Update roce-qos-zh_CN.md
  docs/usage/roce-qos-zh_CN.md
Labels: release/none

#4870 Update roce-qos-zh_CN.md
  docs/usage/roce-qos-zh_CN.md
Labels: release/none

#4862 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-grafana-file.yaml
  Makefile.version
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
Labels: release/none, pr/release/robot_update_version

#4875 Update roce-qos.md
  docs/example/qos/rdma-qos.sh
  docs/usage/roce-qos-zh_CN.md
  docs/usage/roce-qos.md
Labels: release/none

#4884 add reviewer
  CODEOWNERS
  MAINTAINERS.md
Labels: release/none

#4889 ipam: add GC option for running pods with empty podIPs
  charts/spiderpool/README.md
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  docs/reference/spiderpool-controller.md
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/scanAll_IPPool.go
Labels: release/feature-new, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4897 ipam: add GC option for running pods with empty podIPs
  charts/spiderpool/README.md
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  docs/reference/spiderpool-controller.md
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/scanAll_IPPool.go
Labels: robot-cherrypick, release/feature-new

#4894 Add node name filter for pod owner cache to track local pods only
  charts/spiderpool/templates/daemonset.yaml
  cmd/spiderpool-agent/cmd/config.go
  cmd/spiderpool-agent/cmd/metrics_server.go
  pkg/constant/k8s.go
  pkg/podownercache/pod_owner_cache.go
  pkg/podownercache/pod_owner_cache_test.go
Labels: robot-cherrypick, release/bug

#4898 Fix metrics miss vport data from ethtool
  pkg/rdmametrics/ethtool/ethtool.go
Labels: release/bug, cherrypick-release-v1.0

#4914 ipam: add GC option for running pods with empty podIPs
  charts/spiderpool/README.md
  charts/spiderpool/templates/deployment.yaml
  charts/spiderpool/values.yaml
  cmd/spiderpool-controller/cmd/config.go
  docs/concepts/ipam-des-zh_CN.md
  docs/concepts/ipam-des.md
  docs/reference/spiderpool-controller.md
  pkg/gcmanager/gc_manager.go
  pkg/gcmanager/scanAll_IPPool.go
Labels: release/feature-new, release-v0.9

#4919 bump version to v0.9.13
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none, release-v0.9

#4921 Update spiderpool agent default interval of prometheus service monitor
  charts/spiderpool/README.md
  charts/spiderpool/values.yaml
Labels: release/none
