Repository spidernet-io/spiderpool, pull requests merged in 2025-04, with the labels that each got.

#4775 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
Labels: release/none, pr/release/robot_update_version

#4784 Fix ENV EnableGCStatelessTerminatingPod(Not)ReadyNode doesn't works
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4787 Fix ENV EnableGCStatelessTerminatingPod(Not)ReadyNode doesn't works
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
Labels: robot-cherrypick, release/bug

#4765 e2e: bump k8s version to 1.32
  test/Makefile.defs
Labels: release/none

#4803 cni version: get the newest one
  tools/scripts/updateLatestCniPluginVersion.sh
Labels: release/none

#4812 Add pause and discards stats for RDMA metrics
  .github/grafana-check.yaml
  .github/workflows/lint-grafana-file.yaml
  charts/spiderpool/files/grafana-rdma-cluster.json
  charts/spiderpool/files/grafana-rdma-node.json
  charts/spiderpool/files/grafana-rdma-pod.json
  charts/spiderpool/files/grafana-rdma-workload.json
  docs/usage/rdma-metrics-zh_CN.md
  docs/usage/rdma-metrics.md
  pkg/rdmametrics/ethtool/ethtool.go
  pkg/rdmametrics/metrics.go
  pkg/rdmametrics/metrics_test.go
  pkg/rdmametrics/oteltype/types.go
Labels: release/feature-new

#4807 IPAM: Make ENV EnableGCStatelessTerminatingPod(Not)ReadyNode works in…
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
Labels: release/bug, release-v0.8

#4806 IPAM: Make ENV EnableGCStatelessTerminatingPod(Not)ReadyNode works in…
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
Labels: release/bug, release-v0.9

#4824 e2e: Fix cilium fail to running with ipv6 only
  test/Makefile
  test/Makefile.defs
  test/e2e/common/node.go
  test/e2e/spidercoordinator/spidercoordinator_suite_test.go
  test/scripts/install-default-cni.sh
Labels: release/none, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4840 e2e: Fix cilium fail to running with ipv6 only (#4824)
  test/Makefile
  test/e2e/common/node.go
  test/e2e/spidercoordinator/spidercoordinator_suite_test.go
  test/scripts/install-default-cni.sh
Labels: release/none, release-v1.0

#4837 CI: make k8s version to v1.32.3
  .github/workflows/auto-diff-k8s-ci.yaml
  .github/workflows/e2e-init.yaml
  test/Makefile
  test/Makefile.defs
Labels: release/none

#4839 e2e: Fix cilium fail to running with ipv6 only (#4824)
  test/e2e/common/node.go
  test/e2e/spidercoordinator/spidercoordinator_suite_test.go
  test/scripts/install-default-cni.sh
Labels: release/none, release-v0.9

#4838 e2e: Fix cilium fail to running with ipv6 only (#4824)
  test/e2e/common/node.go
  test/e2e/spidercoordinator/spidercoordinator_suite_test.go
  test/scripts/install-default-cni.sh
Labels: release/none, release-v0.8

#4841 bump version to v1.0.2
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#4843 CI: Retry update resources with the conflict error
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  test/e2e/annotation/annotation_test.go
Labels: release/none

#4846 Release-0.9: bump version to v0.9.11
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none

#4844 bump version to 0.8.12
  VERSION
  charts/spiderpool/Chart.yaml
Labels: release/none
