Repository spidernet-io/spiderpool, pull requests merged in 2025-03, with the labels that each got.

#4711 Fix RDMA multicast metric in node dashboard
  charts/spiderpool/files/grafana-rdma-node.json
Labels: robot-cherrypick, release/bug

#4710 chart: optimize rdma titles
  charts/spiderpool/files/grafana-rdma-cluster.json
  charts/spiderpool/files/grafana-rdma-node.json
  charts/spiderpool/files/grafana-rdma-pod.json
  charts/spiderpool/files/grafana-rdma-workload.json
Labels: release/feature-changed, cherrypick-release-v1.0

#4712 chart: optimize rdma titles
  charts/spiderpool/files/grafana-rdma-cluster.json
  charts/spiderpool/files/grafana-rdma-node.json
  charts/spiderpool/files/grafana-rdma-pod.json
  charts/spiderpool/files/grafana-rdma-workload.json
Labels: robot-cherrypick, release/feature-changed

#4717 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  Makefile.version
Labels: release/none, pr/release/robot_update_version

#4729 fix: retrieve the endpoint for deleted stateless pod
  pkg/gcmanager/scanAll_IPPool.go
Labels: release/bug, cherrypick-release-v0.9, cherrypick-release-v1.0

#4733 fix: retrieve the endpoint for deleted stateless pod
  pkg/gcmanager/scanAll_IPPool.go
Labels: robot-cherrypick, release/bug

#4732 fix: retrieve the endpoint for deleted stateless pod
  pkg/gcmanager/scanAll_IPPool.go
Labels: robot-cherrypick, release/bug

#4735 Modify part of the error description in the document 'multi_cni_coexist'
  docs/concepts/multi_cni_coexist-zh_CN.md
  docs/concepts/multi_cni_coexist.md
  docs/images/macvlan-macvlan-service.png
Labels: robot-cherrypick, release/none

#4738 SpiderMultusConfig: Fix error json tag for min/maxTxRateMbps (#4716)
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  pkg/constant/k8s.go
  pkg/multuscniconfig/utils.go
Labels: release/bug, release-v0.8

#4737 SpiderMultusConfig: Fix error json tag for min/maxTxRateMbps (#4716)
  docs/usage/spider-multus-config-zh_CN.md
  docs/usage/spider-multus-config.md
  pkg/constant/k8s.go
  pkg/multuscniconfig/utils.go
Labels: release/bug, release-v0.9

#4726 Update getFinalOwner method to handle not found error
  pkg/podownercache/pod_owner_cache.go
  pkg/podownercache/pod_owner_cache_test.go
Labels: robot-cherrypick, release/none

#4752 IPAM fix: ENV EnableGCStatelessTerminatingPod(Not)ReadyNode=false does not work
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
Labels: release/bug, cherrypick-release-v0.8, cherrypick-release-v0.9, cherrypick-release-v1.0

#4760 IPAM fix: ENV EnableGCStatelessTerminatingPod(Not)ReadyNode=false does not work
  pkg/gcmanager/pod_cache.go
  pkg/gcmanager/scanAll_IPPool.go
Labels: robot-cherrypick, release/bug
