Repository spidernet-io/spiderpool, pull requests merged in 2025-07, with the labels that each got.

#4988 robot updated golang version
  .github/workflows/auto-upgrade-ci.yaml
  .github/workflows/e2e-init.yaml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-grafana-file.yaml
  Makefile.version
  images/spiderpool-agent/Dockerfile
  images/spiderpool-base/Dockerfile
  images/spiderpool-controller/Dockerfile
  images/spiderpool-plugins/Dockerfile
Labels: release/none, pr/release/robot_update_version

#5001 Update setNicAddr.sh
  tools/scripts/setNicAddr.sh
Labels: release/bug

#5000 Add setNicAddr.sh for rhel7
  tools/scripts/setNicAddr.sh
Labels: release/none
